import type { TemplateConfig } from '@/types';

const apexConfig: TemplateConfig = {
  slug: 'apex',
  name: 'Apex',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'photoUrl', label: 'Profile Photo', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Alex Rivera', section: 'hero' },
        { key: 'heroPrefix', label: 'Hero Prefix', type: 'text', placeholder: "Hi, I'm", section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Full-Stack Engineer', section: 'hero' },
        { key: 'subtitle', label: 'Hero Subtitle', type: 'textarea', placeholder: 'I design and build refined web products…', section: 'hero' },
        { key: 'statusText', label: 'Status Text', type: 'text', placeholder: 'Open to collaborations & opportunities', section: 'hero' },
        { key: 'availability', label: 'Availability Badge (nav)', type: 'text', placeholder: 'available for work', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '3+', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Years Coding', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '20+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Projects Shipped', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '12', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Happy Clients', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '8', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'OSS Contributions', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutTag', label: 'Section Tag (e.g. "01 / About")', type: 'text', placeholder: '01 / About', section: 'about' },
        { key: 'aboutHeading', label: 'Section Heading', type: 'text', placeholder: 'A short story so far.', section: 'about' },
        { key: 'aboutPara1', label: 'About — Paragraph 1', type: 'textarea', placeholder: 'I started coding because…', section: 'about' },
        { key: 'aboutPara2', label: 'About — Paragraph 2', type: 'textarea', placeholder: 'Today I work on…', section: 'about' },
        { key: 'aboutPara3', label: 'About — Paragraph 3', type: 'textarea', placeholder: 'Outside of work I…', section: 'about' },
        { key: 'location', label: 'Based In', type: 'text', placeholder: 'Bangalore, IN', section: 'about' },
        { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'IST (UTC+5:30)', section: 'about' },
        { key: 'languages', label: 'Languages', type: 'text', placeholder: 'EN · HI · TA', section: 'about' },
        { key: 'focus', label: 'Current Focus', type: 'text', placeholder: 'Frontend systems & DX', section: 'about' },
      ],
    },
    {
      key: 'skills',
      label: 'Skills & Learning',
      fields: [
        { key: 'skillsTag', label: 'Section Tag', type: 'text', placeholder: '02 / Skills', section: 'skills' },
        { key: 'skillsHeading', label: 'Section Heading', type: 'text', placeholder: 'What I work with.', section: 'skills' },
        { key: 'skillsSub', label: 'Section Subheading', type: 'textarea', placeholder: "The tools I've learned the hard way and trust to ship.", section: 'skills' },
        { key: 'skillsJson', label: 'Skills JSON - array of { category, items }', type: 'textarea', placeholder: 'See default content for format', section: 'skills' },
        { key: 'proficienciesJson', label: 'Core Mastery JSON - array of { name, level }', type: 'textarea', placeholder: 'See default content for format', section: 'skills' },
        { key: 'currentlyLearning', label: 'Currently Learning (comma-sep)', type: 'textarea', placeholder: 'Rust, WebAssembly, System Design', section: 'skills' },
      ],
    },
    {
      key: 'experience',
      label: 'Experience',
      fields: [
        { key: 'expTag', label: 'Section Tag', type: 'text', placeholder: '03 / Experience', section: 'experience' },
        { key: 'expHeading', label: 'Section Heading', type: 'text', placeholder: "Where I've done the work.", section: 'experience' },
        { key: 'expJson', label: 'Experience JSON - array of { period, role, company, summary, bullets, stack, isCurrent }', type: 'textarea', placeholder: 'See default content for format', section: 'experience' },
      ],
    },
    {
      key: 'projects',
      label: 'Projects',
      fields: [
        { key: 'projTag', label: 'Section Tag', type: 'text', placeholder: '04 / Selected work', section: 'projects' },
        { key: 'projHeading', label: 'Section Heading', type: 'text', placeholder: "Things I've built.", section: 'projects' },
        { key: 'projSub', label: 'Section Subheading', type: 'textarea', placeholder: 'Side projects, contract work, and small experiments.', section: 'projects' },
        { key: 'projJson', label: 'Projects JSON - array of { title, tag, desc, stack, liveUrl, githubUrl }', type: 'textarea', placeholder: 'See default content for format', section: 'projects' },
      ],
    },
    {
      key: 'education',
      label: 'Education & Certifications',
      fields: [
        { key: 'eduTag', label: 'Section Tag', type: 'text', placeholder: '05 / Background', section: 'education' },
        { key: 'eduHeading', label: 'Section Heading', type: 'text', placeholder: 'Education & Certifications.', section: 'education' },
        { key: 'educationJson', label: 'Education JSON - array of { school, degree, period, detail }', type: 'textarea', placeholder: 'See default content for format', section: 'education' },
        { key: 'certsJson', label: 'Certifications JSON - array of { name, issuer, year, url }', type: 'textarea', placeholder: 'See default content for format', section: 'education' },
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testTag', label: 'Section Tag', type: 'text', placeholder: '06 / Kind words', section: 'testimonials' },
        { key: 'testHeading', label: 'Section Heading', type: 'text', placeholder: 'What people say.', section: 'testimonials' },
        { key: 'testimonialsJson', label: 'Testimonials JSON - array of { quote, author, role }', type: 'textarea', placeholder: 'See default content for format', section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactTag', label: 'Section Tag', type: 'text', placeholder: '07 / Contact', section: 'contact' },
        { key: 'contactHeadline', label: 'Contact Headline', type: 'text', placeholder: "Let's build something worth shipping.", section: 'contact' },
        { key: 'contactSub', label: 'Contact Subtext', type: 'textarea', placeholder: "I'm always open to interesting conversations…", section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'you@example.com', section: 'contact' },
        { key: 'githubUrl', label: 'GitHub URL', type: 'url', placeholder: 'https://github.com/username', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/username', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://x.com/username', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorAccent', label: 'Accent Color (primary)', type: 'color', placeholder: '#a78bfa', section: 'theme' },
        { key: 'colorAccent2', label: 'Accent Color (secondary)', type: 'color', placeholder: '#22d3ee', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Alex Rivera',
    heroPrefix: "Hi, I'm",
    title: 'Full-Stack Engineer & Builder',
    subtitle: 'I design and build refined web products — from first prototype to production-grade interfaces. Crafting work that feels considered, fast, and human.',
    statusText: 'Open to collaborations & opportunities',
    availability: 'available for work',
    photoUrl: '',
    resumeUrl: '',
    stat1Num: '3+', stat1Label: 'Years Coding',
    stat2Num: '20+', stat2Label: 'Projects Shipped',
    stat3Num: '12', stat3Label: 'Happy Clients',
    stat4Num: '8', stat4Label: 'OSS Contributions',
    aboutTag: '01 / About',
    aboutHeading: 'A short story so far.',
    aboutPara1: 'I started coding because I wanted to bring the things in my head into the browser — every animation, every interaction, every small detail that makes a product feel alive.',
    aboutPara2: "Today I work across the stack — TypeScript on both sides, React for what users see, Node and Postgres for what they don't. I care about accessibility, performance budgets, and writing code that the next person can actually read.",
    aboutPara3: "When I'm not at a keyboard you'll find me reading dev essays, building tiny side projects, or quietly redesigning apps in my head.",
    location: 'Bangalore, IN',
    timezone: 'IST (UTC+5:30)',
    languages: 'EN · HI · TA',
    focus: 'Frontend systems & DX',
    skillsTag: '02 / Skills',
    skillsHeading: 'What I work with.',
    skillsSub: "The tools I've learned by shipping — comfortable today, still sharpening tomorrow.",
    skillsJson: JSON.stringify([
      { category: 'Languages', items: 'TypeScript, JavaScript, Python, SQL, HTML, CSS' },
      { category: 'Frameworks', items: 'React, Next.js, Node.js, Express, Tailwind CSS' },
      { category: 'Backend & Data', items: 'PostgreSQL, MongoDB, Redis, Prisma, REST, GraphQL' },
      { category: 'Tooling', items: 'Git, Docker, Vite, Vitest, Playwright, GitHub Actions' },
      { category: 'Cloud & Ops', items: 'Vercel, AWS (basics), Cloudflare, Supabase' },
      { category: 'Craft', items: 'A11y (WCAG), Animation, Design systems, Figma' },
    ]),
    proficienciesJson: JSON.stringify([
      { name: 'React / Next.js', level: 5 },
      { name: 'TypeScript', level: 5 },
      { name: 'Node.js', level: 4 },
      { name: 'PostgreSQL', level: 4 },
      { name: 'CSS & Animation', level: 4 },
      { name: 'System Design', level: 3 },
    ]),
    currentlyLearning: 'Rust, WebAssembly, System Design, Distributed Systems',
    expTag: '03 / Experience',
    expHeading: "Where I've done the work.",
    expJson: JSON.stringify([
      {
        period: 'Jan 2025 – Present',
        nowLabel: 'Present',
        duration: '11 months',
        role: 'Frontend Engineer',
        company: 'Arcadia Labs · Series A SaaS',
        summary: 'Leading the dashboard surface used by 2,000+ teams across analytics & billing flows.',
        bullets: 'Redesigned the onboarding flow → +28% activation in 6 weeks\nMigrated the design system to Radix + Tailwind across 80+ components\nShaved 41% off bundle size via route-level code splitting\nIntroduced visual regression testing — caught 12 prod bugs pre-merge\nMentored two interns through their first prod releases',
        stack: 'TypeScript, React, Next.js, tRPC, Postgres, Tailwind, Playwright',
        isCurrent: true,
      },
      {
        period: 'Mar 2024 – Dec 2024',
        nowLabel: '',
        duration: '10 months',
        role: 'Full-Stack Developer',
        company: 'Pixelmint Studio · Product agency',
        summary: 'Built and shipped client web products across fintech, education, and creator tools.',
        bullets: 'Shipped 6 production sites from Figma to deploy\nBuilt a multi-tenant CMS handling 40k+ monthly visits\nIntegrated Stripe & Razorpay flows for two SaaS clients\nWrote internal CLI cutting project setup from 2hrs → 8min',
        stack: 'Next.js, Node.js, MongoDB, Stripe, Tailwind',
        isCurrent: false,
      },
      {
        period: 'Jun 2023 – Feb 2024',
        nowLabel: '',
        duration: '9 months',
        role: 'Web Developer Intern',
        company: 'Brightline Tech · Edtech startup',
        summary: 'Joined as a junior dev; shipped my first features end-to-end on a live product.',
        bullets: 'Built 24 reusable UI components used across 3 internal apps\nFixed a long-standing memory leak in the live class module\nImproved Lighthouse score from 58 → 92 on the marketing site',
        stack: 'React, JavaScript, Sass, Firebase',
        isCurrent: false,
      },
    ]),
    projTag: '04 / Selected work',
    projHeading: "Things I've built.",
    projSub: 'A mix of client work, side projects, and small experiments I keep going back to.',
    projJson: JSON.stringify([
      {
        title: 'Lumen Analytics',
        tag: '2025 · Solo',
        desc: "A minimal product analytics dashboard built around the idea that most teams don't need 90% of the charts they pay for. Real-time events via Postgres + Server-Sent Events.",
        stack: 'Next.js, TypeScript, Postgres, Tailwind',
        liveUrl: '',
        githubUrl: '',
      },
      {
        title: 'Notewise',
        tag: '2025 · OSS',
        desc: 'A keyboard-first markdown notes app with AI-powered linking. Designed to feel as fast as a text file, with the structure of a wiki.',
        stack: 'React, IndexedDB, Tauri, OpenAI',
        liveUrl: '',
        githubUrl: '',
      },
      {
        title: 'Kindlr',
        tag: '2024 · Client',
        desc: 'A friendly community platform for a 5,000-member book club. Threaded discussions, reading lists, and a custom recommendation feed.',
        stack: 'Next.js, Postgres, Supabase, Resend',
        liveUrl: '',
        githubUrl: '',
      },
      {
        title: 'Stoplight',
        tag: '2024 · Side project',
        desc: 'A tiny status-page-as-a-service for indie devs. One Markdown file → a hosted status page with incident timelines.',
        stack: 'Astro, Cloudflare Workers, KV',
        liveUrl: '',
        githubUrl: '',
      },
      {
        title: 'Riffmap',
        tag: '2024 · Hackathon',
        desc: "Won a 48-hour hackathon for indie musicians: a visual map of songs by mood, BPM, and key — pulled live from Spotify's API.",
        stack: 'Next.js, D3, Spotify API',
        liveUrl: '',
        githubUrl: '',
      },
      {
        title: 'Inkwell',
        tag: '2023 · Learning',
        desc: 'My very first deployed project. A minimalist writing app with a typewriter mode, focus timer, and word-count goals.',
        stack: 'React, Vite, Vercel',
        liveUrl: '',
        githubUrl: '',
      },
    ]),
    eduTag: '05 / Background',
    eduHeading: 'Education & Certifications.',
    educationJson: JSON.stringify([
      {
        school: 'Anna University',
        degree: 'B.E. in Computer Science',
        period: '2020 – 2024',
        detail: 'CGPA 8.7/10 · Active in the coding club, organised two open hackathons, finalist in Smart India Hackathon 2023.',
      },
      {
        school: 'Self-taught · Online',
        degree: 'Continuous learning',
        period: '2021 – Now',
        detail: "Frontend Masters, Theo's courses, Josh Comeau's CSS for JS, Kent C. Dodds' EpicReact. Reading 1 dev book a month.",
      },
    ]),
    certsJson: JSON.stringify([
      { name: 'Meta Front-End Developer', issuer: 'Meta · Coursera', year: '2024', url: '' },
      { name: 'AWS Certified Cloud Practitioner', issuer: 'Amazon Web Services', year: '2024', url: '' },
      { name: 'Epic React (Pro)', issuer: 'Kent C. Dodds', year: '2023', url: '' },
    ]),
    testTag: '06 / Kind words',
    testHeading: 'What people say.',
    testimonialsJson: JSON.stringify([
      { quote: "One of the rare engineers who cares about both the pixel and the principle. Our product is faster and more accessible because of them.", author: 'Priya Menon', role: 'Engineering Lead · Arcadia Labs' },
      { quote: "Took our vague idea and turned it into a launched product in six weeks. Communicates clearly, ships consistently — would hire again in a heartbeat.", author: 'Daniel Park', role: 'Founder · Kindlr' },
    ]),
    contactTag: '07 / Contact',
    contactHeadline: "Let's build something worth shipping.",
    contactSub: "I'm always open to interesting conversations — collaborations, freelance work, or just trading notes on craft.",
    contactEmail: 'hello@example.com',
    githubUrl: 'https://github.com/yourname',
    linkedinUrl: 'https://linkedin.com/in/yourname',
    twitterUrl: 'https://x.com/yourname',
    colorAccent: '#a78bfa',
    colorAccent2: '#22d3ee',
  },
};

export default apexConfig;
