import type { TemplateConfig } from '@/types';

const atelierConfig: TemplateConfig = {
  slug: 'atelier',
  name: 'Atelier',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'photoUrl', label: 'Portrait / Profile Photo', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Iris Lavelle', section: 'hero' },
        { key: 'role', label: 'Role / Title', type: 'text', placeholder: 'Independent Designer & Art Director', section: 'hero' },
        { key: 'studioMark', label: 'Studio Mark (top-left dateline · leave empty to remove)', type: 'text', placeholder: 'ATELIER · STUDIO', section: 'hero' },
        { key: 'heroTagline', label: 'Hero Tagline (centre dateline)', type: 'text', placeholder: 'Portfolio · 2024–2026', section: 'hero' },
        { key: 'subtitle', label: 'Statement / Subtitle', type: 'textarea', placeholder: 'I design considered brand systems, editorial work, and quiet interfaces for studios who care about craft.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Available Q2 2026', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume / CV (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'statsLabel', label: 'Stats Label (leave empty to remove)', type: 'text', placeholder: 'By the numbers', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '6', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Years Practicing', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '48', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Projects Shipped', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '12', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Studios Collaborated', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '5', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'Industry Awards', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutSectionLabel', label: 'Section Label', type: 'text', placeholder: '01 — About', section: 'about' },
        { key: 'aboutHeading', label: 'Section Heading', type: 'text', placeholder: 'Designing with care, since 2019.', section: 'about' },
        { key: 'aboutPhotoUrl', label: 'About Section Photo', type: 'image', placeholder: '', section: 'about' },
        { key: 'aboutPara1', label: 'About — Paragraph 1', type: 'textarea', placeholder: 'I started designing because…', section: 'about' },
        { key: 'aboutPara2', label: 'About — Paragraph 2', type: 'textarea', placeholder: 'Today I work with…', section: 'about' },
        { key: 'aboutPara3', label: 'About — Paragraph 3', type: 'textarea', placeholder: 'When I am not designing…', section: 'about' },
        { key: 'aboutQuote', label: 'Pull Quote / Philosophy', type: 'textarea', placeholder: 'Good design is quiet. Great design is invisible.', section: 'about' },
        { key: 'location', label: 'Based In', type: 'text', placeholder: 'Lisbon, PT', section: 'about' },
        { key: 'speciality', label: 'Speciality / Focus', type: 'text', placeholder: 'Brand Systems · Editorial', section: 'about' },
        { key: 'education', label: 'Education', type: 'text', placeholder: 'BA Visual Comms · ECAL', section: 'about' },
        { key: 'languages', label: 'Languages', type: 'text', placeholder: 'EN · PT · FR', section: 'about' },
      ],
    },
    {
      key: 'work',
      label: 'Selected Work',
      fields: [
        { key: 'workSectionLabel', label: 'Section Label', type: 'text', placeholder: '02 — Selected Work', section: 'work' },
        { key: 'workHeading', label: 'Section Heading', type: 'text', placeholder: 'Recent work I am proud of.', section: 'work' },
        { key: 'workSubtitle', label: 'Section Subheading', type: 'textarea', placeholder: 'A small selection of projects across brand, editorial, and interface design.', section: 'work' },
      ],
    },
    {
      key: 'disciplines',
      label: 'Disciplines',
      fields: [
        { key: 'discSectionLabel', label: 'Section Label', type: 'text', placeholder: '03 — Disciplines', section: 'disciplines' },
        { key: 'discHeading', label: 'Section Heading', type: 'text', placeholder: 'What I make.', section: 'disciplines' },
        { key: 'discSubtitle', label: 'Section Subheading', type: 'textarea', placeholder: 'The kinds of work I take on — alone or alongside studios.', section: 'disciplines' },
      ],
    },
    {
      key: 'process',
      label: 'Process',
      fields: [
        { key: 'procSectionLabel', label: 'Section Label', type: 'text', placeholder: '04 — Process', section: 'process' },
        { key: 'procHeading', label: 'Section Heading', type: 'text', placeholder: 'How I work.', section: 'process' },
        { key: 'procSubtitle', label: 'Section Subheading', type: 'textarea', placeholder: 'A simple, four-step process — refined across dozens of projects.', section: 'process' },
      ],
    },
    {
      key: 'recognition',
      label: 'Recognition & Clients',
      fields: [
        { key: 'recogSectionLabel', label: 'Section Label', type: 'text', placeholder: '05 — Recognition', section: 'recognition' },
        { key: 'recogHeading', label: 'Section Heading', type: 'text', placeholder: 'Press, awards, and people I have worked with.', section: 'recognition' },
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testSectionLabel', label: 'Section Label', type: 'text', placeholder: '06 — Words', section: 'testimonials' },
        { key: 'testHeading', label: 'Section Heading', type: 'text', placeholder: 'In their own words.', section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactSectionLabel', label: 'Section Label', type: 'text', placeholder: '07 — Contact', section: 'contact' },
        { key: 'contactHeadline', label: 'Contact Headline', type: 'text', placeholder: 'Let us make something together.', section: 'contact' },
        { key: 'contactSub', label: 'Contact Subtext', type: 'textarea', placeholder: 'I am taking on a small number of projects this year. Tell me about yours.', section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'hello@iris.studio', section: 'contact' },
        { key: 'instagramUrl', label: 'Instagram URL', type: 'url', placeholder: 'https://instagram.com/iris', section: 'contact' },
        { key: 'behanceUrl', label: 'Behance URL', type: 'url', placeholder: 'https://behance.net/iris', section: 'contact' },
        { key: 'dribbbleUrl', label: 'Dribbble URL', type: 'url', placeholder: 'https://dribbble.com/iris', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/iris', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://x.com/iris', section: 'contact' },
        { key: 'footerSig', label: 'Footer Signature (right side · leave empty to remove)', type: 'text', placeholder: 'Made slowly, in Lisbon.', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background (Paper)', type: 'color', placeholder: '#f5f0e8', section: 'theme' },
        { key: 'colorBgElev', label: 'Background Elevated', type: 'color', placeholder: '#eee6d8', section: 'theme' },
        { key: 'colorBgCard', label: 'Background Card', type: 'color', placeholder: '#ffffff', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (Ink)', type: 'color', placeholder: '#0d0d0d', section: 'theme' },
        { key: 'colorFgMuted', label: 'Foreground Muted', type: 'color', placeholder: '#4a4a48', section: 'theme' },
        { key: 'colorFgFaint', label: 'Foreground Faint', type: 'color', placeholder: '#8a8a85', section: 'theme' },
        { key: 'colorLine', label: 'Line / Border', type: 'color', placeholder: '#d8d2c4', section: 'theme' },
        { key: 'colorLineStrong', label: 'Line Strong', type: 'color', placeholder: '#b9b2a2', section: 'theme' },
        { key: 'colorAccent', label: 'Accent', type: 'color', placeholder: '#b8503a', section: 'theme' },
        { key: 'colorAccentSoft', label: 'Accent Soft', type: 'color', placeholder: '#f4d9cf', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Iris Lavelle',
    role: 'Independent Designer & Art Director',
    studioMark: 'ATELIER · STUDIO',
    heroTagline: 'Portfolio · 2024–2026',
    subtitle: 'I design considered brand systems, editorial work, and quiet interfaces for studios and founders who care about craft.',
    availability: 'Available Q2 2026',
    photoUrl: '',
    resumeUrl: '',
    statsLabel: 'By the numbers',
    stat1Num: '6', stat1Label: 'Years Practicing',
    stat2Num: '48', stat2Label: 'Projects Shipped',
    stat3Num: '12', stat3Label: 'Studios Collaborated',
    stat4Num: '5', stat4Label: 'Industry Awards',

    aboutSectionLabel: '01 — About',
    aboutHeading: 'Designing with care, since 2019.',
    aboutPhotoUrl: '',
    aboutPara1: 'I started designing in the margins of a notebook full of unwritten zines. Six years on, that instinct has not really left — I still care about the small, felt details as much as I care about systems, hierarchy, and how a thing reads on the third look.',
    aboutPara2: 'Today I run a small studio of one, working with a handful of brands and publications each year. Before that I spent four years inside two design studios in Lisbon and London, leading brand work for hospitality, culture, and software clients.',
    aboutPara3: 'When I am not at the desk, I am usually in a museum bookshop, scanning old jazz LPs, or quietly judging restaurant menu typography.',
    aboutQuote: 'Good design is quiet. Great design is invisible until you remove it.',
    location: 'Lisbon, PT',
    speciality: 'Brand Systems · Editorial',
    education: 'BA Visual Comms · ECAL',
    languages: 'EN · PT · FR',

    workSectionLabel: '02 — Selected Work',
    workHeading: 'Recent work I am proud of.',
    workSubtitle: 'A small selection of projects across brand, editorial, and interface design — chosen because each taught me something new.',
    workJson: JSON.stringify([
      { title: 'Maison Quaí', category: 'Brand · Hospitality', year: '2025', role: 'Designer & Art Direction', description: 'A complete brand system for a Lisbon natural-wine bar — type, palette, packaging, and an unhurried website that loads like a printed menu.', image: '', liveUrl: '' },
      { title: 'Numero Issue 04', category: 'Editorial · Print', year: '2025', role: 'Designer', description: 'Art direction and layout for the fourth issue of an independent culture journal. 144 pages, two specials, a custom display cut, and one stubborn pull quote.', image: '', liveUrl: '' },
      { title: 'Quill OS', category: 'Interface · Software', year: '2024', role: 'Brand & UI Designer', description: 'A focused writing app for long-form drafts. I designed the brand, the marketing site, and the entire reading-mode interface across light and dark themes.', image: '', liveUrl: '' },
      { title: 'Florea Botanical', category: 'Packaging · Print', year: '2024', role: 'Designer', description: 'Six packaging illustrations and a complete label system for an indie tea blend, sold in 40 specialty shops across Europe.', image: '', liveUrl: '' },
      { title: 'Saudade Festival', category: 'Identity · Event', year: '2024', role: 'Lead Designer', description: 'Posters, programme, motion bumpers, and on-site wayfinding for a three-day Portuguese music festival celebrating its first decade.', image: '', liveUrl: '' },
      { title: 'Studio Verdant Site', category: 'Web · Studio', year: '2023', role: 'Designer & Developer', description: 'A complete rebuild of an architecture studio website — slow-loading photography, generous whitespace, and a CMS that finally feels like writing.', image: '', liveUrl: '' },
    ]),

    discSectionLabel: '03 — Disciplines',
    discHeading: 'What I make.',
    discSubtitle: 'Four kinds of work — usually overlapping, often messy — taken on alone or alongside studios.',
    discJson: JSON.stringify([
      { number: '01', title: 'Brand Systems', description: 'Identity, type, palette, voice, and the templates that keep them alive long after launch.', items: 'Naming, Wordmarks, Type, Voice, Guidelines, Templates' },
      { number: '02', title: 'Editorial & Print', description: 'Magazines, books, programmes, and printed objects designed to be held and re-read.', items: 'Magazines, Books, Posters, Programmes, Catalogues' },
      { number: '03', title: 'Digital Interfaces', description: 'Quiet websites and product surfaces — built with restraint, designed to scale.', items: 'Marketing sites, Product UI, Design Systems, Motion' },
      { number: '04', title: 'Art Direction', description: 'Direction for shoots, illustration, and the in-between work that holds a brand together.', items: 'Photography, Illustration, Campaign work, Direction' },
    ]),

    procSectionLabel: '04 — Process',
    procHeading: 'How I work.',
    procSubtitle: 'A simple, four-step process — refined across dozens of projects, never rigid.',
    procJson: JSON.stringify([
      { number: '01', title: 'Listen', description: 'A long, slow conversation. I want to understand the work, the people, and the constraints — before a single line is drawn.' },
      { number: '02', title: 'Sketch', description: 'Rough explorations, mood, and reference. A wide first net before narrowing. The fastest, messiest part.' },
      { number: '03', title: 'Refine', description: 'Two or three directions, then one. We tighten the system, test it in context, and pressure-test edge cases.' },
      { number: '04', title: 'Deliver', description: 'Final assets, guidelines, and the handoff a team can actually use. Plus a year of light support if you need it.' },
    ]),

    recogSectionLabel: '05 — Recognition',
    recogHeading: 'Press, awards, and people I have worked with.',
    pressJson: JSON.stringify([
      { publication: 'It is Nice That', item: 'Feature on Maison Quaí brand system', year: '2025', url: '' },
      { publication: 'Brand New', item: 'Noted: Numero Issue 04', year: '2025', url: '' },
      { publication: 'Type Directors Club', item: 'Award of Excellence — Editorial', year: '2024', url: '' },
      { publication: 'Print Magazine', item: 'New Visual Artist 2024', year: '2024', url: '' },
      { publication: 'AIGA Eye on Design', item: 'Interview on independent practice', year: '2024', url: '' },
      { publication: 'D&AD Awards', item: 'Wood Pencil — Brand Identity', year: '2023', url: '' },
    ]),
    clientsJson: JSON.stringify([
      { name: 'Maison Quaí' }, { name: 'Numero Journal' }, { name: 'Quill OS' },
      { name: 'Florea Botanical' }, { name: 'Saudade Festival' }, { name: 'Studio Verdant' },
      { name: 'The Lisbon Plate' }, { name: 'Atlas & Branch' }, { name: 'Casa Nova Coffee' },
      { name: 'North Cape Press' }, { name: 'Ridgepoint Films' }, { name: 'Lume Skincare' },
    ]),

    testSectionLabel: '06 — Words',
    testHeading: 'In their own words.',
    testimonialsJson: JSON.stringify([
      { quote: 'Iris does the rare thing — she actually listens before she draws. Three months later the brand still feels like us, and that is the highest compliment I can pay a designer.', author: 'Mariana Costa', role: 'Founder', company: 'Maison Quaí' },
      { quote: 'A craftsperson in the best, most outdated sense of the word. We have published four issues together and each one is better than the last.', author: 'Henrique Lopes', role: 'Editor-in-Chief', company: 'Numero Journal' },
      { quote: 'She joined the project late and somehow rescued the whole thing — the brand, the launch, my sanity. Every founder needs an Iris.', author: 'Theo Akande', role: 'Founder', company: 'Quill OS' },
    ]),

    contactSectionLabel: '07 — Contact',
    contactHeadline: 'Let us make something together.',
    contactSub: 'I am taking on a small number of projects this year. If you are working on something thoughtful, I would like to hear about it.',
    contactEmail: 'hello@iris.studio',
    instagramUrl: 'https://instagram.com/iris',
    behanceUrl: 'https://behance.net/iris',
    dribbbleUrl: 'https://dribbble.com/iris',
    linkedinUrl: 'https://linkedin.com/in/iris',
    twitterUrl: 'https://x.com/iris',
    footerSig: 'Made slowly, in Lisbon.',

    colorBg: '#f5f0e8',
    colorBgElev: '#eee6d8',
    colorBgCard: '#ffffff',
    colorFg: '#0d0d0d',
    colorFgMuted: '#4a4a48',
    colorFgFaint: '#8a8a85',
    colorLine: '#d8d2c4',
    colorLineStrong: '#b9b2a2',
    colorAccent: '#b8503a',
    colorAccentSoft: '#f4d9cf',
  },
};

export default atelierConfig;
