import type { TemplateConfig } from '@/types';

const debutConfig: TemplateConfig = {
  slug: 'debut',
  name: 'Debut',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'photoUrl', label: 'Profile Photo', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Riya Kapoor', section: 'hero' },
        { key: 'title', label: 'Role / Title', type: 'text', placeholder: 'Visual Designer', section: 'hero' },
        { key: 'heroTagline', label: 'Hero Tagline (3 lines · line 1 main · line 2 italic accent · line 3 underlined)', type: 'textarea', placeholder: "Hi 👋 I'm Riya.\nA visual designer\nin the making.", section: 'hero' },
        { key: 'bio', label: 'Bio (supports **bold**)', type: 'textarea', placeholder: "I'm a recent grad obsessed with brand identity…", section: 'hero' },
        { key: 'availability', label: 'Availability (top banner badge)', type: 'text', placeholder: 'Available · graduating June 2026', section: 'hero' },
        { key: 'location', label: 'Location', type: 'text', placeholder: 'Mumbai, IN', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume / CV (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'heroCtaPrimary', label: 'Primary CTA Button Label', type: 'text', placeholder: 'See my work', section: 'hero' },
        { key: 'heroCtaSecondary', label: 'Secondary CTA Button Label', type: 'text', placeholder: 'Download resume', section: 'hero' },
        { key: 'navCtaLabel', label: 'Nav CTA Button Label', type: 'text', placeholder: 'Get in touch', section: 'hero' },
        { key: 'heroQuickLocationLabel', label: 'Quick Stat — Location Label', type: 'text', placeholder: 'Based in', section: 'hero' },
        { key: 'heroQuickFocusLabel', label: 'Quick Stat — Focus Label', type: 'text', placeholder: 'Focused on', section: 'hero' },
        { key: 'heroQuickFocus', label: 'Quick Stat — Focus Value', type: 'text', placeholder: 'Brand · Editorial', section: 'hero' },
        { key: 'heroQuickStatusLabel', label: 'Quick Stat — Status Label', type: 'text', placeholder: 'Status', section: 'hero' },
        { key: 'heroQuickStatus', label: 'Quick Stat — Status Value', type: 'text', placeholder: 'Seeking first role', section: 'hero' },
        { key: 'photoBadge', label: 'Photo Overlay Badge', type: 'text', placeholder: 'Open to work', section: 'hero' },
        { key: 'photoCard1Label', label: 'Photo Card 1 Label', type: 'text', placeholder: 'Class of', section: 'hero' },
        { key: 'photoCard1Value', label: 'Photo Card 1 Value', type: 'text', placeholder: '2026', section: 'hero' },
        { key: 'photoCard2Label', label: 'Photo Card 2 Label', type: 'text', placeholder: 'Currently', section: 'hero' },
        { key: 'photoCard2Value', label: 'Photo Card 2 Value', type: 'text', placeholder: 'Final year', section: 'hero' },
        { key: 'statusBarItems', label: 'Top Status Bar Items (comma-sep)', type: 'textarea', placeholder: 'Open to work, Looking for first role, Junior visual designer', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '01 / About me', section: 'about' },
        { key: 'aboutHeading', label: 'Heading (main)', type: 'text', placeholder: 'A little', section: 'about' },
        { key: 'aboutHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: 'about me.', section: 'about' },
        { key: 'aboutMeta', label: 'Section Meta (top-right)', type: 'text', placeholder: 'who · what · why', section: 'about' },
        { key: 'aboutPara1', label: 'About — Paragraph 1', type: 'textarea', placeholder: "I'm a recent grad…", section: 'about' },
        { key: 'aboutPara2', label: 'About — Paragraph 2 (optional)', type: 'textarea', placeholder: 'Outside of design…', section: 'about' },
        { key: 'passionsLabel', label: 'Passions Section Label', type: 'text', placeholder: 'Things that light me up', section: 'about' },
        { key: 'passions', label: 'Passions / Interests (comma-sep, max 8)', type: 'textarea', placeholder: 'Typography, Print, Editorial, Color theory, Brand systems', section: 'about' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '12', section: 'about' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Projects', section: 'about' },
        { key: 'stat1Sub', label: 'Stat 1 — Subtext', type: 'text', placeholder: 'Shipped to brief', section: 'about' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '3', section: 'about' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Internships', section: 'about' },
        { key: 'stat2Sub', label: 'Stat 2 — Subtext', type: 'text', placeholder: 'completed', section: 'about' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '2026', section: 'about' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Class of', section: 'about' },
        { key: 'stat3Sub', label: 'Stat 3 — Subtext', type: 'text', placeholder: '', section: 'about' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '8.7', section: 'about' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'GPA', section: 'about' },
        { key: 'stat4Sub', label: 'Stat 4 — Subtext', type: 'text', placeholder: '', section: 'about' },
      ],
    },
    {
      key: 'education',
      label: 'Education',
      fields: [
        { key: 'eduSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '02 / Education', section: 'education' },
        { key: 'eduHeading', label: 'Heading (main)', type: 'text', placeholder: 'Where I', section: 'education' },
        { key: 'eduHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: 'studied.', section: 'education' },
        { key: 'eduGradeLabel', label: 'Grade/CGPA Label', type: 'text', placeholder: 'Grade', section: 'education' },
      ],
    },
    {
      key: 'internships',
      label: 'Internships',
      fields: [
        { key: 'internsSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '03 / Internships', section: 'internships' },
        { key: 'internsHeading', label: 'Heading (main)', type: 'text', placeholder: 'Real-world', section: 'internships' },
        { key: 'internsHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: 'experience.', section: 'internships' },
      ],
    },
    {
      key: 'work',
      label: 'Selected Work',
      fields: [
        { key: 'workSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '04 / Selected work', section: 'work' },
        { key: 'workHeading', label: 'Heading (main)', type: 'text', placeholder: 'Things I', section: 'work' },
        { key: 'workHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: "'ve made.", section: 'work' },
        { key: 'workMeta', label: 'Section Meta', type: 'text', placeholder: 'click any tile', section: 'work' },
        { key: 'workLinkLabel', label: 'Project Link Label (with URL)', type: 'text', placeholder: 'View case', section: 'work' },
        { key: 'workLinkLabelEmpty', label: 'Project Link Label (no URL)', type: 'text', placeholder: 'Case study', section: 'work' },
        { key: 'workEmptyText', label: 'Empty State Text', type: 'text', placeholder: 'No projects yet — add your work from the dashboard ✦', section: 'work' },
      ],
    },
    {
      key: 'skills',
      label: 'Skills',
      fields: [
        { key: 'skillsSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '05 / Skills', section: 'skills' },
        { key: 'skillsHeading', label: 'Heading (main)', type: 'text', placeholder: 'My', section: 'skills' },
        { key: 'skillsHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: 'toolbox.', section: 'skills' },
        { key: 'learningEyebrow', label: 'Currently-Learning Eyebrow', type: 'text', placeholder: 'Currently exploring', section: 'skills' },
        { key: 'learningTitle', label: 'Currently-Learning Title', type: 'text', placeholder: 'Currently learning', section: 'skills' },
        { key: 'learningSub', label: 'Currently-Learning Subtitle', type: 'textarea', placeholder: "I'm always picking up new tools…", section: 'skills' },
        { key: 'currentlyLearning', label: 'Currently Learning Items (comma-sep)', type: 'textarea', placeholder: 'Motion design, After Effects, Webflow', section: 'skills' },
      ],
    },
    {
      key: 'wishlist',
      label: 'Looking For',
      fields: [
        { key: 'wishlistSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '06 / Looking for', section: 'wishlist' },
        { key: 'wishlistHeading', label: 'Heading (main)', type: 'text', placeholder: 'My', section: 'wishlist' },
        { key: 'wishlistHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: 'wishlist.', section: 'wishlist' },
        { key: 'dreamRolesLabel', label: 'Dream Roles Eyebrow', type: 'text', placeholder: 'Roles I want', section: 'wishlist' },
        { key: 'dreamRolesHeading', label: 'Dream Roles Heading (use <em> for italics)', type: 'text', placeholder: 'Looking for my first <em>full-time</em> role.', section: 'wishlist' },
        { key: 'dreamRolesSub', label: 'Dream Roles Subtext', type: 'textarea', placeholder: "I'm open to junior or associate roles…", section: 'wishlist' },
        { key: 'dreamRoles', label: 'Dream Roles (comma-sep)', type: 'textarea', placeholder: 'Junior Visual Designer, Brand Designer, Editorial Designer', section: 'wishlist' },
        { key: 'dreamCompaniesLabel', label: 'Dream Companies Eyebrow', type: 'text', placeholder: 'Studios I admire', section: 'wishlist' },
        { key: 'dreamCompaniesHeading', label: 'Dream Companies Heading (use <em>)', type: 'text', placeholder: "Dream teams I'd <em>love</em> to work with.", section: 'wishlist' },
        { key: 'dreamCompaniesSub', label: 'Dream Companies Subtext', type: 'textarea', placeholder: 'A short list of studios doing work I admire…', section: 'wishlist' },
        { key: 'dreamCompanies', label: 'Dream Companies (comma-sep)', type: 'textarea', placeholder: 'Pentagram, Wieden+Kennedy, Mother', section: 'wishlist' },
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '07 / Kind words', section: 'testimonials' },
        { key: 'testHeading', label: 'Heading (main)', type: 'text', placeholder: 'What', section: 'testimonials' },
        { key: 'testHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: 'people say.', section: 'testimonials' },
        { key: 'testMeta', label: 'Section Meta', type: 'text', placeholder: 'from mentors · classmates · clients', section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactEyebrow', label: 'Contact Eyebrow', type: 'text', placeholder: "Let's chat", section: 'contact' },
        { key: 'contactHeading', label: 'Heading (main)', type: 'text', placeholder: 'Hire me, or', section: 'contact' },
        { key: 'contactHeadingEm', label: 'Heading (italic accent)', type: 'text', placeholder: 'just say hi.', section: 'contact' },
        { key: 'contactSub', label: 'Contact Subtext', type: 'textarea', placeholder: "I'm looking for my first full-time role…", section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'hello@riya.design', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/riya', section: 'contact' },
        { key: 'linkedinHandle', label: 'LinkedIn Display Text', type: 'text', placeholder: '@riyakapoor', section: 'contact' },
        { key: 'behanceUrl', label: 'Behance URL', type: 'url', placeholder: 'https://behance.net/riya', section: 'contact' },
        { key: 'behanceHandle', label: 'Behance Display Text', type: 'text', placeholder: '@riyakapoor', section: 'contact' },
        { key: 'dribbbleUrl', label: 'Dribbble URL', type: 'url', placeholder: 'https://dribbble.com/riya', section: 'contact' },
        { key: 'dribbbleHandle', label: 'Dribbble Display Text', type: 'text', placeholder: '@riyak', section: 'contact' },
        { key: 'instagramUrl', label: 'Instagram URL', type: 'url', placeholder: 'https://instagram.com/riya', section: 'contact' },
        { key: 'instagramHandle', label: 'Instagram Display Text', type: 'text', placeholder: '@riya.designs', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://twitter.com/riya', section: 'contact' },
        { key: 'twitterHandle', label: 'Twitter Display Text', type: 'text', placeholder: '@riya', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: '#FAF8F4', section: 'theme' },
        { key: 'colorSurface', label: 'Surface', type: 'color', placeholder: '#FFFFFF', section: 'theme' },
        { key: 'colorText', label: 'Ink (Foreground)', type: 'color', placeholder: '#0F0F14', section: 'theme' },
        { key: 'colorAccent', label: 'Accent 1 (primary · coral)', type: 'color', placeholder: '#FF4F5E', section: 'theme' },
        { key: 'colorAccent2', label: 'Accent 2 (blue)', type: 'color', placeholder: '#3F58FF', section: 'theme' },
        { key: 'colorAccent3', label: 'Accent 3 (yellow)', type: 'color', placeholder: '#FFC940', section: 'theme' },
        { key: 'colorAccent4', label: 'Accent 4 (green)', type: 'color', placeholder: '#5BD68C', section: 'theme' },
        { key: 'colorAccent5', label: 'Accent 5 (purple)', type: 'color', placeholder: '#A964FF', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    photoUrl: '',
    name: 'Riya Kapoor',
    title: 'Visual Designer',
    heroTagline: "Hi 👋 I'm Riya.\nA visual designer\nin the making.",
    bio: "I'm a recent grad obsessed with **brand identity** and **editorial design**. Currently in my final year of design school and looking for my first full-time role.",
    availability: 'Available · graduating June 2026',
    location: 'Mumbai, IN',
    resumeUrl: '',
    heroCtaPrimary: 'See my work',
    heroCtaSecondary: 'Download resume',
    navCtaLabel: 'Get in touch',
    heroQuickLocationLabel: 'Based in',
    heroQuickFocusLabel: 'Focused on',
    heroQuickFocus: 'Brand · Editorial',
    heroQuickStatusLabel: 'Status',
    heroQuickStatus: 'Seeking first role',
    photoBadge: 'Open to work',
    photoCard1Label: 'Class of',
    photoCard1Value: '2026',
    photoCard2Label: 'Currently',
    photoCard2Value: 'Final year',
    statusBarItems: 'Open to work · class of 2026, Looking for my first design role, Junior visual designer, Available for full-time and internships',
    aboutSectionLabel: '01 / About me',
    aboutHeading: 'A little',
    aboutHeadingEm: 'about me.',
    aboutMeta: 'who · what · why',
    aboutPara1: "I'm a final-year design student at NID Ahmedabad, **passionate** about visual storytelling, brand systems, and the small joys of typography. I'm looking for my first full-time design role where I can keep learning and shipping good work.",
    aboutPara2: "Outside of design, I run a poster club at college, collect typography books, and brew way too much coffee. I'm happiest with a Pilot pen and a fresh sketchbook.",
    passionsLabel: 'Things that light me up',
    passions: 'Typography, Print, Editorial, Color theory, Brand systems, Illustration, Posters, Books',
    stat1Num: '12', stat1Label: 'Projects', stat1Sub: 'Shipped to brief',
    stat2Num: '3', stat2Label: 'Internships', stat2Sub: 'completed',
    stat3Num: '2026', stat3Label: 'Class of', stat3Sub: '',
    stat4Num: '8.7', stat4Label: 'CGPA', stat4Sub: '',
    eduSectionLabel: '02 / Education',
    eduHeading: 'Where I',
    eduHeadingEm: 'studied.',
    eduGradeLabel: 'CGPA',
    educationJson: JSON.stringify([
      { period: '2022 – 2026', school: 'National Institute of Design', degree: 'BDes · Communication Design', detail: 'Specialised in editorial systems, brand identity, and typography. Capstone: a 96-page magazine on craft.', grade: '8.7' },
      { period: '2020 – 2022', school: 'Modern High School', degree: 'Higher Secondary · Art Stream', detail: 'Top of class in studio art. Won 2 state-level design competitions.', grade: '94%' },
    ]),
    internsSectionLabel: '03 / Internships',
    internsHeading: 'Real-world',
    internsHeadingEm: 'experience.',
    internshipsJson: JSON.stringify([
      { period: 'May – Aug 2025', isCurrent: false, role: 'Visual Design Intern', company: 'Studio Lumen', description: 'Worked on brand identity for two early-stage startups. Supported the lead designer on type system design and packaging.', tags: 'Brand, Type, Packaging' },
      { period: 'Dec 2024 – Feb 2025', isCurrent: false, role: 'Editorial Design Intern', company: 'Folio Press', description: 'Designed layouts for a quarterly print magazine. Researched grids and handled production-ready files.', tags: 'Editorial, Print, InDesign' },
      { period: 'Jun – Jul 2024', isCurrent: false, role: 'Graphic Design Intern', company: 'Pixel & Co', description: 'Designed social campaigns and marketing assets for D2C clients across food and lifestyle.', tags: 'Social, Marketing, Illustrator' },
    ]),
    workSectionLabel: '04 / Selected work',
    workHeading: 'Things I',
    workHeadingEm: "'ve made.",
    workMeta: 'click any tile',
    workLinkLabel: 'View case',
    workLinkLabelEmpty: 'Case study',
    workEmptyText: 'No projects yet — add your work from the dashboard ✦',
    projJson: JSON.stringify([
      { title: 'Slow Press', year: '2025', category: 'Editorial', image: '', desc: 'A capstone project — a 96-page printed magazine on craft, slowness, and modern making. Designed cover to colophon.', stack: 'Editorial, Type, Print', impact: 'Capstone · Distinction', liveUrl: '' },
      { title: 'Brew Bros', year: '2025', category: 'Brand identity', image: '', desc: 'Brand identity and packaging system for a college-friendly coffee subscription. Worked with the founder from sketch to delivery.', stack: 'Identity, Packaging', impact: 'Live · 200+ subs', liveUrl: '' },
      { title: 'Re:type', year: '2024', category: 'Type design', image: '', desc: 'A personal exploration in modular typography — designed a display typeface from scratch in 8 weeks.', stack: 'Type design, Glyphs', impact: 'Selected · Type Camp', liveUrl: '' },
      { title: 'Bloom Posters', year: '2024', category: 'Poster', image: '', desc: 'A series of 6 botanical posters exploring color and grid systems. Sold 80+ prints at the campus market.', stack: 'Poster, Illustration', impact: '80+ prints sold', liveUrl: '' },
    ]),
    skillsSectionLabel: '05 / Skills',
    skillsHeading: 'My',
    skillsHeadingEm: 'toolbox.',
    skillCategoriesJson: JSON.stringify([
      { title: 'Design tools', items: [
        { name: 'Figma', level: 5 },
        { name: 'Adobe Illustrator', level: 4 },
        { name: 'InDesign', level: 5 },
        { name: 'Photoshop', level: 4 },
        { name: 'After Effects', level: 2 },
      ]},
      { title: 'Disciplines', items: [
        { name: 'Brand identity', level: 4 },
        { name: 'Editorial design', level: 5 },
        { name: 'Typography', level: 5 },
        { name: 'Illustration', level: 3 },
        { name: 'Motion design', level: 2 },
      ]},
      { title: 'Soft skills', items: [
        { name: 'Client communication', level: 4 },
        { name: 'Presentation', level: 4 },
        { name: 'Research', level: 4 },
        { name: 'Self-direction', level: 5 },
      ]},
    ]),
    learningEyebrow: 'Currently exploring',
    learningTitle: 'Picking up new things',
    learningSub: "I'm always learning. Right now I'm focused on motion, animation, and getting better at web design fundamentals.",
    currentlyLearning: 'Motion design, After Effects, Webflow, 3D in Spline',
    wishlistSectionLabel: '06 / Looking for',
    wishlistHeading: 'My',
    wishlistHeadingEm: 'wishlist.',
    wishlistMeta: 'big dreams, real list',
    dreamRolesLabel: 'Roles I want',
    dreamRolesHeading: "Looking for my first <em>full-time</em> design role.",
    dreamRolesSub: "I'm open to junior or associate roles across brand, editorial, and product design. Open to relocation, hybrid, or remote — whichever fits the team best.",
    dreamRoles: 'Junior Visual Designer, Junior Brand Designer, Editorial Designer, Associate Designer, Design Intern (full-time)',
    dreamCompaniesLabel: 'Studios I admire',
    dreamCompaniesHeading: "Dream teams I'd <em>love</em> to work with.",
    dreamCompaniesSub: "A short list of studios and teams doing work I genuinely admire. If you're hiring — I'd love to chat.",
    dreamCompanies: 'Pentagram, Wieden+Kennedy, Mother Design, Hyperakt, Order, Studio Dumbar',
    testSectionLabel: '07 / Kind words',
    testHeading: 'What',
    testHeadingEm: 'people say.',
    testMeta: 'from mentors · classmates · clients',
    testJson: JSON.stringify([
      { quote: 'Riya is the most curious student I have taught this decade. Her work has a maturity that you rarely see at this stage.', initials: 'AM', name: 'Prof. Arun Menon', role: 'Faculty · NID Ahmedabad' },
      { quote: 'Working with Riya was a joy — she shipped fast, asked the right questions, and the final identity exceeded what I imagined.', initials: 'NV', name: 'Niharika V.', role: 'Founder, Brew Bros' },
      { quote: 'A rare combination of taste and rigour. We hired her as an intern and she left us better than we were.', initials: 'SK', name: 'Sumit Khan', role: 'Lead, Studio Lumen' },
    ]),
    contactEyebrow: "Let's chat",
    contactHeading: 'Hire me, or',
    contactHeadingEm: 'just say hi.',
    contactSub: "I'm looking for my first full-time role. If your team is hiring junior designers — or if you just want to chat about design — I'd love to hear from you.",
    contactEmail: 'hello@riya.design',
    linkedinUrl: 'https://linkedin.com/in/riyakapoor',
    linkedinHandle: '@riyakapoor',
    behanceUrl: 'https://behance.net/riyakapoor',
    behanceHandle: '@riyakapoor',
    dribbbleUrl: '',
    dribbbleHandle: '',
    instagramUrl: 'https://instagram.com/riya.designs',
    instagramHandle: '@riya.designs',
    twitterUrl: '',
    twitterHandle: '',
    colorBg: '#FAF8F4',
    colorSurface: '#FFFFFF',
    colorText: '#0F0F14',
    colorAccent: '#FF4F5E',
    colorAccent2: '#3F58FF',
    colorAccent3: '#FFC940',
    colorAccent4: '#5BD68C',
    colorAccent5: '#A964FF',
  },
};

export default debutConfig;
