import type { TemplateConfig } from '@/types';

const forgeConfig: TemplateConfig = {
  slug: 'forge',
  name: 'Forge Template',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'name', label: 'Agency Name', type: 'text', placeholder: 'Forge Studio', section: 'hero' },
        { key: 'location', label: 'Location', type: 'text', placeholder: 'Brooklyn, NY', section: 'hero' },
        { key: 'foundedYear', label: 'Founded Year', type: 'text', placeholder: '2018', section: 'hero' },
        { key: 'heroHeadline', label: 'Hero Headline', type: 'textarea', placeholder: 'We build brands that move people.', section: 'hero' },
        { key: 'tagline', label: 'Tagline', type: 'text', placeholder: 'Independent creative studio.', section: 'hero' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', placeholder: 'A multi-disciplinary practice working at the intersection of brand, product, and culture.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Booking projects for Q3', section: 'hero' },
      ],
    },
    {
      key: 'services',
      label: 'Services',
      fields: [
        { key: 'servicesJson', label: 'Services (JSON)', type: 'textarea', placeholder: '[{"number":"01","title":"Brand","description":"...","deliverables":"...","leadName":"..."}]', section: 'services' },
      ],
    },
    {
      key: 'work',
      label: 'Selected Work',
      fields: [
        { key: 'workJson', label: 'Work (JSON)', type: 'textarea', placeholder: '[{"title":"...","client":"...","year":"2024","sector":"...","services":"...","summary":"...","result":"...","image":"","liveUrl":"#"}]', section: 'work' },
      ],
    },
    {
      key: 'clients',
      label: 'Clients',
      fields: [
        { key: 'clientsJson', label: 'Clients (JSON)', type: 'textarea', placeholder: '[{"name":"Northwind","sector":"Outdoor"}]', section: 'clients' },
      ],
    },
    {
      key: 'process',
      label: 'Process',
      fields: [
        { key: 'processJson', label: 'Process (JSON)', type: 'textarea', placeholder: '[{"number":"01","title":"Discover","description":"...","duration":"2 weeks","deliverables":"..."}]', section: 'process' },
      ],
    },
    {
      key: 'team',
      label: 'Team',
      fields: [
        { key: 'teamJson', label: 'Team (JSON)', type: 'textarea', placeholder: '[{"name":"...","role":"...","bio":"...","initial":"L","linkedinUrl":"#","twitterUrl":"#"}]', section: 'team' },
      ],
    },
    {
      key: 'awards',
      label: 'Awards & Press',
      fields: [
        { key: 'awardsJson', label: 'Awards (JSON)', type: 'textarea', placeholder: '[{"name":"D&AD","work":"...","year":"2024","level":"..."}]', section: 'awards' },
        { key: 'pressJson', label: 'Press (JSON)', type: 'textarea', placeholder: '[{"outlet":"...","headline":"...","year":"2024","url":"#"}]', section: 'awards' },
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testimonialsJson', label: 'Testimonials (JSON)', type: 'textarea', placeholder: '[{"quote":"...","author":"...","role":"...","company":"..."}]', section: 'testimonials' },
      ],
    },
    {
      key: 'careers',
      label: 'Careers',
      fields: [
        { key: 'careersJson', label: 'Open Roles (JSON)', type: 'textarea', placeholder: '[{"role":"...","type":"Full-time","location":"...","url":"#"}]', section: 'careers' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactEmail', label: 'General Email', type: 'text', placeholder: 'hello@forge.studio', section: 'contact' },
        { key: 'newBizEmail', label: 'New Business Email', type: 'text', placeholder: 'newbiz@forge.studio', section: 'contact' },
        { key: 'contactPhone', label: 'Phone', type: 'text', placeholder: '+1 (212) 555-0123', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/company/forge-studio', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://x.com/forgestudio', section: 'contact' },
        { key: 'instagramUrl', label: 'Instagram URL', type: 'url', placeholder: 'https://instagram.com/forgestudio', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background (Charcoal)', type: 'color', placeholder: '#111111', section: 'theme' },
        { key: 'colorBgLight', label: 'Background Light (Bone)', type: 'color', placeholder: '#f3f0e8', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (Bone)', type: 'color', placeholder: '#f3f0e8', section: 'theme' },
        { key: 'colorFgLight', label: 'Foreground Light (Charcoal)', type: 'color', placeholder: '#111111', section: 'theme' },
        { key: 'colorAccent', label: 'Accent (Orange)', type: 'color', placeholder: '#ff5e1f', section: 'theme' },
        { key: 'colorAccentSoft', label: 'Accent Soft', type: 'color', placeholder: 'rgba(255, 94, 31, 0.14)', section: 'theme' },
        { key: 'colorLine', label: 'Line / Border', type: 'color', placeholder: 'rgba(243, 240, 232, 0.14)', section: 'theme' },
        { key: 'colorLineLight', label: 'Line / Border (Light)', type: 'color', placeholder: 'rgba(17, 17, 17, 0.14)', section: 'theme' },
        { key: 'colorCard', label: 'Card Background', type: 'color', placeholder: '#181818', section: 'theme' },
        { key: 'colorCardLight', label: 'Card Background (Light)', type: 'color', placeholder: '#ebe7dc', section: 'theme' },
        { key: 'colorMuted', label: 'Muted Foreground', type: 'color', placeholder: 'rgba(243, 240, 232, 0.62)', section: 'theme' },
        { key: 'colorMutedLight', label: 'Muted Foreground (Light)', type: 'color', placeholder: 'rgba(17, 17, 17, 0.62)', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Forge Studio',
    location: 'Brooklyn, NY',
    foundedYear: '2018',
    heroHeadline: 'We build brands that move markets.',
    tagline: 'A brand & web studio in Brooklyn.',
    subtitle: 'Forge Studio is an independent creative practice working at the intersection of brand, product, and culture. We partner with ambitious teams to ship category-defining work that earns attention and compounds value.',
    availability: 'Booking projects for Q3 2026',
    contactEmail: 'hello@forge.studio',
    newBizEmail: 'newbiz@forge.studio',
    contactPhone: '+1 (212) 555-0184',
    linkedinUrl: 'https://linkedin.com/company/forge-studio',
    twitterUrl: 'https://x.com/forgestudio',
    instagramUrl: 'https://instagram.com/forgestudio',
    servicesJson: JSON.stringify([
      { number: '01', title: 'Brand Identity', description: 'Names, marks, systems, and the strategy that holds them together. We build identity systems flexible enough to live across every surface for the next decade.', deliverables: 'Naming, Logo, Type System, Color, Guidelines', leadName: 'Lena Park' },
      { number: '02', title: 'Digital Product', description: 'End-to-end product design from research to release. Native apps, dashboards, and tools that feel inevitable to the people who use them every day.', deliverables: 'UX, UI, Design Systems, Prototypes', leadName: 'Marcus Reid' },
      { number: '03', title: 'Web & Interactive', description: 'Marketing sites, e-commerce, and bespoke web experiences engineered for speed, accessibility, and conversion at scale.', deliverables: 'Strategy, Design, Build, CMS', leadName: 'Iris Tanaka' },
      { number: '04', title: 'Motion & Film', description: 'Brand films, product motion, and identity in motion. We treat the moving image as a first-class brand surface — not a nice-to-have.', deliverables: 'Direction, Animation, Edit, Sound', leadName: 'Sam Okafor' },
      { number: '05', title: 'Strategy', description: 'Positioning, narrative, and go-to-market planning. The thinking that makes the work do more than look good — it makes it work harder.', deliverables: 'Research, Positioning, Naming, Narrative', leadName: 'Devin Halle' },
      { number: '06', title: 'Campaigns', description: 'Integrated campaign work spanning film, OOH, social, and experiential. Built to be felt, not just seen.', deliverables: 'Concept, Production, Rollout, Measurement', leadName: 'Ana Vidal' },
    ]),
    workJson: JSON.stringify([
      { title: 'Northwind Outfitters', client: 'Northwind', year: '2024', sector: 'Outdoor / Retail', services: 'Brand, Web, Campaign', summary: 'A full rebrand and direct-to-consumer relaunch for a 40-year-old outdoor goods company entering a new generation of customer.', result: '+218% e-commerce revenue in six months', image: '', liveUrl: '#' },
      { title: 'Halcyon Sleep', client: 'Halcyon', year: '2024', sector: 'Consumer Health', services: 'Identity, Packaging, Product', summary: 'Identity and product design for a sleep wellness brand that wanted to feel less like pharma and more like a nightly ritual.', result: 'Sold out of launch run in 11 days', image: '', liveUrl: '#' },
      { title: 'Field Notes Quarterly', client: 'Field Notes', year: '2023', sector: 'Publishing', services: 'Editorial, Web, Print', summary: 'A complete redesign of the quarterly print publication and its digital companion. Built around a new editorial voice and a more confident grid.', result: '3.4x increase in paid subscriptions', image: '', liveUrl: '#' },
      { title: 'Mercer Tools', client: 'Mercer', year: '2023', sector: 'B2B SaaS', services: 'Brand, Product, Web', summary: 'Repositioning a developer tooling company from open-source side project to enterprise platform — without losing the engineers who built it.', result: 'Series B closed at $80M', image: '', liveUrl: '#' },
      { title: 'Loam Coffee', client: 'Loam', year: '2022', sector: 'F&B / Hospitality', services: 'Identity, Packaging, Spatial', summary: 'Brand and spatial identity for a third-wave coffee operator opening three locations across the boroughs.', result: 'James Beard Best New Restaurant semifinalist', image: '', liveUrl: '#' },
      { title: 'Polaris Civic', client: 'City of Pittsburgh', year: '2022', sector: 'Government / Civic', services: 'Strategy, Brand, Product', summary: 'A digital service design engagement reshaping how residents access twenty-three city services through a single front door.', result: '62% reduction in support volume', image: '', liveUrl: '#' },
    ]),
    clientsJson: JSON.stringify([
      { name: 'Northwind', sector: 'Outdoor' },
      { name: 'Halcyon', sector: 'Wellness' },
      { name: 'Mercer', sector: 'SaaS' },
      { name: 'Field Notes', sector: 'Publishing' },
      { name: 'Loam', sector: 'F&B' },
      { name: 'Polaris', sector: 'Civic' },
      { name: 'Atlas Bank', sector: 'Fintech' },
      { name: 'Westgate', sector: 'Real Estate' },
      { name: 'Kindred', sector: 'Healthcare' },
      { name: 'Bluebird Air', sector: 'Travel' },
      { name: 'Otto Studios', sector: 'Entertainment' },
      { name: 'Cardinal', sector: 'Logistics' },
      { name: 'Marlow & Co.', sector: 'Apparel' },
      { name: 'Helix Foods', sector: 'CPG' },
    ]),
    processJson: JSON.stringify([
      { number: '01', title: 'Discover', description: 'We start by listening. Stakeholder interviews, audits, audience research, and competitive landscaping. The output is a sharper brief than the one we walked in with.', duration: '2 — 3 weeks', deliverables: 'Research, Audit, Strategy Brief' },
      { number: '02', title: 'Define', description: 'We translate research into direction. Positioning, narrative, and the strategic posture the work will be built on. Nothing moves into design until this is sharp.', duration: '2 weeks', deliverables: 'Positioning, Narrative, Principles' },
      { number: '03', title: 'Design', description: 'Concepts, iterations, and the long, slow work of getting the details right. Two to three directions reduced to one, then refined until it is the obvious answer.', duration: '4 — 8 weeks', deliverables: 'Concepts, Systems, Guidelines' },
      { number: '04', title: 'Build', description: 'Production, engineering, and rollout. We work in tight loops with your team so the handoff is not a handoff. We stay involved until it ships.', duration: '4 — 12 weeks', deliverables: 'Production, Code, Assets, Launch' },
      { number: '05', title: 'Evolve', description: 'We do not believe in launch-and-leave. We stay on retainer with most partners, evolving the system as the business grows and learns.', duration: 'Ongoing', deliverables: 'Retainer, Optimization, Expansion' },
    ]),
    teamJson: JSON.stringify([
      { name: 'Lena Park', role: 'Founder & Executive Creative Director', bio: 'Previously design director at Pentagram and Instrument. AIGA Medal recipient. Lena leads brand identity engagements and oversees creative direction across the studio.', initial: 'L', linkedinUrl: 'https://linkedin.com/in/lenapark', twitterUrl: 'https://x.com/lenapark' },
      { name: 'Marcus Reid', role: 'Partner, Head of Product', bio: 'Fifteen years designing software at Stripe, Linear, and as a solo practitioner. Marcus leads our product practice and writes our point of view on the craft.', initial: 'M', linkedinUrl: 'https://linkedin.com/in/marcusreid', twitterUrl: 'https://x.com/marcusreid' },
      { name: 'Iris Tanaka', role: 'Design Director, Web', bio: 'Iris leads web and interactive engagements. Formerly at Active Theory and Resn. Two-time FWA Site of the Year and a regular speaker at Config.', initial: 'I', linkedinUrl: 'https://linkedin.com/in/iristanaka', twitterUrl: 'https://x.com/iristanaka' },
      { name: 'Sam Okafor', role: 'Director of Motion', bio: 'Director and animator with a background in commercial film. Sam leads our motion practice and our in-house edit suite, and has shipped work for Nike, Apple, and the Met.', initial: 'S', linkedinUrl: 'https://linkedin.com/in/samokafor', twitterUrl: 'https://x.com/samokafor' },
      { name: 'Devin Halle', role: 'Head of Strategy', bio: 'Former planner at Wieden+Kennedy and a small handful of independents. Devin runs strategy across the studio and writes most of our case studies.', initial: 'D', linkedinUrl: 'https://linkedin.com/in/devinhalle', twitterUrl: 'https://x.com/devinhalle' },
      { name: 'Ana Vidal', role: 'Director of Campaigns', bio: 'Ana leads integrated campaign work, from concept through production. Previously at Mother and Droga5, with a Cannes Grand Prix on the shelf.', initial: 'A', linkedinUrl: 'https://linkedin.com/in/anavidal', twitterUrl: 'https://x.com/anavidal' },
    ]),
    awardsJson: JSON.stringify([
      { name: 'D&AD Wood Pencil', work: 'Northwind Outfitters', year: '2024', level: 'Brand Identity' },
      { name: 'Brand New — Notable', work: 'Halcyon Sleep', year: '2024', level: 'Identity Work' },
      { name: 'Webby Award', work: 'Mercer Tools', year: '2023', level: 'Best B2B Website' },
      { name: 'Type Directors Club', work: 'Field Notes Quarterly', year: '2023', level: 'Editorial Design' },
      { name: 'Awwwards SOTY', work: 'Loam Coffee', year: '2022', level: 'Site of the Year, Honorable' },
      { name: 'Communication Arts', work: 'Polaris Civic', year: '2022', level: 'Interactive Annual' },
    ]),
    pressJson: JSON.stringify([
      { outlet: 'It’s Nice That', headline: 'Inside Forge Studio’s rebrand of Northwind', year: '2024', url: '#' },
      { outlet: 'Brand New', headline: 'New logo and identity for Halcyon Sleep', year: '2024', url: '#' },
      { outlet: 'Fast Company', headline: 'How a Brooklyn studio is rebuilding civic digital design', year: '2023', url: '#' },
      { outlet: 'Eye on Design', headline: 'A conversation with Lena Park', year: '2023', url: '#' },
      { outlet: 'The Drum', headline: 'Forge Studio named Independent Studio of the Year shortlist', year: '2022', url: '#' },
    ]),
    testimonialsJson: JSON.stringify([
      { quote: 'Forge did not just rebrand us. They rebuilt the way we think about ourselves. The work shipped on time, on budget, and reset the trajectory of the company.', author: 'Rachel Yoon', role: 'CEO', company: 'Northwind Outfitters' },
      { quote: 'They are the rare studio that holds the strategic line as fiercely as the craft line. Six months in and the work is still teaching our team how to operate.', author: 'David Friedman', role: 'Chief Marketing Officer', company: 'Mercer Tools' },
      { quote: 'Working with Forge feels like adding a senior creative team to your roster. They show up, they push back, and they ship work that wins awards and revenue.', author: 'Priya Chandra', role: 'Founder', company: 'Halcyon Sleep' },
    ]),
    careersJson: JSON.stringify([
      { role: 'Senior Brand Designer', type: 'Full-time', location: 'Brooklyn / Hybrid', url: '#' },
      { role: 'Product Designer', type: 'Full-time', location: 'Remote (US)', url: '#' },
      { role: 'Motion Designer', type: 'Contract', location: 'Brooklyn / On-site', url: '#' },
      { role: 'Strategy Director', type: 'Full-time', location: 'Brooklyn / Hybrid', url: '#' },
    ]),
    colorBg: '#111111',
    colorBgLight: '#f3f0e8',
    colorFg: '#f3f0e8',
    colorFgLight: '#111111',
    colorAccent: '#ff5e1f',
    colorAccentSoft: 'rgba(255, 94, 31, 0.14)',
    colorLine: 'rgba(243, 240, 232, 0.14)',
    colorLineLight: 'rgba(17, 17, 17, 0.14)',
    colorCard: '#181818',
    colorCardLight: '#ebe7dc',
    colorMuted: 'rgba(243, 240, 232, 0.62)',
    colorMutedLight: 'rgba(17, 17, 17, 0.62)',
  },
};

export default forgeConfig;
