import type { TemplateConfig } from '@/types';

const helixConfig: TemplateConfig = {
  slug: 'helix',
  name: 'Helix Template',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Helix Vega', section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Software Engineer', section: 'hero' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', placeholder: 'building thoughtful interfaces and resilient systems with an obsession for typography, performance, and the small details that compound.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'available for work', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'yearsExp', label: 'Years of Experience', type: 'text', placeholder: '6+', section: 'hero' },
        { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'UTC+1', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutP1', label: 'About — Paragraph 1', type: 'textarea', placeholder: "I'm Helix, a software engineer who treats software as a craft.", section: 'about' },
        { key: 'aboutP2', label: 'About — Paragraph 2', type: 'textarea', placeholder: 'Currently focused on developer tooling, performance, and the messy reality of distributed systems.', section: 'about' },
        { key: 'locationLabel', label: 'Location Label', type: 'text', placeholder: 'Lisbon, PT', section: 'about' },
      ],
    },
    {
      key: 'skills',
      label: 'Skills',
      fields: [
        { key: 'skillLang', label: 'Languages (fallback)', type: 'text', placeholder: 'TypeScript, Go, Python, Rust, SQL', section: 'skills' },
        { key: 'skillFramework', label: 'Frameworks (fallback)', type: 'text', placeholder: 'React, Next.js, Remix, Svelte', section: 'skills' },
        { key: 'skillBackend', label: 'Backend (fallback)', type: 'text', placeholder: 'Node.js, PostgreSQL, Redis, gRPC', section: 'skills' },
        { key: 'skillTooling', label: 'Tooling (fallback)', type: 'text', placeholder: 'Vite, Turborepo, Vitest, Playwright', section: 'skills' },
        { key: 'skillPlatform', label: 'Platform (fallback)', type: 'text', placeholder: 'Docker, Kubernetes, AWS, Vercel', section: 'skills' },
      ],
    },
    {
      key: 'experience',
      label: 'Experience',
      fields: [],
    },
    {
      key: 'projects',
      label: 'Projects',
      fields: [],
    },
    {
      key: 'education',
      label: 'Education & Certifications',
      fields: [],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'hello@example.com', section: 'contact' },
        { key: 'contactPhone', label: 'Phone', type: 'text', placeholder: '+00 0000 0000', section: 'contact' },
        { key: 'contactLocation', label: 'Location', type: 'text', placeholder: 'Lisbon, PT', section: 'contact' },
        { key: 'githubUrl', label: 'GitHub URL', type: 'url', placeholder: 'https://github.com/username', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/username', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://twitter.com/username', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: '#0a0a0a', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (primary text)', type: 'color', placeholder: '#f5f5f0', section: 'theme' },
        { key: 'colorPanel', label: 'Panel Background', type: 'color', placeholder: '#f5f5f0', section: 'theme' },
        { key: 'colorPanelFg', label: 'Panel Foreground', type: 'color', placeholder: '#0a0a0a', section: 'theme' },
        { key: 'colorAccent', label: 'Accent Color', type: 'color', placeholder: '#9eff00', section: 'theme' },
        { key: 'colorLine', label: 'Border / Line', type: 'color', placeholder: '#1f1f1f', section: 'theme' },
        { key: 'colorLineStrong', label: 'Border Strong', type: 'color', placeholder: '#2a2a2a', section: 'theme' },
        { key: 'colorMuted', label: 'Muted Text', type: 'color', placeholder: '#7a7a72', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Helix Vega',
    title: 'Software Engineer',
    subtitle: 'building thoughtful interfaces and resilient systems with an obsession for typography, performance, and the small details that compound.',
    availability: 'available for work',
    resumeUrl: '',
    yearsExp: '6+',
    timezone: 'UTC+1',
    heroStats: JSON.stringify([
      { label: 'YEARS', value: '6+' },
      { label: 'SHIPPED', value: '40+' },
      { label: 'STACK', value: 'TS/GO' },
      { label: 'TZ', value: 'UTC+1' },
    ]),
    aboutP1: "I'm Helix Vega, a software engineer who treats software as a craft. I care about the substrate — the wiring beneath features — and the surface — the experience of using them.",
    aboutP2: 'Currently focused on developer tooling, performance, and the messy reality of distributed systems. Previously: design systems, infra, and a handful of zero-to-one products.',
    locationLabel: 'Lisbon, PT',
    skillLang: 'TypeScript, Go, Python, Rust, SQL',
    skillFramework: 'React, Next.js, Remix, Svelte',
    skillBackend: 'Node.js, PostgreSQL, Redis, gRPC',
    skillTooling: 'Vite, Turborepo, Vitest, Playwright',
    skillPlatform: 'Docker, Kubernetes, AWS, Vercel',
    skillsJson: JSON.stringify([
      { category: 'LANGUAGES', items: 'TypeScript, Go, Python, Rust, SQL' },
      { category: 'FRAMEWORKS', items: 'React, Next.js, Remix, Svelte, Tailwind' },
      { category: 'BACKEND', items: 'Node.js, PostgreSQL, Redis, gRPC, Kafka' },
      { category: 'TOOLING', items: 'Vite, Turborepo, Vitest, Playwright, Storybook' },
      { category: 'PLATFORM', items: 'Docker, Kubernetes, AWS, Vercel, Cloudflare' },
    ]),
    expJson: JSON.stringify([
      {
        period: '2023 — NOW',
        duration: '2 yrs',
        role: 'Senior Software Engineer',
        company: 'Acme Labs',
        summary: 'Leading platform engineering for a distributed data product used by 200+ teams.',
        bullets: 'Architected a multi-tenant ingestion pipeline processing 4B events/day.\nCut p99 query latency from 800ms to 90ms via query planning + caching.\nMentored 6 engineers; ran the internal frontend guild.\nDrove the migration from a monolith to a service-oriented edge runtime.',
        stack: 'TypeScript, Go, Postgres, Kafka, Kubernetes',
        isCurrent: true,
      },
      {
        period: '2020 — 2023',
        duration: '3 yrs',
        role: 'Software Engineer',
        company: 'Northwind',
        summary: 'Full-stack engineer on the growth team, shipping experiments and core product.',
        bullets: 'Owned the onboarding flow that doubled W1 activation.\nBuilt the in-house A/B framework still used company-wide.\nShipped 20+ production experiments at a weekly cadence.',
        stack: 'React, Next.js, Node, Redis',
        isCurrent: false,
      },
      {
        period: '2018 — 2020',
        duration: '2 yrs',
        role: 'Junior Engineer',
        company: 'Halcyon Studio',
        summary: 'Built marketing sites and product surfaces for early-stage clients.',
        bullets: 'Delivered 12 production sites with perfect Lighthouse scores.\nWrote the studio playbook for accessibility and motion.',
        stack: 'TypeScript, React, GSAP, Webflow',
        isCurrent: false,
      },
    ]),
    projJson: JSON.stringify([
      {
        title: 'Lattice',
        tag: 'OSS / DEVTOOL',
        desc: 'A zero-config edge analytics SDK with type-safe events and SQL-style aggregation. Designed for product teams who want to own their event pipeline.',
        stack: 'TypeScript, Cloudflare, DuckDB',
        liveUrl: 'https://example.com/lattice',
        githubUrl: 'https://github.com/example/lattice',
      },
      {
        title: 'Beacon',
        tag: 'PRODUCT',
        desc: 'Realtime infrastructure observability for distributed systems at scale. Streaming traces, structured logs, and alerts in a single pane.',
        stack: 'Go, ClickHouse, React',
        liveUrl: 'https://example.com/beacon',
        githubUrl: '',
      },
      {
        title: 'Folio',
        tag: 'CLIENT WORK',
        desc: 'Editorial-grade publishing platform for independent writers — bring your own domain, your own typography, your own rules.',
        stack: 'Next.js, Postgres, Stripe',
        liveUrl: 'https://example.com/folio',
        githubUrl: '',
      },
      {
        title: 'Halt',
        tag: 'OSS / CLI',
        desc: 'A frighteningly fast CLI for managing local dev environments and per-project secrets. Drop-in replacement for direnv.',
        stack: 'Rust, TOML',
        liveUrl: '',
        githubUrl: 'https://github.com/example/halt',
      },
    ]),
    educationJson: JSON.stringify([
      {
        school: 'University of Coimbra',
        degree: 'B.Sc. Computer Science',
        period: '2014 — 2018',
        detail: 'Focus on distributed systems and programming languages. Graduated with honors. Thesis on incremental compilation in typed languages.',
      },
      {
        school: 'Recurse Center',
        degree: 'Self-directed Programming Retreat',
        period: '2019',
        detail: 'Twelve weeks of deep work on compilers, type systems, and low-level Rust. Built a hobby database engine from scratch.',
      },
    ]),
    certsJson: JSON.stringify([
      { name: 'Certified Kubernetes Administrator', issuer: 'CNCF', year: '2023', url: '' },
      { name: 'AWS Solutions Architect — Associate', issuer: 'Amazon Web Services', year: '2022', url: '' },
      { name: 'HashiCorp Certified: Terraform Associate', issuer: 'HashiCorp', year: '2022', url: '' },
      { name: 'Google Professional Cloud Architect', issuer: 'Google Cloud', year: '2021', url: '' },
    ]),
    contactEmail: 'hello@helixvega.dev',
    contactPhone: '+351 900 000 000',
    contactLocation: 'Lisbon, PT',
    githubUrl: 'https://github.com/helixvega',
    linkedinUrl: 'https://linkedin.com/in/helixvega',
    twitterUrl: 'https://twitter.com/helixvega',
    colorBg: '#0a0a0a',
    colorFg: '#f5f5f0',
    colorPanel: '#f5f5f0',
    colorPanelFg: '#0a0a0a',
    colorAccent: '#9eff00',
    colorLine: '#1f1f1f',
    colorLineStrong: '#2a2a2a',
    colorMuted: '#7a7a72',
  },
};

export default helixConfig;
