import type { TemplateConfig } from '@/types';

const lumenConfig: TemplateConfig = {
  slug: 'lumen',
  name: 'Lumen Template',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Lumen Vasquez', section: 'hero' },
        { key: 'handle', label: 'Primary Handle', type: 'text', placeholder: '@lumenvasquez', section: 'hero' },
        { key: 'tagline', label: 'Tagline', type: 'text', placeholder: 'Tech & creator-economy storyteller', section: 'hero' },
        { key: 'subtitle', label: 'Subtitle / Bio', type: 'textarea', placeholder: 'Breaking down the platforms, products, and people powering the modern creator economy.', section: 'hero' },
        { key: 'niches', label: 'Niches (comma separated)', type: 'text', placeholder: 'Tech, Creator Economy, Productivity', section: 'hero' },
        { key: 'avatarUrl', label: 'Avatar / Headshot', type: 'image', placeholder: '', section: 'hero' },
      ],
    },
    {
      key: 'platforms',
      label: 'Platforms',
      fields: [
        { key: 'youtubeUrl', label: 'YouTube URL', type: 'url', placeholder: 'https://youtube.com/@lumenvasquez', section: 'platforms' },
        { key: 'tiktokUrl', label: 'TikTok URL', type: 'url', placeholder: 'https://tiktok.com/@lumenvasquez', section: 'platforms' },
        { key: 'instagramUrl', label: 'Instagram URL', type: 'url', placeholder: 'https://instagram.com/lumenvasquez', section: 'platforms' },
        { key: 'twitterUrl', label: 'X / Twitter URL', type: 'url', placeholder: 'https://x.com/lumenvasquez', section: 'platforms' },
        { key: 'twitchUrl', label: 'Twitch URL', type: 'url', placeholder: 'https://twitch.tv/lumenvasquez', section: 'platforms' },
        { key: 'spotifyUrl', label: 'Spotify / Podcast URL', type: 'url', placeholder: 'https://open.spotify.com/show/...', section: 'platforms' },
      ],
    },
    {
      key: 'featured',
      label: 'Featured Content',
      fields: [
        { key: 'totalContent', label: 'Total Content Published', type: 'text', placeholder: '480+', section: 'featured' },
      ],
    },
    {
      key: 'niches',
      label: 'Niches',
      fields: [],
    },
    {
      key: 'brands',
      label: 'Brands & Partners',
      fields: [],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutP1', label: 'About — Paragraph 1', type: 'textarea', placeholder: 'I started filming with a borrowed phone in 2019…', section: 'about' },
        { key: 'aboutP2', label: 'About — Paragraph 2', type: 'textarea', placeholder: 'Today I publish 4x a week across YouTube, TikTok, and the newsletter…', section: 'about' },
        { key: 'yearsCreating', label: 'Years Creating', type: 'text', placeholder: '6', section: 'about' },
        { key: 'cadence', label: 'Publishing Cadence', type: 'text', placeholder: '4x / week', section: 'about' },
      ],
    },
    {
      key: 'press',
      label: 'Press & Media',
      fields: [],
    },
    {
      key: 'services',
      label: 'Services & Rates',
      fields: [],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactEmail', label: 'Contact Email', type: 'text', placeholder: 'hi@lumenvasquez.com', section: 'contact' },
        { key: 'managerEmail', label: 'Manager / Agent Email', type: 'text', placeholder: 'bookings@brightside.co', section: 'contact' },
        { key: 'calendarUrl', label: 'Booking Calendar URL', type: 'url', placeholder: 'https://cal.com/lumenvasquez/intro', section: 'contact' },
        { key: 'mediaKitUrl', label: 'Media Kit URL', type: 'url', placeholder: 'https://lumenvasquez.com/media-kit.pdf', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background (deep purple)', type: 'color', placeholder: 'oklch(0.14 0.05 300)', section: 'theme' },
        { key: 'colorCard', label: 'Card Background', type: 'color', placeholder: 'oklch(0.2 0.06 300)', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (text)', type: 'color', placeholder: 'oklch(0.98 0.01 300)', section: 'theme' },
        { key: 'colorLine', label: 'Border / Line', type: 'color', placeholder: 'oklch(0.3 0.05 300)', section: 'theme' },
        { key: 'colorAccent', label: 'Accent — Pink', type: 'color', placeholder: 'oklch(0.72 0.25 350)', section: 'theme' },
        { key: 'colorAccent2', label: 'Accent — Purple', type: 'color', placeholder: 'oklch(0.65 0.27 295)', section: 'theme' },
        { key: 'colorAccent3', label: 'Accent — Cyan', type: 'color', placeholder: 'oklch(0.82 0.18 200)', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Lumen Vasquez',
    handle: '@lumenvasquez',
    tagline: 'Tech & creator-economy storyteller',
    subtitle: "Breaking down the platforms, products, and people powering the modern creator economy — with a little chaos and a lot of color.",
    niches: 'Tech, Creator Economy, Productivity, Streaming Culture',
    avatarUrl: '',
    youtubeUrl: 'https://youtube.com/@lumenvasquez',
    tiktokUrl: 'https://tiktok.com/@lumenvasquez',
    instagramUrl: 'https://instagram.com/lumenvasquez',
    twitterUrl: 'https://x.com/lumenvasquez',
    twitchUrl: 'https://twitch.tv/lumenvasquez',
    spotifyUrl: 'https://open.spotify.com/show/lumen-after-hours',
    aboutP1: "I started filming with a borrowed phone in my dorm in 2019 — three minute rants about why creator-economy tools were quietly broken. Six years and a few algorithm shifts later, that rant became a full-time studio: a YouTube channel, a Tuesday newsletter, a podcast that actually pays for itself, and a whole lot of opinions about monetization.",
    aboutP2: "Today I publish 4x a week across YouTube, TikTok, and Lumen After Hours — covering the apps, founders, and weird little pivots shaping how creators get paid. I've worked with brands from Notion to Riverside, but the work I'm proudest of is the long-form: deep dives that take three weeks to research and a lifetime of internet brain to write.",
    yearsCreating: '6',
    cadence: '4x / week',
    totalContent: '480+',
    contactEmail: 'hi@lumenvasquez.com',
    managerEmail: 'bookings@brightside.co',
    calendarUrl: 'https://cal.com/lumenvasquez/intro',
    mediaKitUrl: 'https://lumenvasquez.com/media-kit.pdf',
    platformsJson: JSON.stringify([
      { platform: 'YouTube', handle: '@lumenvasquez', followers: '842K', url: 'https://youtube.com/@lumenvasquez', color: '#FF0033' },
      { platform: 'TikTok', handle: '@lumenvasquez', followers: '1.4M', url: 'https://tiktok.com/@lumenvasquez', color: '#25F4EE' },
      { platform: 'Instagram', handle: '@lumenvasquez', followers: '312K', url: 'https://instagram.com/lumenvasquez', color: '#E1306C' },
      { platform: 'X / Twitter', handle: '@lumenvasquez', followers: '188K', url: 'https://x.com/lumenvasquez', color: '#FFFFFF' },
      { platform: 'Twitch', handle: 'lumenvasquez', followers: '54K', url: 'https://twitch.tv/lumenvasquez', color: '#9146FF' },
      { platform: 'Spotify', handle: 'Lumen After Hours', followers: '96K', url: 'https://open.spotify.com/show/lumen-after-hours', color: '#1DB954' },
    ]),
    featuredJson: JSON.stringify([
      { title: "I Spent $10K Testing Every Creator Monetization Tool So You Don't Have To", platform: 'YouTube', thumbnail: '', views: '2.1M', duration: '18:42', type: 'long', url: 'https://youtube.com/watch?v=lumen-monetize', year: '2026' },
      { title: 'Why MrBeast Quietly Bought a Pencil Factory (and what it means)', platform: 'YouTube', thumbnail: '', views: '1.6M', duration: '12:08', type: 'long', url: 'https://youtube.com/watch?v=lumen-mrbeast', year: '2026' },
      { title: 'POV: your podcast host just discovered AI clip tools', platform: 'TikTok', thumbnail: '', views: '4.8M', duration: '0:47', type: 'short', url: 'https://tiktok.com/@lumenvasquez/video/clip-tools', year: '2026' },
      { title: 'The Substack-to-YouTube Pipeline is Real', platform: 'YouTube', thumbnail: '', views: '912K', duration: '14:31', type: 'long', url: 'https://youtube.com/watch?v=lumen-substack', year: '2025' },
      { title: 'creator economy crash course in 60 seconds', platform: 'Instagram', thumbnail: '', views: '2.3M', duration: '0:59', type: 'reel', url: 'https://instagram.com/reel/lumen-crash-course', year: '2026' },
      { title: 'Lumen After Hours · Ep. 41: Talking with the founder of Beehiiv', platform: 'Spotify', thumbnail: '', views: '88K', duration: '54:12', type: 'podcast', url: 'https://open.spotify.com/episode/lumen-beehiiv', year: '2026' },
      { title: 'I tried being a TikTok Shop affiliate for 30 days', platform: 'TikTok', thumbnail: '', views: '3.1M', duration: '1:24', type: 'short', url: 'https://tiktok.com/@lumenvasquez/video/tiktok-shop', year: '2025' },
      { title: 'Behind the desk: my actual creator stack in 2026', platform: 'YouTube', thumbnail: '', views: '740K', duration: '9:55', type: 'long', url: 'https://youtube.com/watch?v=lumen-stack', year: '2026' },
      { title: 'studio reset → studio chaos in 8 seconds', platform: 'Instagram', thumbnail: '', views: '1.2M', duration: '0:08', type: 'reel', url: 'https://instagram.com/reel/lumen-studio', year: '2026' },
    ]),
    nichesJson: JSON.stringify([
      { name: 'Creator Economy', icon: '💸' },
      { name: 'Tech & Tools', icon: '🛠️' },
      { name: 'Productivity', icon: '⚡' },
      { name: 'Streaming Culture', icon: '📺' },
      { name: 'Founder Stories', icon: '🚀' },
      { name: 'Podcasting', icon: '🎙️' },
      { name: 'Newsletters', icon: '📬' },
      { name: 'AI & Workflow', icon: '🤖' },
    ]),
    brandsJson: JSON.stringify([
      { name: 'Notion', year: '2026', type: 'Integrated Sponsor' },
      { name: 'Riverside.fm', year: '2026', type: 'Long-term Partner' },
      { name: 'Beehiiv', year: '2026', type: 'Brand Deal' },
      { name: 'Descript', year: '2025', type: 'Integrated Sponsor' },
      { name: 'Linear', year: '2025', type: 'Brand Deal' },
      { name: 'Squarespace', year: '2025', type: 'Sponsored Series' },
      { name: 'Opal', year: '2024', type: 'Gifted + Paid' },
      { name: 'Logitech', year: '2024', type: 'Hardware Partner' },
      { name: 'Audible', year: '2024', type: 'Read Sponsor' },
      { name: 'Squarespace', year: '2023', type: 'Pre-roll Partner' },
    ]),
    campaignsJson: JSON.stringify([
      { brand: 'Notion', title: 'Run Your Creator Business in One Workspace', summary: 'A three-part YouTube + Shorts series walking through the actual Notion stack I use to plan, script, and ship 4 videos a week — landing 2.4M combined views and a 6.1% CTR to a co-branded template.', deliverables: '2 long-form videos · 4 Shorts · 1 Tuesday newsletter takeover', year: '2026', image: '' },
      { brand: 'Riverside.fm', title: 'Lumen After Hours — Year One on Riverside', summary: 'Year-long podcast integration with Riverside as the production backbone. Custom intro, in-episode demos, and a dedicated YouTube deep-dive on remote recording workflows.', deliverables: '12 podcast episodes · 1 dedicated YouTube · 6 Reels', year: '2026', image: '' },
      { brand: 'Beehiiv', title: 'Newsletter Economy 101', summary: "A 14-minute YouTube essay on why every creator should run a newsletter, with Beehiiv as the practical case study. Drove 3,800 signups in week one and got name-checked in Beehiiv's own keynote.", deliverables: '1 long-form video · 3 TikToks · 1 newsletter swap', year: '2026', image: '' },
      { brand: 'Descript', title: 'Edit Like a Maniac, Look Like a Pro', summary: "Two-month 'creator stack' series featuring Descript's underbidding rooms feature. Tutorials performed 38% above channel average and converted at 4.2% to trial.", deliverables: '2 tutorials · 5 Shorts · 1 livestream', year: '2025', image: '' },
      { brand: 'Linear', title: 'Run Your Studio Like a Software Team', summary: "A genre-bending video — half studio tour, half ops manual — pitching Linear as the project tool for creator teams. Spawned a follow-up community template still in use.", deliverables: '1 long-form video · 1 LinkedIn essay · 2 Reels', year: '2025', image: '' },
    ]),
    pressJson: JSON.stringify([
      { outlet: 'The Verge', headline: 'Lumen Vasquez Is the Creator Other Creators Can\'t Stop Watching', year: '2026', url: 'https://theverge.com/lumen-vasquez-profile' },
      { outlet: 'Fast Company', headline: 'How a 24-Year-Old Built a Million-Dollar Studio Out of a Brooklyn Walk-Up', year: '2026', url: 'https://fastcompany.com/lumen-studio' },
      { outlet: 'Forbes 30 Under 30', headline: 'Media — 2026 Honoree', year: '2026', url: 'https://forbes.com/30under30/media/lumen-vasquez' },
      { outlet: 'Colin and Samir', headline: 'Lumen Vasquez on Quietly Becoming the Industry\'s Favorite Explainer', year: '2025', url: 'https://colinandsamir.com/lumen-interview' },
      { outlet: 'Morning Brew', headline: 'The Creator Economy Has a New Tour Guide — and She Has Receipts', year: '2025', url: 'https://morningbrew.com/lumen-vasquez' },
    ]),
    servicesJson: JSON.stringify([
      { title: 'Integrated YouTube Sponsorship', description: 'A natively woven 60–90 second mid-roll inside a long-form video, scripted by me, approved by you. Performance reporting included.', deliverables: '1 mid-roll integration · script approval · 14-day perf report', startingPrice: 'from $18,000' },
      { title: 'Dedicated Video Partnership', description: 'A full long-form video built around your product or story. Co-developed concept, full production, and aligned launch with social cutdowns.', deliverables: '1 long-form video · 3 Shorts · 1 newsletter mention', startingPrice: 'from $42,000' },
      { title: 'Short-Form Campaign Bundle', description: 'A 30-day burst of TikToks and Reels riffing on your product in my voice. Great for launches, app updates, or seasonal pushes.', deliverables: '4 TikToks · 4 Reels · usage rights 30 days', startingPrice: 'from $14,000' },
      { title: 'Podcast Host-Read + Episode Slot', description: 'A host-read sponsor slot on Lumen After Hours, optionally upgraded to a guest spot for a founder or product lead.', deliverables: '60s host-read · optional 40-min guest episode', startingPrice: 'from $6,500' },
      { title: 'Custom Creator Consulting', description: 'For brands and platforms: a working session (or retainer) helping you talk to creators like a creator. No fluff, no decks longer than they need to be.', deliverables: '90-min strategy call · written follow-up · optional retainer', startingPrice: 'from $2,500' },
    ]),
    testimonialsJson: JSON.stringify([
      { quote: "Lumen didn't just hit our numbers — she rewired how our team talks about creators internally. The integration outperformed our paid media for the quarter.", author: 'Priya Anand', role: 'Head of Creator Marketing', brand: 'Notion' },
      { quote: 'Working with Lumen feels like hiring a senior strategist who also happens to ship the assets. Rare combo. We re-upped before the first deal even wrapped.', author: 'Marcus Chen', role: 'VP Brand', brand: 'Riverside.fm' },
      { quote: "She gets the assignment and then quietly does something better than the assignment. Our signups from her video are still trickling in eight months later.", author: 'Tyler Denk', role: 'Co-founder & CEO', brand: 'Beehiiv' },
      { quote: 'Lumen is one of maybe five creators on the internet who can sell software to other creators without sounding like an ad. Easy renewal.', author: 'Sofia Reyes', role: 'Director of Partnerships', brand: 'Descript' },
    ]),
    colorBg: 'oklch(0.14 0.05 300)',
    colorCard: 'oklch(0.2 0.06 300)',
    colorFg: 'oklch(0.98 0.01 300)',
    colorLine: 'oklch(0.3 0.05 300)',
    colorAccent: 'oklch(0.72 0.25 350)',
    colorAccent2: 'oklch(0.65 0.27 295)',
    colorAccent3: 'oklch(0.82 0.18 200)',
  },
};

export default lumenConfig;
