import type { TemplateConfig } from '@/types';

const marenConfig: TemplateConfig = {
  slug: 'maren',
  name: 'Maren Template',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Maren Holloway', section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Software Engineer', section: 'hero' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', placeholder: 'Building thoughtful interfaces for products people return to.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Available Q3 2026', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '2', section: 'hero' },
        { key: 'stat1Unit', label: 'Stat 1 — Unit', type: 'text', placeholder: 'yrs', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Shipping in production', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '14', section: 'hero' },
        { key: 'stat2Unit', label: 'Stat 2 — Unit', type: 'text', placeholder: '+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Features delivered', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '38', section: 'hero' },
        { key: 'stat3Unit', label: 'Stat 3 — Unit', type: 'text', placeholder: '%', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Avg. perf gains landed', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '6', section: 'hero' },
        { key: 'stat4Unit', label: 'Stat 4 — Unit', type: 'text', placeholder: '', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'OSS contributions', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutSectionLabel', label: 'Section Label (e.g. "01 / About")', type: 'text', placeholder: '01 / About', section: 'about' },
        { key: 'aboutHeading', label: 'Section Heading', type: 'text', placeholder: 'A short version of a longer story.', section: 'about' },
        { key: 'aboutPara1', label: 'About — Paragraph 1', type: 'textarea', placeholder: 'I started writing code because I wanted my zines to have hover states…', section: 'about' },
        { key: 'aboutPara2', label: 'About — Paragraph 2', type: 'textarea', placeholder: 'Today I work on a B2B analytics product…', section: 'about' },
        { key: 'aboutPara3', label: 'About — Paragraph 3', type: 'textarea', placeholder: 'When I\'m not at a keyboard…', section: 'about' },
        { key: 'location', label: 'Based In', type: 'text', placeholder: 'Berlin, DE', section: 'about' },
        { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'CET (UTC+1)', section: 'about' },
        { key: 'education', label: 'Education', type: 'text', placeholder: 'B.Tech — VIT University', section: 'about' },
        { key: 'languages', label: 'Languages', type: 'text', placeholder: 'EN · DE', section: 'about' },
      ],
    },
    {
      key: 'skills',
      label: 'Skills',
      fields: [
        { key: 'skillsSectionLabel', label: 'Section Label (e.g. "02 / Skills")', type: 'text', placeholder: '02 / Skills', section: 'skills' },
        { key: 'skillsHeading', label: 'Section Heading', type: 'text', placeholder: 'The toolkit I reach for first.', section: 'skills' },
      ],
    },
    {
      key: 'experience',
      label: 'Experience',
      fields: [
        { key: 'expSectionLabel', label: 'Section Label (e.g. "03 / Experience")', type: 'text', placeholder: '03 / Experience', section: 'experience' },
        { key: 'expHeading', label: 'Section Heading', type: 'text', placeholder: "Where I've done the work.", section: 'experience' },
      ],
    },
    {
      key: 'projects',
      label: 'Projects',
      fields: [
        { key: 'projSectionLabel', label: 'Section Label (e.g. "04 / Selected Work")', type: 'text', placeholder: '04 / Selected Work', section: 'projects' },
        { key: 'projHeading', label: 'Section Heading', type: 'text', placeholder: "Selected work I'm proud of.", section: 'projects' },
      ],
    },
    {
      key: 'education',
      label: 'Education & Certifications',
      fields: [
        { key: 'eduSectionLabel', label: 'Section Label (e.g. "05 / Education")', type: 'text', placeholder: '05 / Education', section: 'education' },
        { key: 'eduHeading', label: 'Section Heading', type: 'text', placeholder: 'Where I learned to build.', section: 'education' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactSectionLabel', label: 'Section Label (e.g. "06 / Contact")', type: 'text', placeholder: '06 / Contact', section: 'contact' },
        { key: 'contactHeadline', label: 'Contact Headline', type: 'text', placeholder: "Got an interesting problem? Let's talk.", section: 'contact' },
        { key: 'contactSub', label: 'Contact Subtext', type: 'textarea', placeholder: "I'm picking up freelance work for Q3 2026 and quietly looking at staff-leaning frontend roles.", section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'you@example.com', section: 'contact' },
        { key: 'githubUrl', label: 'GitHub URL', type: 'url', placeholder: 'https://github.com/username', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/username', section: 'contact' },
        { key: 'blogHandle', label: 'Blog Handle / Domain', type: 'text', placeholder: '@marenwrites', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: 'oklch(0.16 0.008 260)', section: 'theme' },
        { key: 'colorBgElev', label: 'Background Elevated', type: 'color', placeholder: 'oklch(0.2 0.01 260)', section: 'theme' },
        { key: 'colorBgCard', label: 'Background Card', type: 'color', placeholder: 'oklch(0.22 0.012 260)', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (primary text)', type: 'color', placeholder: 'oklch(0.96 0.004 90)', section: 'theme' },
        { key: 'colorFgMuted', label: 'Foreground Muted', type: 'color', placeholder: 'oklch(0.7 0.01 260)', section: 'theme' },
        { key: 'colorFgFaint', label: 'Foreground Faint', type: 'color', placeholder: 'oklch(0.52 0.012 260)', section: 'theme' },
        { key: 'colorLine', label: 'Border / Line', type: 'color', placeholder: 'oklch(0.28 0.012 260)', section: 'theme' },
        { key: 'colorLineStrong', label: 'Border Strong', type: 'color', placeholder: 'oklch(0.36 0.014 260)', section: 'theme' },
        { key: 'colorAccent', label: 'Accent Color', type: 'color', placeholder: 'oklch(0.78 0.18 145)', section: 'theme' },
        { key: 'colorAccentSoft', label: 'Accent Soft (bg)', type: 'color', placeholder: 'oklch(0.28 0.06 145)', section: 'theme' },
        { key: 'colorAccentFg', label: 'Accent Foreground', type: 'color', placeholder: 'oklch(0.92 0.14 145)', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Maren Holloway',
    title: 'Software Engineer',
    subtitle: 'Building thoughtful interfaces for products people return to.',
    availability: 'Available Q3 2026',
    resumeUrl: '',
    skillsJson: JSON.stringify([
      { category: 'Languages', items: 'TypeScript, JavaScript, HTML, CSS / Sass, SQL, Python' },
      { category: 'Frameworks & UI', items: 'React, Next.js, Remix, Svelte, Tailwind, Framer Motion, Radix UI' },
      { category: 'Backend & Data', items: 'Node.js, tRPC, PostgreSQL, Prisma, Redis, REST & GraphQL' },
      { category: 'Tooling', items: 'Vite, Turborepo, pnpm, Vitest, Playwright, Storybook' },
      { category: 'Platform & Ops', items: 'Vercel, AWS (basics), Docker, GitHub Actions, Sentry' },
      { category: 'Craft', items: 'A11y (WCAG 2.2), Perf budgeting, Design systems, Animation, Figma' },
    ]),
    expJson: JSON.stringify([
      { period: 'Jul 2025 – Present', nowLabel: 'Present', duration: '10 months', role: 'Frontend Engineer', company: 'Lattice & Loom / B2B analytics, Series B', employmentType: 'Full-time', summary: 'Owning the chart and dashboard surface for a product used by 1,400+ ops teams.', bullets: "Rebuilt the dashboard renderer on a virtualized canvas — first paint −42%\nShipped 8 production features incl. cohort builder & saved views\nCut bundle size by −31% via route-level code splitting\nDrove the Radix-based design-system migration across 120+ components\nWrote the team's a11y checklist; product hit WCAG 2.2 AA\nReduced p95 interaction latency from 220ms to 95ms", stack: 'TypeScript, React, Next.js, tRPC, Postgres, Tailwind, Playwright', isCurrent: true },
      { period: 'May 2024 – Jun 2025', nowLabel: '', duration: '1 yr 2 mos', role: 'Junior Developer', company: 'Studio Werkraum / Design-systems agency', employmentType: 'Full-time', summary: 'Embedded with two healthtech clients to build, document, and maintain their internal component libraries.', bullets: 'Built 46 reusable React components from Figma specs\nAuthored Storybook docs adopted by 3 internal teams\nMigrated 18-page patient-portal flow to React Server Components\nImproved Lighthouse score from 64 → 96 on the marketing site\nSet up visual-regression suite catching ~2 regressions/sprint\nMentored an intern through their first PR-to-prod cycle', stack: 'React, TypeScript, Storybook, Sass, Vite, Chromatic', isCurrent: false },
    ]),
    projJson: JSON.stringify([
      { title: 'Plotwise', tag: '2026 · Solo', desc: 'A tiny, dependency-free charting library for product teams who keep outgrowing their dashboard tool. Renders 200k points at 60fps via a canvas+worker split.', stack: 'TypeScript, Canvas, Web Workers, Vitest', liveUrl: '', githubUrl: '' },
      { title: 'Marginalia', tag: '2025 · 2 contributors', desc: 'A keyboard-driven reading log for engineers. Pulls highlights from Kindle & Readwise, ranks them by re-read frequency, and gently re-surfaces them in your morning email.', stack: 'Next.js, Postgres, tRPC, Resend', liveUrl: '', githubUrl: '' },
      { title: 'Relay Notes', tag: '2025 · OSS', desc: 'Async stand-up tool for distributed teams. CRDT-backed multiplayer notes, deep links into Linear, no sign-up. Used by ~80 internal users daily.', stack: 'Svelte, Yjs, WebSockets, Fly.io', liveUrl: '', githubUrl: '' },
      { title: 'Kerning Club', tag: '2024 · For fun', desc: 'A daily kerning game for type nerds. Drag the letters until they sit right, get scored against a reference grid.', stack: 'React, Framer Motion, Vercel', liveUrl: '', githubUrl: '' },
    ]),
    location: 'Berlin, DE',
    timezone: 'CET (UTC+1)',
    education: '',
    languages: 'EN · DE',
    stat1Num: '2', stat1Unit: 'yrs', stat1Label: 'Shipping in production',
    stat2Num: '14', stat2Unit: '+', stat2Label: 'Features delivered',
    stat3Num: '38', stat3Unit: '%', stat3Label: 'Avg. perf gains landed',
    stat4Num: '6', stat4Unit: '', stat4Label: 'OSS contributions',
    aboutPara1: "I started writing code because I wanted my zines to have hover states. Two years in, that instinct hasn't really left — I still care about the small, felt details as much as I care about correctness, accessibility, and load times.",
    aboutPara2: "Today I work on a B2B analytics product where I own most of the visualization layer. Before that I cut my teeth at a design-systems agency, rebuilding component libraries for two healthtech clients.",
    aboutPara3: "When I'm not at a keyboard I'm probably reading printed serif journals, riding the U7, or quietly judging restaurant menu typography.",
    skillLang: 'TypeScript, JavaScript, HTML, CSS / Sass, SQL, Python',
    skillFramework: 'React, Next.js, Remix, Svelte, Tailwind, Framer Motion, Radix UI',
    skillBackend: 'Node.js, tRPC, PostgreSQL, Prisma, Redis, REST & GraphQL',
    skillTooling: 'Vite, Turborepo, pnpm, Vitest, Playwright, Storybook',
    skillPlatform: 'Vercel, AWS (basics), Docker, GitHub Actions, Sentry',
    skillCraft: 'A11y (WCAG 2.2), Perf budgeting, Design systems, Animation, Figma',
    exp1Period: 'Jul 2025 – Present',
    exp1Now: 'Present',
    exp1Duration: '10 months',
    exp1Role: 'Frontend Engineer',
    exp1Company: 'Lattice & Loom / B2B analytics, Series B',
    exp1Summary: 'Owning the chart and dashboard surface for a product used by 1,400+ ops teams.',
    exp1Bullets: 'Rebuilt the dashboard renderer on a virtualized canvas — first paint −42%\nShipped 8 production features incl. cohort builder & saved views\nCut bundle size by −31% via route-level code splitting\nDrove the Radix-based design-system migration across 120+ components\nWrote the team\'s a11y checklist; product hit WCAG 2.2 AA\nReduced p95 interaction latency from 220ms to 95ms',
    exp1Stack: 'TypeScript, React, Next.js, tRPC, Postgres, Tailwind, Playwright',
    exp2Period: 'May 2024 – Jun 2025',
    exp2Duration: '1 yr 2 mos',
    exp2Role: 'Junior Developer',
    exp2Company: 'Studio Werkraum / Design-systems agency',
    exp2Summary: 'Embedded with two healthtech clients to build, document, and maintain their internal component libraries.',
    exp2Bullets: 'Built 46 reusable React components from Figma specs\nAuthored Storybook docs adopted by 3 internal teams\nMigrated 18-page patient-portal flow to React Server Components\nImproved Lighthouse score from 64 → 96 on the marketing site\nSet up visual-regression suite catching ~2 regressions/sprint\nMentored an intern through their first PR-to-prod cycle',
    exp2Stack: 'React, TypeScript, Storybook, Sass, Vite, Chromatic',
    proj1Title: 'Plotwise',
    proj1Tag: '2026 · Solo',
    proj1Desc: 'A tiny, dependency-free charting library for product teams who keep outgrowing their dashboard tool. Renders 200k points at 60fps via a canvas+worker split.',
    proj1Stack: 'TypeScript, Canvas, Web Workers, Vitest',
    proj2Title: 'Marginalia',
    proj2Tag: '2025 · 2 contributors',
    proj2Desc: 'A keyboard-driven reading log for engineers. Pulls highlights from Kindle & Readwise, ranks them by re-read frequency, and gently re-surfaces them in your morning email.',
    proj2Stack: 'Next.js, Postgres, tRPC, Resend',
    proj3Title: 'Relay Notes',
    proj3Tag: '2025 · OSS',
    proj3Desc: 'Async stand-up tool for distributed teams. CRDT-backed multiplayer notes, deep links into Linear, no sign-up. Used by ~80 internal users daily.',
    proj3Stack: 'Svelte, Yjs, WebSockets, Fly.io',
    proj4Title: 'Kerning Club',
    proj4Tag: '2024 · For fun',
    proj4Desc: 'A daily kerning game for type nerds. Drag the letters until they sit right, get scored against a reference grid.',
    proj4Stack: 'React, Framer Motion, Vercel',
    eduSectionLabel: '05 / Education',
    eduHeading: 'Where I learned to build.',
    educationJson: JSON.stringify([
      { school: 'Technical University of Berlin', degree: 'B.Sc. Computer Science', period: '2020 – 2024', detail: 'GPA 1.8 · Thesis on reactive UI rendering architectures · Founded the campus web-dev club.' },
      { school: 'Self-taught · Online', degree: 'Continuous learning', period: '2021 – Now', detail: 'Frontend Masters, Josh Comeau\'s CSS for JS, Kent C. Dodds\' EpicReact, Theo\'s courses. Reading 1 dev book a month.' },
    ]),
    certsJson: JSON.stringify([
      { name: 'AWS Certified Cloud Practitioner', issuer: 'Amazon Web Services', year: '2024', url: '' },
      { name: 'Accessibility (CPACC)', issuer: 'IAAP', year: '2024', url: '' },
      { name: 'Epic React (Pro)', issuer: 'Kent C. Dodds', year: '2023', url: '' },
      { name: 'Meta Front-End Developer', issuer: 'Meta · Coursera', year: '2023', url: '' },
    ]),
    contactHeadline: "Got an interesting problem? Let's talk.",
    contactSub: "I'm picking up freelance work for Q3 2026 and quietly looking at staff-leaning frontend roles. The form is fine — email is faster.",
    contactEmail: 'maren@example.com',
    githubUrl: 'https://github.com/marenholloway',
    linkedinUrl: 'https://linkedin.com/in/maren-holloway',
    blogHandle: '@marenwrites',
    colorBg: 'oklch(0.16 0.008 260)',
    colorBgElev: 'oklch(0.2 0.01 260)',
    colorBgCard: 'oklch(0.22 0.012 260)',
    colorFg: 'oklch(0.96 0.004 90)',
    colorFgMuted: 'oklch(0.7 0.01 260)',
    colorFgFaint: 'oklch(0.52 0.012 260)',
    colorLine: 'oklch(0.28 0.012 260)',
    colorLineStrong: 'oklch(0.36 0.014 260)',
    colorAccent: 'oklch(0.78 0.18 145)',
    colorAccentSoft: 'oklch(0.28 0.06 145)',
    colorAccentFg: 'oklch(0.92 0.14 145)',
  },
};

export default marenConfig;
