import type { TemplateConfig } from '@/types';

const marenConfig: TemplateConfig = {
  slug: 'maren',
  name: 'Maren Template',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Maren Holloway', section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Software Engineer', section: 'hero' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', placeholder: 'Building thoughtful interfaces for products people return to.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Available Q3 2026', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '2', section: 'hero' },
        { key: 'stat1Unit', label: 'Stat 1 — Unit', type: 'text', placeholder: 'yrs', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Shipping in production', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '14', section: 'hero' },
        { key: 'stat2Unit', label: 'Stat 2 — Unit', type: 'text', placeholder: '+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Features delivered', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '38', section: 'hero' },
        { key: 'stat3Unit', label: 'Stat 3 — Unit', type: 'text', placeholder: '%', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Avg. perf gains landed', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '6', section: 'hero' },
        { key: 'stat4Unit', label: 'Stat 4 — Unit', type: 'text', placeholder: '', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'OSS contributions', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutPara1', label: 'About — Paragraph 1', type: 'textarea', placeholder: 'I started writing code because I wanted my zines to have hover states…', section: 'about' },
        { key: 'aboutPara2', label: 'About — Paragraph 2', type: 'textarea', placeholder: 'Today I work on a B2B analytics product…', section: 'about' },
        { key: 'aboutPara3', label: 'About — Paragraph 3', type: 'textarea', placeholder: 'When I\'m not at a keyboard…', section: 'about' },
        { key: 'location', label: 'Based In', type: 'text', placeholder: 'Berlin, DE', section: 'about' },
        { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'CET (UTC+1)', section: 'about' },
        { key: 'education', label: 'Education', type: 'text', placeholder: 'B.Tech — VIT University', section: 'about' },
        { key: 'languages', label: 'Languages', type: 'text', placeholder: 'EN · DE', section: 'about' },
      ],
    },
    {
      key: 'skills',
      label: 'Skills',
      fields: [
        { key: 'skillLang', label: 'Languages (comma-sep)', type: 'textarea', placeholder: 'TypeScript, JavaScript, HTML, CSS / Sass, SQL, Python', section: 'skills' },
        { key: 'skillFramework', label: 'Frameworks & UI (comma-sep)', type: 'textarea', placeholder: 'React, Next.js, Remix, Svelte, Tailwind, Framer Motion, Radix UI', section: 'skills' },
        { key: 'skillBackend', label: 'Backend & Data (comma-sep)', type: 'textarea', placeholder: 'Node.js, tRPC, PostgreSQL, Prisma, Redis, REST & GraphQL', section: 'skills' },
        { key: 'skillTooling', label: 'Tooling (comma-sep)', type: 'textarea', placeholder: 'Vite, Turborepo, pnpm, Vitest, Playwright, Storybook', section: 'skills' },
        { key: 'skillPlatform', label: 'Platform & Ops (comma-sep)', type: 'textarea', placeholder: 'Vercel, AWS (basics), Docker, GitHub Actions, Sentry', section: 'skills' },
        { key: 'skillCraft', label: 'Craft (comma-sep)', type: 'textarea', placeholder: 'A11y (WCAG 2.2), Perf budgeting, Design systems, Animation, Figma', section: 'skills' },
      ],
    },
    {
      key: 'experience',
      label: 'Experience',
      fields: [
        { key: 'exp1Period', label: 'Exp 1 — Period', type: 'text', placeholder: 'Jul 2025 – Present', section: 'experience' },
        { key: 'exp1Now', label: 'Exp 1 — Now Label (leave blank if not current)', type: 'text', placeholder: 'Present', section: 'experience' },
        { key: 'exp1Duration', label: 'Exp 1 — Duration Label', type: 'text', placeholder: '10 months', section: 'experience' },
        { key: 'exp1Role', label: 'Exp 1 — Role', type: 'text', placeholder: 'Frontend Engineer', section: 'experience' },
        { key: 'exp1Company', label: 'Exp 1 — Company', type: 'text', placeholder: 'Lattice & Loom / B2B analytics, Series B', section: 'experience' },
        { key: 'exp1Summary', label: 'Exp 1 — Summary', type: 'textarea', placeholder: 'Owning the chart and dashboard surface for a product used by 1,400+ ops teams.', section: 'experience' },
        { key: 'exp1Bullets', label: 'Exp 1 — Bullets (one per line)', type: 'textarea', placeholder: 'Rebuilt the dashboard renderer on a virtualized canvas — first paint −42%\nShipped 8 production features', section: 'experience' },
        { key: 'exp1Stack', label: 'Exp 1 — Stack (comma-sep)', type: 'text', placeholder: 'TypeScript, React, Next.js, tRPC, Postgres, Tailwind, Playwright', section: 'experience' },
        { key: 'exp2Period', label: 'Exp 2 — Period', type: 'text', placeholder: 'May 2024 – Jun 2025', section: 'experience' },
        { key: 'exp2Duration', label: 'Exp 2 — Duration Label', type: 'text', placeholder: '1 yr 2 mos', section: 'experience' },
        { key: 'exp2Role', label: 'Exp 2 — Role', type: 'text', placeholder: 'Junior Developer', section: 'experience' },
        { key: 'exp2Company', label: 'Exp 2 — Company', type: 'text', placeholder: 'Studio Werkraum / Design-systems agency', section: 'experience' },
        { key: 'exp2Summary', label: 'Exp 2 — Summary', type: 'textarea', placeholder: 'Embedded with two healthtech clients to build, document, and maintain their internal component libraries.', section: 'experience' },
        { key: 'exp2Bullets', label: 'Exp 2 — Bullets (one per line)', type: 'textarea', placeholder: 'Built 46 reusable React components from Figma specs\nAuthored Storybook docs adopted by 3 internal teams', section: 'experience' },
        { key: 'exp2Stack', label: 'Exp 2 — Stack (comma-sep)', type: 'text', placeholder: 'React, TypeScript, Storybook, Sass, Vite, Chromatic', section: 'experience' },
      ],
    },
    {
      key: 'projects',
      label: 'Projects',
      fields: [
        { key: 'proj1Title', label: 'Project 1 — Title', type: 'text', placeholder: 'Plotwise', section: 'projects' },
        { key: 'proj1Tag', label: 'Project 1 — Tag', type: 'text', placeholder: '2026 · Solo', section: 'projects' },
        { key: 'proj1Desc', label: 'Project 1 — Description', type: 'textarea', placeholder: 'A tiny, dependency-free charting library…', section: 'projects' },
        { key: 'proj1Stack', label: 'Project 1 — Stack (comma-sep)', type: 'text', placeholder: 'TypeScript, Canvas, Web Workers, Vitest', section: 'projects' },
        { key: 'proj1LiveUrl', label: 'Project 1 — Live URL', type: 'url', placeholder: 'https://plotwise.dev', section: 'projects' },
        { key: 'proj1GithubUrl', label: 'Project 1 — GitHub URL', type: 'url', placeholder: 'https://github.com/username/plotwise', section: 'projects' },
        { key: 'proj2Title', label: 'Project 2 — Title', type: 'text', placeholder: 'Marginalia', section: 'projects' },
        { key: 'proj2Tag', label: 'Project 2 — Tag', type: 'text', placeholder: '2025 · 2 contributors', section: 'projects' },
        { key: 'proj2Desc', label: 'Project 2 — Description', type: 'textarea', section: 'projects' },
        { key: 'proj2Stack', label: 'Project 2 — Stack (comma-sep)', type: 'text', section: 'projects' },
        { key: 'proj2LiveUrl', label: 'Project 2 — Live URL', type: 'url', section: 'projects' },
        { key: 'proj2GithubUrl', label: 'Project 2 — GitHub URL', type: 'url', section: 'projects' },
        { key: 'proj3Title', label: 'Project 3 — Title', type: 'text', section: 'projects' },
        { key: 'proj3Tag', label: 'Project 3 — Tag', type: 'text', section: 'projects' },
        { key: 'proj3Desc', label: 'Project 3 — Description', type: 'textarea', section: 'projects' },
        { key: 'proj3Stack', label: 'Project 3 — Stack (comma-sep)', type: 'text', section: 'projects' },
        { key: 'proj3LiveUrl', label: 'Project 3 — Live URL', type: 'url', section: 'projects' },
        { key: 'proj3GithubUrl', label: 'Project 3 — GitHub URL', type: 'url', section: 'projects' },
        { key: 'proj4Title', label: 'Project 4 — Title', type: 'text', section: 'projects' },
        { key: 'proj4Tag', label: 'Project 4 — Tag', type: 'text', section: 'projects' },
        { key: 'proj4Desc', label: 'Project 4 — Description', type: 'textarea', section: 'projects' },
        { key: 'proj4Stack', label: 'Project 4 — Stack (comma-sep)', type: 'text', section: 'projects' },
        { key: 'proj4LiveUrl', label: 'Project 4 — Live URL', type: 'url', section: 'projects' },
        { key: 'proj4GithubUrl', label: 'Project 4 — GitHub URL', type: 'url', section: 'projects' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactHeadline', label: 'Contact Headline', type: 'text', placeholder: "Got an interesting problem? Let's talk.", section: 'contact' },
        { key: 'contactSub', label: 'Contact Subtext', type: 'textarea', placeholder: "I'm picking up freelance work for Q3 2026 and quietly looking at staff-leaning frontend roles.", section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'you@example.com', section: 'contact' },
        { key: 'githubUrl', label: 'GitHub URL', type: 'url', placeholder: 'https://github.com/username', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/username', section: 'contact' },
        { key: 'blogHandle', label: 'Blog Handle / Domain', type: 'text', placeholder: '@marenwrites', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: 'oklch(0.16 0.008 260)', section: 'theme' },
        { key: 'colorBgElev', label: 'Background Elevated', type: 'color', placeholder: 'oklch(0.2 0.01 260)', section: 'theme' },
        { key: 'colorBgCard', label: 'Background Card', type: 'color', placeholder: 'oklch(0.22 0.012 260)', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (primary text)', type: 'color', placeholder: 'oklch(0.96 0.004 90)', section: 'theme' },
        { key: 'colorFgMuted', label: 'Foreground Muted', type: 'color', placeholder: 'oklch(0.7 0.01 260)', section: 'theme' },
        { key: 'colorFgFaint', label: 'Foreground Faint', type: 'color', placeholder: 'oklch(0.52 0.012 260)', section: 'theme' },
        { key: 'colorLine', label: 'Border / Line', type: 'color', placeholder: 'oklch(0.28 0.012 260)', section: 'theme' },
        { key: 'colorLineStrong', label: 'Border Strong', type: 'color', placeholder: 'oklch(0.36 0.014 260)', section: 'theme' },
        { key: 'colorAccent', label: 'Accent Color', type: 'color', placeholder: 'oklch(0.78 0.18 145)', section: 'theme' },
        { key: 'colorAccentSoft', label: 'Accent Soft (bg)', type: 'color', placeholder: 'oklch(0.28 0.06 145)', section: 'theme' },
        { key: 'colorAccentFg', label: 'Accent Foreground', type: 'color', placeholder: 'oklch(0.92 0.14 145)', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Maren Holloway',
    title: 'Software Engineer',
    subtitle: 'Building thoughtful interfaces for products people return to.',
    availability: 'Available Q3 2026',
    location: 'Berlin, DE',
    timezone: 'CET (UTC+1)',
    education: '',
    languages: 'EN · DE',
    stat1Num: '2', stat1Unit: 'yrs', stat1Label: 'Shipping in production',
    stat2Num: '14', stat2Unit: '+', stat2Label: 'Features delivered',
    stat3Num: '38', stat3Unit: '%', stat3Label: 'Avg. perf gains landed',
    stat4Num: '6', stat4Unit: '', stat4Label: 'OSS contributions',
    aboutPara1: "I started writing code because I wanted my zines to have hover states. Two years in, that instinct hasn't really left — I still care about the small, felt details as much as I care about correctness, accessibility, and load times.",
    aboutPara2: "Today I work on a B2B analytics product where I own most of the visualization layer. Before that I cut my teeth at a design-systems agency, rebuilding component libraries for two healthtech clients.",
    aboutPara3: "When I'm not at a keyboard I'm probably reading printed serif journals, riding the U7, or quietly judging restaurant menu typography.",
    skillLang: 'TypeScript, JavaScript, HTML, CSS / Sass, SQL, Python',
    skillFramework: 'React, Next.js, Remix, Svelte, Tailwind, Framer Motion, Radix UI',
    skillBackend: 'Node.js, tRPC, PostgreSQL, Prisma, Redis, REST & GraphQL',
    skillTooling: 'Vite, Turborepo, pnpm, Vitest, Playwright, Storybook',
    skillPlatform: 'Vercel, AWS (basics), Docker, GitHub Actions, Sentry',
    skillCraft: 'A11y (WCAG 2.2), Perf budgeting, Design systems, Animation, Figma',
    exp1Period: 'Jul 2025 – Present',
    exp1Now: 'Present',
    exp1Duration: '10 months',
    exp1Role: 'Frontend Engineer',
    exp1Company: 'Lattice & Loom / B2B analytics, Series B',
    exp1Summary: 'Owning the chart and dashboard surface for a product used by 1,400+ ops teams.',
    exp1Bullets: 'Rebuilt the dashboard renderer on a virtualized canvas — first paint −42%\nShipped 8 production features incl. cohort builder & saved views\nCut bundle size by −31% via route-level code splitting\nDrove the Radix-based design-system migration across 120+ components\nWrote the team\'s a11y checklist; product hit WCAG 2.2 AA\nReduced p95 interaction latency from 220ms to 95ms',
    exp1Stack: 'TypeScript, React, Next.js, tRPC, Postgres, Tailwind, Playwright',
    exp2Period: 'May 2024 – Jun 2025',
    exp2Duration: '1 yr 2 mos',
    exp2Role: 'Junior Developer',
    exp2Company: 'Studio Werkraum / Design-systems agency',
    exp2Summary: 'Embedded with two healthtech clients to build, document, and maintain their internal component libraries.',
    exp2Bullets: 'Built 46 reusable React components from Figma specs\nAuthored Storybook docs adopted by 3 internal teams\nMigrated 18-page patient-portal flow to React Server Components\nImproved Lighthouse score from 64 → 96 on the marketing site\nSet up visual-regression suite catching ~2 regressions/sprint\nMentored an intern through their first PR-to-prod cycle',
    exp2Stack: 'React, TypeScript, Storybook, Sass, Vite, Chromatic',
    proj1Title: 'Plotwise',
    proj1Tag: '2026 · Solo',
    proj1Desc: 'A tiny, dependency-free charting library for product teams who keep outgrowing their dashboard tool. Renders 200k points at 60fps via a canvas+worker split.',
    proj1Stack: 'TypeScript, Canvas, Web Workers, Vitest',
    proj2Title: 'Marginalia',
    proj2Tag: '2025 · 2 contributors',
    proj2Desc: 'A keyboard-driven reading log for engineers. Pulls highlights from Kindle & Readwise, ranks them by re-read frequency, and gently re-surfaces them in your morning email.',
    proj2Stack: 'Next.js, Postgres, tRPC, Resend',
    proj3Title: 'Relay Notes',
    proj3Tag: '2025 · OSS',
    proj3Desc: 'Async stand-up tool for distributed teams. CRDT-backed multiplayer notes, deep links into Linear, no sign-up. Used by ~80 internal users daily.',
    proj3Stack: 'Svelte, Yjs, WebSockets, Fly.io',
    proj4Title: 'Kerning Club',
    proj4Tag: '2024 · For fun',
    proj4Desc: 'A daily kerning game for type nerds. Drag the letters until they sit right, get scored against a reference grid.',
    proj4Stack: 'React, Framer Motion, Vercel',
    contactHeadline: "Got an interesting problem? Let's talk.",
    contactSub: "I'm picking up freelance work for Q3 2026 and quietly looking at staff-leaning frontend roles. The form is fine — email is faster.",
    contactEmail: 'maren@example.com',
    githubUrl: 'https://github.com/marenholloway',
    linkedinUrl: 'https://linkedin.com/in/maren-holloway',
    blogHandle: '@marenwrites',
    colorBg: 'oklch(0.16 0.008 260)',
    colorBgElev: 'oklch(0.2 0.01 260)',
    colorBgCard: 'oklch(0.22 0.012 260)',
    colorFg: 'oklch(0.96 0.004 90)',
    colorFgMuted: 'oklch(0.7 0.01 260)',
    colorFgFaint: 'oklch(0.52 0.012 260)',
    colorLine: 'oklch(0.28 0.012 260)',
    colorLineStrong: 'oklch(0.36 0.014 260)',
    colorAccent: 'oklch(0.78 0.18 145)',
    colorAccentSoft: 'oklch(0.28 0.06 145)',
    colorAccentFg: 'oklch(0.92 0.14 145)',
  },
};

export default marenConfig;
