import type { TemplateConfig } from '@/types';

const mintslateConfig: TemplateConfig = {
  slug: 'mintslate',
  name: 'Mint Slate',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'photoUrl', label: 'Profile Photo', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Taylor Chen', section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Full-Stack Engineer', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Open to opportunities', section: 'hero' },
        { key: 'yoe', label: 'Years of Experience', type: 'text', placeholder: '5', section: 'hero' },
        { key: 'bio', label: 'Bio (supports **bold**)', type: 'textarea', placeholder: 'I build fast, accessible web products...', section: 'hero' },
        { key: 'heroTagline', label: 'Hero Tagline', type: 'text', placeholder: 'builds things that ship.', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'location', label: 'Location', type: 'text', placeholder: 'San Francisco, CA', section: 'hero' },
        { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'PST (UTC-8)', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '5+', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Years Experience', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '30+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Projects Shipped', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '99%', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Uptime Record', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '12', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'OSS Contributions', section: 'hero' },
      ],
    },
    {
      key: 'skills',
      label: 'Skills',
      fields: [
        { key: 'skillsHeading', label: 'Section Heading', type: 'text', placeholder: 'Core stack', section: 'skills' },
        { key: 'skillsSub', label: 'Section Subheading', type: 'text', placeholder: 'The tools I reach for when I need to ship something today.', section: 'skills' },
        { key: 'skillCore', label: 'Core Skills (comma-sep)', type: 'textarea', placeholder: 'React, TypeScript, Node.js, PostgreSQL, Docker', section: 'skills' },
        { key: 'skillLearning', label: 'Currently Learning (comma-sep)', type: 'textarea', placeholder: 'Rust, WebAssembly', section: 'skills' },
        { key: 'learningHrs', label: 'Learning Hours / Week', type: 'text', placeholder: '10 hrs/week', section: 'skills' },
      ],
    },
    {
      key: 'experience',
      label: 'Experience',
      fields: [
        { key: 'expHeading', label: 'Section Heading', type: 'text', placeholder: 'Track record', section: 'experience' },
        { key: 'expSub', label: 'Section Subheading', type: 'text', placeholder: 'Ship measurable wins, leave the codebase better than I found it.', section: 'experience' },
      ],
    },
    {
      key: 'projects',
      label: 'Projects',
      fields: [
        { key: 'projHeading', label: 'Section Heading', type: 'text', placeholder: "Things I've shipped", section: 'projects' },
        { key: 'projSub', label: 'Section Subheading', type: 'text', placeholder: 'Projects where I owned the architecture, implementation, and the metric.', section: 'projects' },
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testimonialsHeading', label: 'Section Heading', type: 'text', placeholder: 'What others say', section: 'testimonials' },
        { key: 'testimonialsSub', label: 'Section Subheading', type: 'text', placeholder: "From the people I've shipped with.", section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactHeading', label: 'Section Heading', type: 'text', placeholder: "Let's build something.", section: 'contact' },
        { key: 'contactSub', label: 'Availability Line', type: 'text', placeholder: 'Available for new projects', section: 'contact' },
        { key: 'contactDesc', label: 'Description', type: 'textarea', placeholder: "I'm currently open to senior and staff-level roles.", section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'taylor@example.com', section: 'contact' },
        { key: 'githubUrl', label: 'GitHub URL', type: 'url', placeholder: 'https://github.com/taylorchen', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/taylorchen', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://twitter.com/taylorchen', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: '#f0fdf4', section: 'theme' },
        { key: 'colorBg2', label: 'Background Elevated', type: 'color', placeholder: '#f8fafc', section: 'theme' },
        { key: 'colorCard', label: 'Background Card', type: 'color', placeholder: '#ffffff', section: 'theme' },
        { key: 'colorText', label: 'Foreground (primary text)', type: 'color', placeholder: '#1e293b', section: 'theme' },
        { key: 'colorTextMuted', label: 'Foreground Muted', type: 'color', placeholder: '#475569', section: 'theme' },
        { key: 'colorTextFaint', label: 'Foreground Faint', type: 'color', placeholder: '#94a3b8', section: 'theme' },
        { key: 'colorBorder', label: 'Border / Line', type: 'color', placeholder: '#e2e8f0', section: 'theme' },
        { key: 'colorBorderStrong', label: 'Border Strong', type: 'color', placeholder: '#cbd5e1', section: 'theme' },
        { key: 'colorAccent', label: 'Accent Color', type: 'color', placeholder: '#2dd4bf', section: 'theme' },
        { key: 'colorAccentHover', label: 'Accent Hover', type: 'color', placeholder: '#14b8a6', section: 'theme' },
        { key: 'colorAccentDark', label: 'Accent Dark', type: 'color', placeholder: '#0f766e', section: 'theme' },
        { key: 'colorAccentSoft', label: 'Accent Soft (bg)', type: 'color', placeholder: '#ccfbf1', section: 'theme' },
        { key: 'colorAccentFaint', label: 'Accent Faint (bg)', type: 'color', placeholder: '#ecfdf5', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    photoUrl: '',
    name: 'Taylor Chen',
    title: 'Full-Stack Engineer',
    availability: 'Open to opportunities',
    yoe: '5',
    bio: 'I build **fast**, **accessible** web products that scale. Passionate about developer experience, clean APIs, and shipping things that matter.',
    heroTagline: 'builds things that ship.',
    resumeUrl: '',
    location: 'San Francisco, CA',
    timezone: 'PST (UTC-8)',
    stat1Num: '5+', stat1Label: 'Years Experience',
    stat2Num: '30+', stat2Label: 'Projects Shipped',
    stat3Num: '99%', stat3Label: 'Uptime Record',
    stat4Num: '12', stat4Label: 'OSS Contributions',
    skillsHeading: 'Core stack',
    skillsSub: 'The tools I reach for when I need to ship something today, with confidence.',
    skillCore: 'React, TypeScript, Node.js, PostgreSQL, Docker, Next.js, GraphQL, Redis',
    skillLearning: 'Rust, WebAssembly',
    learningHrs: '10 hrs/week',
    toolsJson: JSON.stringify([
      { name: 'VS Code', ctx: 'Primary IDE', image: '' },
      { name: 'Figma', ctx: 'Design & Prototyping', image: '' },
      { name: 'Neovim', ctx: 'Terminal work', image: '' },
    ]),
    expHeading: 'Track record',
    expSub: 'Ship measurable wins, leave the codebase better than I found it.',
    expJson: JSON.stringify([
      { role: 'Senior Full-Stack Engineer', company: 'Vercel', tagline: 'Infrastructure & DX', period: '2023 – Present', duration: '2 yrs', isCurrent: true, bullets: 'Reduced cold start times by 40% via edge function optimization\nBuilt edge middleware for A/B testing serving 50M requests/day', stack: 'TypeScript, Next.js, Go, PostgreSQL, Redis' },
      { role: 'Frontend Engineer', company: 'Stripe', tagline: 'Payments UI', period: '2021 – 2023', duration: '2 yrs', isCurrent: false, bullets: 'Built checkout flow used by 500k+ merchants globally\nImproved payment conversion rate by 12% through UX iteration', stack: 'React, TypeScript, Ruby on Rails, Sass' },
    ]),
    projHeading: "Things I've shipped",
    projSub: 'Projects where I owned the architecture, implementation, and the metric that mattered.',
    projJson: JSON.stringify([
      { title: 'DevFlow', year: '2024', image: '', desc: 'A developer workflow tool that streamlines code review and deployment.', stack: 'React, TypeScript, Node.js, PostgreSQL', impact: '10k monthly active users', challenge: 'Real-time collaboration at scale', liveUrl: '', githubUrl: '' },
      { title: 'PerfPulse', year: '2023', image: '', desc: 'Lightweight performance monitoring SDK for Next.js apps.', stack: 'TypeScript, Next.js, ClickHouse', impact: '2k npm downloads/month', challenge: '<1kb bundle overhead', liveUrl: '', githubUrl: '' },
      { title: 'SchemaForge', year: '2023', image: '', desc: 'Visual database schema designer with instant TypeScript type generation.', stack: 'React, TypeScript, SQLite', impact: '5k GitHub stars', challenge: 'Accurate type inference across dialects', liveUrl: '', githubUrl: '' },
    ]),
    testimonialsHeading: 'What others say',
    testimonialsSub: "From the people I've shipped with and engineers who've reviewed my code.",
    testJson: JSON.stringify([
      { quote: 'Taylor shipped our redesign two weeks early and the performance numbers were outstanding.', initials: 'SK', name: 'Sarah Kim', role: 'Engineering Manager, Vercel' },
      { quote: "One of the best engineers I've worked with. Rare ability to balance technical excellence with strong product instincts.", initials: 'MR', name: 'Marcus Rodriguez', role: 'CTO, DevFlow' },
    ]),
    contactHeading: "Let's build something.",
    contactSub: 'Available for new projects',
    contactDesc: "I'm currently open to senior and staff-level roles as well as interesting freelance projects.",
    contactEmail: 'taylor@example.com',
    githubUrl: 'https://github.com/taylorchen',
    linkedinUrl: 'https://linkedin.com/in/taylorchen',
    twitterUrl: 'https://twitter.com/taylorchen',
    colorAccent: '#2dd4bf',
    colorAccentHover: '#14b8a6',
    colorAccentDark: '#0f766e',
    colorAccentSoft: '#ccfbf1',
    colorAccentFaint: '#ecfdf5',
    colorBg: '#f0fdf4',
    colorBg2: '#f8fafc',
    colorCard: '#ffffff',
    colorBorder: '#e2e8f0',
    colorBorderStrong: '#cbd5e1',
    colorText: '#1e293b',
    colorTextMuted: '#475569',
    colorTextFaint: '#94a3b8',
  },
};

export default mintslateConfig;
