import type { TemplateConfig } from '@/types';

const mosaicConfig: TemplateConfig = {
  slug: 'mosaic',
  name: 'Mosaic',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'photoUrl', label: 'Portrait Photo (Polaroid)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Sasha Park', section: 'hero' },
        { key: 'title', label: 'Role / Title', type: 'text', placeholder: 'Independent Designer', section: 'hero' },
        { key: 'heroTagline', label: 'Hero Tagline (2 lines · 2nd line is handwritten)', type: 'textarea', placeholder: "Hi, I'm Sasha.\nI make things you'll love.", section: 'hero' },
        { key: 'bio', label: 'Bio (supports **bold**)', type: 'textarea', placeholder: 'I design brand identities…', section: 'hero' },
        { key: 'yoe', label: 'Years of Experience', type: 'text', placeholder: '6', section: 'hero' },
        { key: 'location', label: 'Location', type: 'text', placeholder: 'Seoul, KR', section: 'hero' },
        { key: 'resumeUrl', label: 'CV / Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'heroStickers', label: 'Sticker Labels (comma-sep, max 5)', type: 'textarea', placeholder: 'design ✻, strategy ✦, typography ★, illustration ✿', section: 'hero' },
        { key: 'heroCtaPrimary', label: 'Primary CTA Button Label', type: 'text', placeholder: 'See the work', section: 'hero' },
        { key: 'heroCtaSecondary', label: 'Secondary CTA Button Label', type: 'text', placeholder: 'Grab my CV', section: 'hero' },
        { key: 'heroPhotoArrow', label: 'Photo Arrow Doodle Text', type: 'text', placeholder: "that's me!", section: 'hero' },
        { key: 'heroPhotoCaption', label: 'Polaroid Caption (leave empty for auto)', type: 'text', placeholder: '— Sasha, Seoul', section: 'hero' },
        { key: 'navCtaLabel', label: 'Nav "Say hi" Button Label', type: 'text', placeholder: 'Say hi', section: 'hero' },
        { key: 'marqueeItems', label: 'Marquee Items (comma-sep · leave empty to hide)', type: 'textarea', placeholder: 'Branding, Editorial, Art direction, Typography, Illustration, Identity systems', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '6+', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Years', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '40+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Projects', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '8', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Awards', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '∞', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'Coffees', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '01 · About', section: 'about' },
        { key: 'aboutHeading', label: 'Section Heading (main)', type: 'text', placeholder: 'A little', section: 'about' },
        { key: 'aboutHeadingHand', label: 'Section Heading (handwritten)', type: 'text', placeholder: 'about me.', section: 'about' },
        { key: 'aboutPhotoUrl', label: 'About Section Photo', type: 'image', placeholder: '', section: 'about' },
        { key: 'aboutStickyNote', label: 'Sticky Note (handwritten)', type: 'text', placeholder: 'always sketching first.', section: 'about' },
        { key: 'aboutPara1', label: 'About — Paragraph 1', type: 'textarea', placeholder: "I'm a designer based in…", section: 'about' },
        { key: 'aboutPara2', label: 'About — Paragraph 2 (optional)', type: 'textarea', placeholder: 'When I am not designing…', section: 'about' },
        { key: 'education', label: 'Education', type: 'text', placeholder: 'BFA · Hongik', section: 'about' },
        { key: 'languages', label: 'Languages', type: 'text', placeholder: 'EN · KO', section: 'about' },
        { key: 'metaLocationLabel', label: 'Meta — Location Label', type: 'text', placeholder: 'Based in', section: 'about' },
        { key: 'metaPracticeLabel', label: 'Meta — Practice Label', type: 'text', placeholder: 'Practice', section: 'about' },
        { key: 'metaPracticeSuffix', label: 'Meta — Practice Value Suffix', type: 'text', placeholder: 'years', section: 'about' },
        { key: 'metaEducationLabel', label: 'Meta — Education Label', type: 'text', placeholder: 'Studied', section: 'about' },
        { key: 'metaLanguagesLabel', label: 'Meta — Languages Label', type: 'text', placeholder: 'Speaks', section: 'about' },
      ],
    },
    {
      key: 'services',
      label: 'What I Do',
      fields: [
        { key: 'servicesSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '02 · What I do', section: 'services' },
        { key: 'servicesHeadingMarker', label: 'Heading Marker (highlighted word)', type: 'text', placeholder: 'Services', section: 'services' },
        { key: 'servicesHeading', label: 'Heading (rest of title)', type: 'text', placeholder: 'on offer.', section: 'services' },
        { key: 'services', label: 'Services (comma-sep, max 8)', type: 'textarea', placeholder: 'Brand identity, Visual systems, Editorial, Art direction, Web design', section: 'services' },
        { key: 'servicesItemPrefix', label: 'Service Card Prefix', type: 'text', placeholder: 'SVC', section: 'services' },
        { key: 'servicesSub', label: 'Section Subheading', type: 'text', placeholder: 'A few of the things I help studios make.', section: 'services' },
      ],
    },
    {
      key: 'work',
      label: 'Selected Work',
      fields: [
        { key: 'workSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '03 · Selected work', section: 'work' },
        { key: 'workHeading', label: 'Heading (main)', type: 'text', placeholder: "Things I've", section: 'work' },
        { key: 'workHeadingHand', label: 'Heading (handwritten)', type: 'text', placeholder: 'made.', section: 'work' },
        { key: 'projSub', label: 'Section Subheading', type: 'textarea', placeholder: 'A handful of recent projects…', section: 'work' },
        { key: 'workItemPrefix', label: 'Project Card Prefix', type: 'text', placeholder: 'PROJECT', section: 'work' },
        { key: 'workMetaTypeLabel', label: 'Project Meta — Type Label', type: 'text', placeholder: 'Type', section: 'work' },
        { key: 'workMetaYearLabel', label: 'Project Meta — Year Label', type: 'text', placeholder: 'Year', section: 'work' },
        { key: 'workLinkLabel', label: 'Project Link Label (with URL)', type: 'text', placeholder: 'Open case study', section: 'work' },
        { key: 'workLinkLabelEmpty', label: 'Project Link Label (no URL)', type: 'text', placeholder: 'Case study', section: 'work' },
        { key: 'workEmptyText', label: 'Empty State Text', type: 'text', placeholder: 'No projects yet — add your work from the dashboard ✦', section: 'work' },
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testimonialsSectionLabel', label: 'Section Number/Label', type: 'text', placeholder: '04 · Words', section: 'testimonials' },
        { key: 'testimonialsHeading', label: 'Heading (main)', type: 'text', placeholder: 'Kind', section: 'testimonials' },
        { key: 'testimonialsHeadingHand', label: 'Heading (handwritten)', type: 'text', placeholder: 'words.', section: 'testimonials' },
        { key: 'testimonialsSub', label: 'Section Subheading', type: 'textarea', placeholder: "A few notes from the people I've worked with.", section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'postcardStampLabel', label: 'Postcard Stamp Label', type: 'text', placeholder: '★ Postcard · No. 01', section: 'contact' },
        { key: 'postcardDate', label: 'Postcard Date (leave empty for auto)', type: 'text', placeholder: 'Mar 14, 2026', section: 'contact' },
        { key: 'postcardCost', label: 'Postage Cost', type: 'text', placeholder: '$1', section: 'contact' },
        { key: 'postcardClassLabel', label: 'Postage Class Label', type: 'text', placeholder: 'FIRST CLASS', section: 'contact' },
        { key: 'postcardGreeting', label: 'Letter Greeting', type: 'text', placeholder: 'Hi there,', section: 'contact' },
        { key: 'postcardSignLabel', label: 'Signature Label', type: 'text', placeholder: '— signed,', section: 'contact' },
        { key: 'postcardSignature', label: 'Signature Name (leave empty for first name)', type: 'text', placeholder: 'Sasha', section: 'contact' },
        { key: 'postcardReachLabel', label: 'Reach-me Label', type: 'text', placeholder: 'Reach me at', section: 'contact' },
        { key: 'postcardFindLabel', label: 'Or-find-me Label', type: 'text', placeholder: 'Or find me', section: 'contact' },
        { key: 'postcardDoodle1', label: 'Doodle 1 (top-left, leave empty to hide)', type: 'text', placeholder: 'drop a line ↘', section: 'contact' },
        { key: 'postcardDoodle2', label: 'Doodle 2 (bottom-right, leave empty to hide)', type: 'text', placeholder: '↖ p.s. say hi!', section: 'contact' },
        { key: 'contactSub', label: 'Letter Message (supports **bold**)', type: 'textarea', placeholder: "I'd love to hear about your project…", section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'hello@sasha.studio', section: 'contact' },
        { key: 'instagramUrl', label: 'Instagram URL', type: 'url', placeholder: 'https://instagram.com/sasha', section: 'contact' },
        { key: 'behanceUrl', label: 'Behance URL', type: 'url', placeholder: 'https://behance.net/sasha', section: 'contact' },
        { key: 'dribbbleUrl', label: 'Dribbble URL', type: 'url', placeholder: 'https://dribbble.com/sasha', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/sasha', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://twitter.com/sasha', section: 'contact' },
        { key: 'footerLabel', label: 'Footer Studio Label', type: 'text', placeholder: 'Sasha Park — Studio', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Paper / Cream Background', type: 'color', placeholder: '#FDF8F0', section: 'theme' },
        { key: 'colorBg2', label: 'Elevated Paper', type: 'color', placeholder: '#F7F0E1', section: 'theme' },
        { key: 'colorText', label: 'Ink (Foreground)', type: 'color', placeholder: '#2A2622', section: 'theme' },
        { key: 'colorAccent', label: 'Accent 1 (primary)', type: 'color', placeholder: '#E8533D', section: 'theme' },
        { key: 'colorAccent2', label: 'Accent 2 (yellow)', type: 'color', placeholder: '#F4B233', section: 'theme' },
        { key: 'colorAccent3', label: 'Accent 3 (green)', type: 'color', placeholder: '#6BA86B', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    photoUrl: '',
    name: 'Sasha Park',
    title: 'Independent Designer',
    heroTagline: "Hi, I'm Sasha.\nI make things you'll love.",
    bio: "I design **brand identities**, **editorial systems**, and the occasional poster — for studios, founders, and friends who care about the details.",
    yoe: '6',
    location: 'Seoul, KR',
    resumeUrl: '',
    heroStickers: 'design ✻, strategy ✦, typography ★, illustration ✿, art direction ✸',
    heroCtaPrimary: 'See the work',
    heroCtaSecondary: 'Grab my CV',
    heroPhotoArrow: "that's me!",
    heroPhotoCaption: '',
    navCtaLabel: 'Say hi',
    marqueeItems: 'Branding, Editorial, Art direction, Typography, Illustration, Identity systems',
    stat1Num: '6+', stat1Label: 'Years',
    stat2Num: '40+', stat2Label: 'Projects',
    stat3Num: '8', stat3Label: 'Awards',
    stat4Num: '∞', stat4Label: 'Coffees',
    aboutSectionLabel: '01 · About',
    aboutHeading: 'A little',
    aboutHeadingHand: 'about me.',
    aboutPhotoUrl: '',
    aboutStickyNote: 'always sketching first.',
    aboutPara1: "I'm a designer based in Seoul with **6+ years** of practice across brand, editorial, and product. I love making things by hand and refining them on screen — the best ideas usually start on paper.",
    aboutPara2: "When I'm not designing, you'll find me at flea markets, in bookstores, or at the coffee shop down the street planning my next poster.",
    education: 'BFA · Hongik University',
    languages: 'EN · KO',
    metaLocationLabel: 'Based in',
    metaPracticeLabel: 'Practice',
    metaPracticeSuffix: 'years',
    metaEducationLabel: 'Studied',
    metaLanguagesLabel: 'Speaks',
    servicesSectionLabel: '02 · What I do',
    servicesHeadingMarker: 'Services',
    servicesHeading: 'on offer.',
    servicesItemPrefix: 'SVC',
    services: 'Brand identity, Visual systems, Editorial design, Art direction, Web design, Illustration',
    servicesSub: 'A few of the things I help studios, founders, and teams make.',
    workSectionLabel: '03 · Selected work',
    workHeading: "Things I've",
    workHeadingHand: 'made.',
    workItemPrefix: 'PROJECT',
    workMetaTypeLabel: 'Type',
    workMetaYearLabel: 'Year',
    workLinkLabel: 'Open case study',
    workLinkLabelEmpty: 'Case study',
    workEmptyText: 'No projects yet — add your work from the dashboard ✦',
    projSub: 'A handful of recent projects across brand, editorial, and product. More on request.',
    projJson: JSON.stringify([
      { title: 'Folio Press', year: '2024', category: 'Editorial', image: '', desc: 'Art direction and editorial system for an independent magazine on craft and slowness — 128 pages, four issues a year.', stack: 'Editorial, Type design, Print', impact: 'Sold-out launch issue', liveUrl: '' },
      { title: 'Hatch Coffee', year: '2024', category: 'Brand identity', image: '', desc: 'Naming, identity, and packaging for a third-wave coffee roaster with a wildly seasonal menu and a cult following.', stack: 'Identity, Packaging, Illustration', impact: 'Featured · Brand New', liveUrl: '' },
      { title: 'Bloom & Co', year: '2023', category: 'Brand identity', image: '', desc: 'A complete refresh for a family florist transitioning from neighbourhood shop to nationwide DTC. New name, new system, new website.', stack: 'Identity, Web, Naming', impact: '3x DTC revenue', liveUrl: '' },
      { title: 'Solace App', year: '2023', category: 'Product', image: '', desc: 'Product design for a mindfulness app — visual language, illustrations, motion principles, and full iOS app design.', stack: 'Product, UI/UX, Motion', impact: '120k installs', liveUrl: '' },
    ]),
    testimonialsSectionLabel: '04 · Words',
    testimonialsHeading: 'Kind',
    testimonialsHeadingHand: 'words.',
    testimonialsSub: "A few notes from the people I've had the joy of making things with.",
    testJson: JSON.stringify([
      { quote: 'Sasha turned a messy brief into the clearest, warmest brand we have ever had. The kind of designer you write thank-you cards to.', initials: 'JR', name: 'Julia Reyes', role: 'Co-founder, Hatch Coffee' },
      { quote: 'Honest, fast, and full of ideas. Working with Sasha changed the way I think about what design is for.', initials: 'DA', name: 'Diego Alvarez', role: 'CEO, Solace' },
      { quote: 'A masterclass in taste and craft. I would hire Sasha again tomorrow.', initials: 'MK', name: 'Marie Klein', role: 'Editor, Folio Press' },
    ]),
    postcardStampLabel: '★ Postcard · No. 01',
    postcardDate: '',
    postcardCost: '$1',
    postcardClassLabel: 'FIRST CLASS',
    postcardGreeting: 'Hi there,',
    postcardSignLabel: '— signed,',
    postcardSignature: '',
    postcardReachLabel: 'Reach me at',
    postcardFindLabel: 'Or find me',
    postcardDoodle1: 'drop a line ↘',
    postcardDoodle2: '↖ p.s. say hi!',
    contactSub: "I'd love to hear about your **project** — the brief, the timing, and what you're hoping to make. Pop me a line and let's get started.",
    contactEmail: 'hello@sasha.studio',
    instagramUrl: 'https://instagram.com/sasha',
    behanceUrl: 'https://behance.net/sasha',
    dribbbleUrl: '',
    linkedinUrl: 'https://linkedin.com/in/sasha',
    twitterUrl: '',
    footerLabel: '',
    colorBg: '#FDF8F0',
    colorBg2: '#F7F0E1',
    colorText: '#2A2622',
    colorAccent: '#E8533D',
    colorAccent2: '#F4B233',
    colorAccent3: '#6BA86B',
  },
};

export default mosaicConfig;
