import type { TemplateConfig } from '@/types';

const nexusConfig: TemplateConfig = {
  slug: 'nexus',
  name: 'Nexus',
  sections: [
    {
      key: 'hero',
      label: 'README.md',
      fields: [
        { key: 'photoUrl', label: 'Profile Photo', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Alex Rivera', section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Full-Stack Engineer', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Open to opportunities', section: 'hero' },
        { key: 'yoe', label: 'Years of Experience', type: 'text', placeholder: '5', section: 'hero' },
        { key: 'bio', label: 'Bio (supports **bold**)', type: 'textarea', placeholder: 'I build performant, type-safe systems...', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'location', label: 'Location', type: 'text', placeholder: 'Berlin, DE', section: 'hero' },
        { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'CET (UTC+1)', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '5+', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Years Experience', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '40+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Projects Shipped', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '99.9%', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Uptime SLO', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '24', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'OSS Contributions', section: 'hero' },
      ],
    },
    {
      key: 'skills',
      label: 'skills.json',
      fields: [
        { key: 'skillsHeading', label: 'Section Heading', type: 'text', placeholder: 'core stack & tools', section: 'skills' },
        { key: 'skillCore', label: 'Core Skills (comma-sep)', type: 'textarea', placeholder: 'TypeScript, React, Node.js, PostgreSQL, Docker', section: 'skills' },
        { key: 'skillLearning', label: 'Currently Learning (comma-sep)', type: 'textarea', placeholder: 'Rust, WebAssembly', section: 'skills' },
      ],
    },
    {
      key: 'experience',
      label: 'experience.tsx',
      fields: [
        { key: 'expHeading', label: 'Section Heading', type: 'text', placeholder: 'professional track record', section: 'experience' },
      ],
    },
    {
      key: 'projects',
      label: 'projects.json',
      fields: [
        { key: 'projHeading', label: 'Section Heading', type: 'text', placeholder: 'featured shipped projects', section: 'projects' },
      ],
    },
    {
      key: 'testimonials',
      label: 'refs.md',
      fields: [
        { key: 'testimonialsHeading', label: 'Section Heading', type: 'text', placeholder: 'references from collaborators', section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'contact.sh',
      fields: [
        { key: 'contactHeading', label: 'Section Heading', type: 'text', placeholder: 'get in touch', section: 'contact' },
        { key: 'contactSub', label: 'Response Description', type: 'textarea', placeholder: 'Replies within 24h. Async-friendly.', section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'alex@example.com', section: 'contact' },
        { key: 'githubUrl', label: 'GitHub URL', type: 'url', placeholder: 'https://github.com/alexrivera', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/alexrivera', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://twitter.com/alexrivera', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: '#0d1117', section: 'theme' },
        { key: 'colorBg2', label: 'Background Elevated', type: 'color', placeholder: '#161b22', section: 'theme' },
        { key: 'colorBg3', label: 'Background Highlighted', type: 'color', placeholder: '#1c2230', section: 'theme' },
        { key: 'colorBorder', label: 'Border / Line', type: 'color', placeholder: '#21262d', section: 'theme' },
        { key: 'colorText', label: 'Foreground (primary)', type: 'color', placeholder: '#e6edf3', section: 'theme' },
        { key: 'colorTextMuted', label: 'Foreground Muted', type: 'color', placeholder: '#9ca3af', section: 'theme' },
        { key: 'colorAccent', label: 'Accent Color', type: 'color', placeholder: '#58a6ff', section: 'theme' },
        { key: 'colorAccentHover', label: 'Accent Hover', type: 'color', placeholder: '#79c0ff', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    photoUrl: '',
    name: 'Alex Rivera',
    title: 'Full-Stack Engineer',
    availability: 'Open to opportunities',
    yoe: '5',
    bio: 'I build **performant**, **type-safe** systems that scale. Focused on developer experience and shipping things that matter — from edge infrastructure to refined UI.',
    resumeUrl: '',
    location: 'Berlin, DE',
    timezone: 'CET (UTC+1)',
    stat1Num: '5+', stat1Label: 'Years Experience',
    stat2Num: '40+', stat2Label: 'Projects Shipped',
    stat3Num: '99.9%', stat3Label: 'Uptime SLO',
    stat4Num: '24', stat4Label: 'OSS Contributions',
    skillsHeading: 'core stack & tools',
    skillCore: 'TypeScript, React, Next.js, Node.js, PostgreSQL, Redis, Docker, Kubernetes, GraphQL, tRPC',
    skillLearning: 'Rust, WebAssembly, Zig',
    toolsJson: JSON.stringify([
      { name: 'VS Code', ctx: 'Primary editor', image: '' },
      { name: 'Neovim', ctx: 'Terminal sessions', image: '' },
      { name: 'Figma', ctx: 'Design handoff', image: '' },
      { name: 'Linear', ctx: 'Issue tracking', image: '' },
      { name: 'Vercel', ctx: 'Deployment', image: '' },
      { name: 'Postman', ctx: 'API testing', image: '' },
    ]),
    expHeading: 'professional track record',
    expJson: JSON.stringify([
      { role: 'Senior Engineer', company: 'Vercel', tagline: 'Infrastructure & developer experience for the edge.', period: '2023 – Present', duration: '2 yrs · current', isCurrent: true, bullets: 'Reduced cold-start times by **40%** via edge function optimization\nBuilt A/B testing middleware serving **50M+** requests/day\nLed a 6-engineer migration to a new monorepo build pipeline', stack: 'TypeScript, Next.js, Go, PostgreSQL, Redis' },
      { role: 'Frontend Engineer', company: 'Stripe', tagline: 'Payments surfaces used by hundreds of thousands of merchants.', period: '2021 – 2023', duration: '2 yrs', isCurrent: false, bullets: 'Shipped checkout flow used by **500k+** merchants globally\nImproved payment conversion by **12%** through UX iteration\nMentored 3 junior engineers and ran the team\'s eng-review channel', stack: 'React, TypeScript, Ruby on Rails, Sass' },
      { role: 'Software Engineer', company: 'Acme Labs', tagline: 'Early-stage product work across a fast-moving startup.', period: '2019 – 2021', duration: '2 yrs', isCurrent: false, bullets: 'Built the v1 of internal admin tools used by ops & support\nMigrated legacy PHP service to Node + TypeScript with **zero** downtime', stack: 'Node.js, TypeScript, React, PostgreSQL' },
    ]),
    projHeading: 'featured shipped projects',
    projJson: JSON.stringify([
      { title: 'DevFlow', year: '2024', image: '', desc: 'A developer workflow tool integrating GitHub, Linear, and Slack into one terminal-first UI.', stack: 'React, TypeScript, Node.js, PostgreSQL', impact: '10k MAU', challenge: 'Real-time collab across distributed teams', liveUrl: '', githubUrl: '' },
      { title: 'PerfPulse', year: '2023', image: '', desc: 'Lightweight performance monitoring SDK for Next.js apps, <1kb of overhead.', stack: 'TypeScript, ClickHouse, Edge', impact: '2k npm/month', challenge: '<1kb bundle, zero PII leaked', liveUrl: '', githubUrl: '' },
      { title: 'SchemaForge', year: '2023', image: '', desc: 'Visual database schema designer with instant TypeScript type generation.', stack: 'React, TypeScript, SQLite', impact: '5k GitHub ⭐', challenge: 'Accurate type inference across SQL dialects', liveUrl: '', githubUrl: '' },
      { title: 'EdgeCache', year: '2022', image: '', desc: 'A distributed edge-cache layer for high-traffic APIs.', stack: 'Go, Redis, Kubernetes', impact: '99.99% hit rate', challenge: 'Sub-10ms eviction across regions', liveUrl: '', githubUrl: '' },
    ]),
    testimonialsHeading: 'references from collaborators',
    testJson: JSON.stringify([
      { quote: 'Alex shipped our redesign two weeks early and the performance numbers were outstanding. Rare combo of speed, taste, and rigor.', initials: 'SK', name: 'Sarah Kim', role: 'Eng Manager, Vercel' },
      { quote: "One of the best engineers I've worked with. Strong product instincts paired with rare technical depth.", initials: 'MR', name: 'Marcus Rodriguez', role: 'CTO, DevFlow' },
    ]),
    contactHeading: 'get in touch',
    contactSub: 'Replies within 24h. Async-friendly across time zones.',
    contactEmail: 'alex@example.com',
    githubUrl: 'https://github.com/alexrivera',
    linkedinUrl: 'https://linkedin.com/in/alexrivera',
    twitterUrl: 'https://twitter.com/alexrivera',
    colorBg: '#0d1117',
    colorBg2: '#161b22',
    colorBg3: '#1c2230',
    colorBorder: '#21262d',
    colorText: '#e6edf3',
    colorTextMuted: '#9ca3af',
    colorAccent: '#58a6ff',
    colorAccentHover: '#79c0ff',
  },
};

export default nexusConfig;
