import type { TemplateConfig } from '@/types';

const prismConfig: TemplateConfig = {
  slug: 'prism',
  name: 'Prism',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'photoUrl', label: 'Portrait / Profile Photo', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Maya Velasco', section: 'hero' },
        { key: 'title', label: 'Role / Title', type: 'text', placeholder: 'Multidisciplinary Designer', section: 'hero' },
        { key: 'heroTagline', label: 'Hero Tagline (Line 1 + Line 2 — 2 lines)', type: 'textarea', placeholder: 'I make brands\nfeel alive', section: 'hero' },
        { key: 'bio', label: 'Bio (supports **bold**)', type: 'textarea', placeholder: 'Independent designer crafting **identities** and **products** for ambitious teams.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Open for new work · Q1-Q2', section: 'hero' },
        { key: 'yoe', label: 'Years of Experience', type: 'text', placeholder: '7', section: 'hero' },
        { key: 'location', label: 'Location', type: 'text', placeholder: 'Mexico City, MX', section: 'hero' },
        { key: 'resumeUrl', label: 'CV / Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '7+', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Years of practice', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '60+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Brands launched', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '14', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Awards & features', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '∞', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'Cups of coffee', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'services', label: 'Services / Disciplines (comma-sep)', type: 'textarea', placeholder: 'Brand identity, Visual design, Art direction, Web design, Editorial', section: 'about' },
        { key: 'philosophy', label: 'Philosophy / Pull Quote', type: 'textarea', placeholder: 'Good design is invisible. Great design tells a story you remember.', section: 'about' },
        { key: 'philosophyAuthor', label: 'Philosophy Attribution', type: 'text', placeholder: 'the studio', section: 'about' },
      ],
    },
    {
      key: 'work',
      label: 'Selected Work',
      fields: [
        { key: 'projSub', label: 'Section Subheading', type: 'textarea', placeholder: 'A small selection of recent client engagements and personal explorations.', section: 'work' },
      ],
    },
    {
      key: 'process',
      label: 'Process',
      fields: [
        // process is fed by processJson (managed elsewhere)
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testimonialsSub', label: 'Section Subheading', type: 'textarea', placeholder: "A few words from the people I've had the pleasure of working with.", section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactSub', label: 'Contact Subtext', type: 'textarea', placeholder: 'Currently booking new client work. Drop me a note.', section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'hello@maya.studio', section: 'contact' },
        { key: 'instagramUrl', label: 'Instagram URL', type: 'url', placeholder: 'https://instagram.com/maya', section: 'contact' },
        { key: 'behanceUrl', label: 'Behance URL', type: 'url', placeholder: 'https://behance.net/maya', section: 'contact' },
        { key: 'dribbbleUrl', label: 'Dribbble URL', type: 'url', placeholder: 'https://dribbble.com/maya', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/maya', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://twitter.com/maya', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorC1', label: 'Accent 1 (coral)', type: 'color', placeholder: '#FF6B6B', section: 'theme' },
        { key: 'colorC2', label: 'Accent 2 (yellow)', type: 'color', placeholder: '#FFD93D', section: 'theme' },
        { key: 'colorC3', label: 'Accent 3 (green)', type: 'color', placeholder: '#6BCB77', section: 'theme' },
        { key: 'colorC4', label: 'Accent 4 (blue)', type: 'color', placeholder: '#4D96FF', section: 'theme' },
        { key: 'colorC5', label: 'Accent 5 (purple)', type: 'color', placeholder: '#C780FA', section: 'theme' },
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: '#0D0B1E', section: 'theme' },
        { key: 'colorBg2', label: 'Background Elevated', type: 'color', placeholder: '#15122A', section: 'theme' },
        { key: 'colorText', label: 'Foreground (primary)', type: 'color', placeholder: '#F5F0FF', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    photoUrl: '',
    name: 'Maya Velasco',
    title: 'Multidisciplinary Designer',
    heroTagline: 'I make brands\nfeel alive',
    bio: 'Independent designer crafting **identities** and **products** for ambitious teams. Currently shaping visual systems for early-stage startups and culture-driven brands.',
    availability: 'Open for new work · Q1-Q2',
    yoe: '7',
    location: 'Mexico City, MX',
    resumeUrl: '',
    stat1Num: '7+', stat1Label: 'Years of practice',
    stat2Num: '60+', stat2Label: 'Brands launched',
    stat3Num: '14', stat3Label: 'Awards & features',
    stat4Num: '∞', stat4Label: 'Cups of coffee',
    services: 'Brand identity, Visual design, Art direction, Web design, Editorial design',
    philosophy: 'Good design is invisible. Great design tells a story you remember.',
    philosophyAuthor: 'the studio',
    projSub: 'A small selection of recent client engagements and personal explorations.',
    projJson: JSON.stringify([
      { title: 'Lumen Studio', year: '2024', category: 'Brand identity', image: '', desc: 'Visual identity and design system for a boutique consultancy launching their next chapter — a system that scales from business card to billboard.', stack: 'Identity, Web, Print', impact: 'Series A close', liveUrl: '' },
      { title: 'Bloom Atelier', year: '2024', category: 'Editorial', image: '', desc: 'Editorial direction for a quarterly journal exploring craft, slowness, and modern making. 96 pages of considered typography.', stack: 'Editorial, Art direction, Print', impact: 'Print run sold out', liveUrl: '' },
      { title: 'Refract App', year: '2023', category: 'Product', image: '', desc: 'Product design for a creative tools app — from initial sketches to a shipped iOS app with a strong, joyful design language.', stack: 'Product, UI/UX, iOS', impact: '50k installs', liveUrl: '' },
      { title: 'Cascade Coffee', year: '2023', category: 'Packaging', image: '', desc: 'Packaging redesign for a third-wave coffee roaster — wordmark, label system, and a flexible visual identity that travels.', stack: 'Packaging, Identity', impact: '3x DTC growth', liveUrl: '' },
      { title: 'Field Notes Co.', year: '2022', category: 'Brand identity', image: '', desc: 'Naming, brand identity, and launch campaign for a stationery company built on a love of analog tools.', stack: 'Naming, Identity, Web', impact: 'Featured · Brand New', liveUrl: '' },
      { title: 'Solene Skincare', year: '2022', category: 'Packaging', image: '', desc: 'Premium skincare packaging and brand system rooted in botanical illustration and serif typography.', stack: 'Identity, Packaging, Illustration', impact: 'Sephora launch', liveUrl: '' },
    ]),
    processJson: JSON.stringify([
      { title: 'Discover', description: 'Deep research into brand, users, and competitors. We dig until we find something true.' },
      { title: 'Explore', description: 'Multiple directions, rapid iteration, bold choices. The wider, the better.' },
      { title: 'Refine', description: 'Sharpen the strongest concept into a system that bends without breaking.' },
      { title: 'Deliver', description: 'Production-ready files, brand guidelines, and a friendly handoff.' },
    ]),
    testimonialsSub: "A few words from the people I've had the pleasure of working with.",
    testJson: JSON.stringify([
      { quote: 'Maya turned our messy brief into the clearest brand we have ever had. She is a rare talent.', initials: 'JR', name: 'Julia Reyes', role: 'Co-founder, Lumen Studio' },
      { quote: 'Honest, fast, and incredibly thoughtful. The work we made together changed our trajectory.', initials: 'DA', name: 'Diego Alvarez', role: 'CEO, Refract' },
      { quote: 'Working with Maya is a masterclass in taste and craft. She elevates every detail.', initials: 'MK', name: 'Marie Klein', role: 'Creative Director, Bloom' },
      { quote: 'Best designer we have ever hired. Period.', initials: 'TN', name: 'Tomás Núñez', role: 'Founder, Field Notes Co.' },
    ]),
    contactSub: "Currently booking new client work. Drop me a note with the project, timing, and what you're hoping to achieve.",
    contactEmail: 'hello@maya.studio',
    instagramUrl: 'https://instagram.com/maya',
    behanceUrl: 'https://behance.net/maya',
    dribbbleUrl: 'https://dribbble.com/maya',
    linkedinUrl: 'https://linkedin.com/in/maya',
    twitterUrl: 'https://twitter.com/maya',
    colorC1: '#FF6B6B',
    colorC2: '#FFD93D',
    colorC3: '#6BCB77',
    colorC4: '#4D96FF',
    colorC5: '#C780FA',
    colorBg: '#0D0B1E',
    colorBg2: '#15122A',
    colorText: '#F5F0FF',
  },
};

export default prismConfig;
