import type { TemplateConfig } from '@/types';

const pulseConfig: TemplateConfig = {
  slug: 'pulse',
  name: 'Pulse Template',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Pulse Okafor', section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Growth marketer for SaaS', section: 'hero' },
        { key: 'heroHeadline', label: 'Hero Headline', type: 'textarea', placeholder: 'Compounding growth for SaaS that refuses to plateau.', section: 'hero' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', placeholder: 'Full-funnel marketing operator. I take SaaS from $1M to $20M ARR with paid, SEO, and lifecycle that actually compounds.', section: 'hero' },
        { key: 'brandStrip', label: 'Brand Strip (comma-separated)', type: 'text', placeholder: 'Notion, Linear, Vercel, Figma, Loom, Ramp', section: 'hero' },
      ],
    },
    {
      key: 'stats',
      label: 'Stats',
      fields: [
        { key: 'statsJson', label: 'Stats JSON', type: 'textarea', placeholder: '[{"value":"50","label":"Revenue driven","suffix":"M+"}]', section: 'stats' },
      ],
    },
    {
      key: 'services',
      label: 'Services',
      fields: [
        { key: 'servicesJson', label: 'Services JSON', type: 'textarea', placeholder: '[{"title":"SEO","description":"...","channels":"...","deliverables":"..."}]', section: 'services' },
      ],
    },
    {
      key: 'caseStudies',
      label: 'Case Studies',
      fields: [
        { key: 'caseStudiesJson', label: 'Case Studies JSON', type: 'textarea', placeholder: '[{"client":"...","industry":"...","challenge":"...","solution":"...","results":[],"channels":"...","period":"..."}]', section: 'caseStudies' },
      ],
    },
    {
      key: 'channels',
      label: 'Channels & Stack',
      fields: [
        { key: 'channelsJson', label: 'Channels JSON', type: 'textarea', placeholder: '[{"category":"Ads","items":"Google Ads, Meta, LinkedIn"}]', section: 'channels' },
      ],
    },
    {
      key: 'brands',
      label: 'Brands Worked With',
      fields: [
        { key: 'brandsJson', label: 'Brands JSON', type: 'textarea', placeholder: '[{"name":"Notion"}]', section: 'brands' },
      ],
    },
    {
      key: 'press',
      label: 'Press & Features',
      fields: [
        { key: 'pressJson', label: 'Press JSON', type: 'textarea', placeholder: '[{"title":"...","venue":"...","year":"2025","url":"..."}]', section: 'press' },
      ],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [
        { key: 'testimonialsJson', label: 'Testimonials JSON', type: 'textarea', placeholder: '[{"quote":"...","author":"...","role":"...","company":"...","result":"..."}]', section: 'testimonials' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'pulse@example.com', section: 'contact' },
        { key: 'calendarUrl', label: 'Calendar URL', type: 'url', placeholder: 'https://cal.com/pulseokafor', section: 'contact' },
        { key: 'location', label: 'Location', type: 'text', placeholder: 'Lagos · Remote-first', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/pulseokafor', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://x.com/pulseokafor', section: 'contact' },
        { key: 'websiteUrl', label: 'Website URL', type: 'url', placeholder: 'https://pulseokafor.com', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background', type: 'color', placeholder: '#0d0d12', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (text)', type: 'color', placeholder: '#f4f4f0', section: 'theme' },
        { key: 'colorAccent', label: 'Accent (neon yellow)', type: 'color', placeholder: '#e8ff5a', section: 'theme' },
        { key: 'colorAccent2', label: 'Accent 2 (hot pink)', type: 'color', placeholder: '#ff3d8b', section: 'theme' },
        { key: 'colorLine', label: 'Border / Line', type: 'color', placeholder: '#26262e', section: 'theme' },
        { key: 'colorCard', label: 'Card Background', type: 'color', placeholder: '#16161c', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Pulse Okafor',
    title: 'Growth marketer for SaaS',
    heroHeadline: 'Compounding growth for SaaS that refuses to plateau.',
    subtitle: 'Full-funnel marketing operator. I take Series A–C SaaS from $1M to $20M ARR with paid, SEO, and lifecycle that actually compounds — no vanity metrics, no fluff.',
    brandStrip: 'Notion, Linear, Vercel, Figma, Loom, Ramp, Retool, Stripe',
    contactEmail: 'pulse@pulseokafor.com',
    calendarUrl: 'https://cal.com/pulseokafor/intro',
    location: 'Lagos · Remote-first',
    linkedinUrl: 'https://linkedin.com/in/pulseokafor',
    twitterUrl: 'https://x.com/pulseokafor',
    websiteUrl: 'https://pulseokafor.com',
    statsJson: JSON.stringify([
      { value: '50', label: 'Revenue driven for clients', suffix: 'M+' },
      { value: '4.8', label: 'Avg. ROAS across paid', suffix: 'x' },
      { value: '320', label: 'Organic traffic lift', suffix: '%' },
      { value: '27', label: 'SaaS brands scaled', suffix: '' },
    ]),
    servicesJson: JSON.stringify([
      {
        title: 'SEO & Organic Growth',
        description: 'Programmatic + editorial SEO engines that turn search demand into pipeline. I build the keyword graph, the content system, and the link velocity to win the category.',
        channels: 'Google, Bing, AI Search, Reddit',
        deliverables: 'Keyword strategy, content briefs, programmatic pages, link building, internal linking audit',
      },
      {
        title: 'Paid Acquisition',
        description: 'High-intent paid funnels across Google, Meta, and LinkedIn. Built around payback period, not last-click vanity. I obsess over CAC, LTV, and contribution margin.',
        channels: 'Google Ads, Meta, LinkedIn, Reddit, X',
        deliverables: 'Account structure, creative testing, landing pages, MMM, attribution model',
      },
      {
        title: 'Content & Brand',
        description: 'Opinionated content that earns attention in a sea of LLM slop. Long-form playbooks, founder POV, and a distribution plan that goes beyond LinkedIn shitposting.',
        channels: 'Blog, YouTube, Podcast, LinkedIn, Newsletter',
        deliverables: 'Editorial calendar, ghostwriting, video scripts, design system for content',
      },
      {
        title: 'Email & Lifecycle',
        description: 'Behavioral email and product-led lifecycle flows that activate, convert, and expand. From cold MQL to ARR — every email earns its keep.',
        channels: 'Customer.io, HubSpot, Loops, Iterable',
        deliverables: 'Onboarding sequences, win-back, upsell campaigns, lead nurture, transactional UX',
      },
      {
        title: 'Growth Experimentation',
        description: 'A weekly experiment loop across acquisition, activation, and monetization. We ship, we measure, we double down on what works. Everything is documented.',
        channels: 'Mixpanel, Amplitude, GA4, PostHog',
        deliverables: 'Experiment backlog, A/B tests, North Star tree, growth model in Mode',
      },
      {
        title: 'Brand & Positioning',
        description: 'Sharp positioning that makes your buyer feel seen. Messaging matrices, ICP maps, and a verbal identity that survives contact with reality.',
        channels: 'Website, Sales decks, Ads, PR',
        deliverables: 'Positioning doc, messaging house, naming, tone-of-voice guide',
      },
    ]),
    caseStudiesJson: JSON.stringify([
      {
        client: 'Stacklane',
        industry: 'B2B SaaS · Dev tools',
        challenge: 'Stuck at $2.4M ARR with flatlining paid and a content engine that produced 4 posts a month and zero pipeline. CAC payback had crept past 18 months.',
        solution: 'Rebuilt the paid account around bottom-of-funnel keywords, shipped 60 programmatic SEO pages, and rewired the lifecycle so trial users hit value in under 7 days. Killed 40% of spend on day one.',
        results: [
          { label: 'ARR growth', value: '$2.4M → $9.1M' },
          { label: 'CAC payback', value: '18mo → 6mo' },
          { label: 'Organic signups', value: '+412%' },
          { label: 'Paid ROAS', value: '2.1x → 5.6x' },
        ],
        channels: 'SEO, Google Ads, Lifecycle, Onboarding',
        period: '14 months',
        image: '',
      },
      {
        client: 'Northbeam Labs',
        industry: 'B2B SaaS · Analytics',
        challenge: 'Pre-PMF Series A burning $180k/mo on paid with no attribution discipline. Marketing was a black box and the board wanted answers.',
        solution: 'Built a contribution-margin attribution model in Mode, cut 6 underperforming channels, doubled down on LinkedIn ABM, and launched a category-defining report that earned 14 backlinks from DR70+ sites.',
        results: [
          { label: 'Pipeline generated', value: '$14M' },
          { label: 'Marketing-sourced ARR', value: '38% → 71%' },
          { label: 'CPL on LinkedIn', value: '−63%' },
          { label: 'Branded search', value: '+540%' },
        ],
        channels: 'LinkedIn Ads, ABM, PR, Content',
        period: '11 months',
        image: '',
      },
      {
        client: 'Mira Health',
        industry: 'Healthtech · D2C',
        challenge: 'New consumer health brand, zero domain authority, competing against 9-figure incumbents on the same keywords. Founders wanted scale without burning the seed round.',
        solution: 'Niched down to 3 underserved ICPs, built a hub-and-spoke SEO content library, launched a referral loop inside the app, and ran a creator program with 22 micro-influencers on payout-per-signup.',
        results: [
          { label: 'Monthly signups', value: '0 → 18k' },
          { label: 'CAC', value: '$48 → $19' },
          { label: 'Organic share', value: '0% → 58%' },
          { label: 'Year-one revenue', value: '$3.6M' },
        ],
        channels: 'SEO, Creator, Referral, Email',
        period: '9 months',
        image: '',
      },
      {
        client: 'Velocity OS',
        industry: 'B2B SaaS · Ops platform',
        challenge: 'Strong product, weak narrative. Sales cycles dragged past 90 days and win rates against the obvious competitor sat at 22%.',
        solution: 'Repositioned around a sharper buyer pain, rebuilt the website around the new story, armed sales with a competitive battle card, and shipped a buyer-education email sequence.',
        results: [
          { label: 'Win rate', value: '22% → 47%' },
          { label: 'Sales cycle', value: '92 days → 41 days' },
          { label: 'Demo-to-close', value: '+38%' },
          { label: 'ARR added', value: '$4.2M' },
        ],
        channels: 'Positioning, Web, Sales enablement, Email',
        period: '6 months',
        image: '',
      },
    ]),
    channelsJson: JSON.stringify([
      { category: 'Paid Ads', items: 'Google Ads, Meta Ads, LinkedIn Ads, Reddit Ads, X Ads, TikTok Ads' },
      { category: 'Analytics & Attribution', items: 'GA4, Mixpanel, Amplitude, PostHog, Northbeam, Heap, Mode, Hex' },
      { category: 'SEO & Content', items: 'Ahrefs, Semrush, Clearscope, Screaming Frog, Surfer, Frase, Webflow CMS' },
      { category: 'Email & Lifecycle', items: 'Customer.io, HubSpot, Loops, Iterable, Klaviyo, Beehiiv, Resend' },
      { category: 'CRM & Sales', items: 'HubSpot, Salesforce, Attio, Apollo, Clay, Gong, Default' },
    ]),
    brandsJson: JSON.stringify([
      { name: 'Notion' },
      { name: 'Linear' },
      { name: 'Vercel' },
      { name: 'Figma' },
      { name: 'Loom' },
      { name: 'Ramp' },
      { name: 'Retool' },
      { name: 'Stripe' },
      { name: 'PostHog' },
      { name: 'Webflow' },
      { name: 'Cal.com' },
      { name: 'Resend' },
    ]),
    pressJson: JSON.stringify([
      { title: 'The Growth Playbook That Actually Compounds', venue: 'First Round Review', year: '2025', url: 'https://review.firstround.com' },
      { title: 'Why Most SaaS SEO Strategies Plateau At $5M ARR', venue: 'Lenny\'s Newsletter', year: '2025', url: 'https://lennysnewsletter.com' },
      { title: 'Inside The Stacklane Turnaround', venue: 'SaaStr Annual', year: '2024', url: 'https://saastr.com' },
      { title: 'Marketing-Led Growth Is Back (And Smarter)', venue: 'Demand Curve', year: '2024', url: 'https://demandcurve.com' },
      { title: 'The 40-Minute Growth Audit', venue: 'Marketing Brew', year: '2023', url: 'https://morningbrew.com/marketing' },
    ]),
    testimonialsJson: JSON.stringify([
      {
        quote: 'Pulse rebuilt our entire growth motion in 90 days. We went from second-guessing every spend to running the cleanest experiment loop I\'ve ever seen at a SaaS company. CAC dropped 58%. Period.',
        author: 'Maya Rendell',
        role: 'CEO & Co-founder',
        company: 'Stacklane',
        result: 'CAC −58% in 90 days',
      },
      {
        quote: 'The category report Pulse shipped did more for our pipeline than 18 months of paid combined. Sales walked into meetings with prospects who already knew our story. That\'s the bar now.',
        author: 'Daniel Osei',
        role: 'VP Marketing',
        company: 'Northbeam Labs',
        result: '$14M pipeline generated',
      },
      {
        quote: 'Most growth marketers sell motion. Pulse sells outcomes — and ships them. We hit our annual plan in seven months. The board thinks I\'m a genius. I just hired Pulse.',
        author: 'Selene Park',
        role: 'Founder',
        company: 'Mira Health',
        result: 'Annual plan hit in 7 months',
      },
      {
        quote: 'Repositioning is the hardest thing in marketing and most people fake it. Pulse did the real work — customer interviews, messaging tests, sales tape teardowns — and our win rate more than doubled.',
        author: 'Ravi Chen',
        role: 'CRO',
        company: 'Velocity OS',
        result: 'Win rate 22% → 47%',
      },
    ]),
    colorBg: '#0d0d12',
    colorFg: '#f4f4f0',
    colorAccent: '#e8ff5a',
    colorAccent2: '#ff3d8b',
    colorLine: '#26262e',
    colorCard: '#16161c',
  },
};

export default pulseConfig;
