import type { TemplateConfig } from '@/types';

const quartzConfig: TemplateConfig = {
  slug: 'quartz',
  name: 'Quartz',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'photoUrl', label: 'Profile Photo', type: 'image', placeholder: '', section: 'hero' },
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Sam Aldrich', section: 'hero' },
        { key: 'role', label: 'Role / Title', type: 'text', placeholder: 'Senior Full-Stack Engineer', section: 'hero' },
        { key: 'tagline', label: 'Tagline (short statement)', type: 'text', placeholder: 'Building software that earns its place.', section: 'hero' },
        { key: 'subtitle', label: 'Hero Subtitle', type: 'textarea', placeholder: 'I help product teams turn rough ideas into shipped features — calm, well-tested, and built to last.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Open to roles · Q3 2026', section: 'hero' },
        { key: 'location', label: 'Based In', type: 'text', placeholder: 'Amsterdam, NL', section: 'hero' },
        { key: 'resumeUrl', label: 'Resume (PDF upload)', type: 'image', placeholder: '', section: 'hero' },
        { key: 'stat1Num', label: 'Stat 1 — Number', type: 'text', placeholder: '8', section: 'hero' },
        { key: 'stat1Label', label: 'Stat 1 — Label', type: 'text', placeholder: 'Years Shipping', section: 'hero' },
        { key: 'stat2Num', label: 'Stat 2 — Number', type: 'text', placeholder: '60+', section: 'hero' },
        { key: 'stat2Label', label: 'Stat 2 — Label', type: 'text', placeholder: 'Features Delivered', section: 'hero' },
        { key: 'stat3Num', label: 'Stat 3 — Number', type: 'text', placeholder: '14', section: 'hero' },
        { key: 'stat3Label', label: 'Stat 3 — Label', type: 'text', placeholder: 'Teams Joined', section: 'hero' },
        { key: 'stat4Num', label: 'Stat 4 — Number', type: 'text', placeholder: '24', section: 'hero' },
        { key: 'stat4Label', label: 'Stat 4 — Label', type: 'text', placeholder: 'OSS Merges', section: 'hero' },
      ],
    },
    {
      key: 'about',
      label: 'About',
      fields: [
        { key: 'aboutSectionLabel', label: 'Section Label', type: 'text', placeholder: '/01 — About', section: 'about' },
        { key: 'aboutHeading', label: 'Section Heading', type: 'text', placeholder: 'A short version of a longer story.', section: 'about' },
        { key: 'aboutPara1', label: 'About — Paragraph 1', type: 'textarea', placeholder: 'I started building software because…', section: 'about' },
        { key: 'aboutPara2', label: 'About — Paragraph 2', type: 'textarea', placeholder: 'Today I work on…', section: 'about' },
        { key: 'aboutPara3', label: 'About — Paragraph 3', type: 'textarea', placeholder: 'Away from the keyboard…', section: 'about' },
        { key: 'focus', label: 'Current Focus', type: 'text', placeholder: 'Frontend systems & dev tooling', section: 'about' },
        { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'CET · UTC+1', section: 'about' },
        { key: 'languages', label: 'Languages', type: 'text', placeholder: 'EN · NL', section: 'about' },
        { key: 'education', label: 'Education Tagline', type: 'text', placeholder: 'B.Sc. CS · TU Delft', section: 'about' },
      ],
    },
    {
      key: 'skills',
      label: 'Skills',
      fields: [
        { key: 'skillsSectionLabel', label: 'Section Label', type: 'text', placeholder: '/02 — Skills', section: 'skills' },
        { key: 'skillsHeading', label: 'Section Heading', type: 'text', placeholder: 'The tools I reach for.', section: 'skills' },
        { key: 'skillsSub', label: 'Section Subheading', type: 'textarea', placeholder: 'A grouped view of what I work with day-to-day.', section: 'skills' },
      ],
    },
    {
      key: 'experience',
      label: 'Experience',
      fields: [
        { key: 'expSectionLabel', label: 'Section Label', type: 'text', placeholder: '/03 — Experience', section: 'experience' },
        { key: 'expHeading', label: 'Section Heading', type: 'text', placeholder: "Where I've done the work.", section: 'experience' },
      ],
    },
    {
      key: 'projects',
      label: 'Projects',
      fields: [
        { key: 'projSectionLabel', label: 'Section Label', type: 'text', placeholder: '/04 — Selected Work', section: 'projects' },
        { key: 'projHeading', label: 'Section Heading', type: 'text', placeholder: 'Things I have built.', section: 'projects' },
        { key: 'projSub', label: 'Section Subheading', type: 'textarea', placeholder: 'Client work, side projects, and small experiments.', section: 'projects' },
      ],
    },
    {
      key: 'education',
      label: 'Education & Certifications',
      fields: [
        { key: 'eduSectionLabel', label: 'Section Label', type: 'text', placeholder: '/05 — Background', section: 'education' },
        { key: 'eduHeading', label: 'Section Heading', type: 'text', placeholder: 'Where I learned to build.', section: 'education' },
      ],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactSectionLabel', label: 'Section Label', type: 'text', placeholder: '/06 — Contact', section: 'contact' },
        { key: 'contactHeadline', label: 'Contact Headline', type: 'text', placeholder: 'Have a project in mind?', section: 'contact' },
        { key: 'contactSub', label: 'Contact Subtext', type: 'textarea', placeholder: 'I am open to senior frontend roles and small consulting engagements.', section: 'contact' },
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'hello@samaldrich.dev', section: 'contact' },
        { key: 'githubUrl', label: 'GitHub URL', type: 'url', placeholder: 'https://github.com/username', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/username', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter / X URL', type: 'url', placeholder: 'https://x.com/username', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background (Page)', type: 'color', placeholder: '#f8f6f0', section: 'theme' },
        { key: 'colorSurface', label: 'Card Surface', type: 'color', placeholder: '#ffffff', section: 'theme' },
        { key: 'colorSurfaceAlt', label: 'Card Surface (alt)', type: 'color', placeholder: '#f1eee5', section: 'theme' },
        { key: 'colorInk', label: 'Foreground (Ink)', type: 'color', placeholder: '#1a1a17', section: 'theme' },
        { key: 'colorInkMuted', label: 'Foreground Muted', type: 'color', placeholder: '#5c5c54', section: 'theme' },
        { key: 'colorInkFaint', label: 'Foreground Faint', type: 'color', placeholder: '#a09c8f', section: 'theme' },
        { key: 'colorLine', label: 'Line / Border', type: 'color', placeholder: '#e3dfd2', section: 'theme' },
        { key: 'colorAccent', label: 'Accent', type: 'color', placeholder: '#6e8c64', section: 'theme' },
        { key: 'colorAccentSoft', label: 'Accent Soft', type: 'color', placeholder: '#dfe7d8', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Sam Aldrich',
    role: 'Senior Full-Stack Engineer',
    tagline: 'Building software that earns its place.',
    subtitle: 'I help product teams turn rough ideas into shipped features — calm, well-tested, and built to last.',
    availability: 'Open to roles · Q3 2026',
    location: 'Amsterdam, NL',
    photoUrl: '',
    resumeUrl: '',
    stat1Num: '8', stat1Label: 'Years Shipping',
    stat2Num: '60+', stat2Label: 'Features Delivered',
    stat3Num: '14', stat3Label: 'Teams Joined',
    stat4Num: '24', stat4Label: 'OSS Merges',

    aboutSectionLabel: '/01 — About',
    aboutHeading: 'A short version of a longer story.',
    aboutPara1: 'I started building software because I wanted my school projects to feel like real apps — and then realised most real apps could feel a lot better. Eight years on, that instinct still drives most of what I do.',
    aboutPara2: 'Today I lead a small frontend squad on a B2B analytics product. Before that I was the first hire at a creative-tools startup, an SDK engineer at a fintech, and a lone contractor before any of that.',
    aboutPara3: 'Outside the IDE I bake very specific kinds of sourdough, run slow trails, and lose a lot of evenings to a synthesizer I do not entirely understand yet.',
    focus: 'Frontend systems & dev tooling',
    timezone: 'CET · UTC+1',
    languages: 'EN · NL',
    education: 'B.Sc. CS · TU Delft',

    skillsSectionLabel: '/02 — Skills',
    skillsHeading: 'The tools I reach for.',
    skillsSub: 'A grouped view of what I work with day-to-day, sharpest at the top of each card.',
    skillsJson: JSON.stringify([
      { category: 'Languages', items: 'TypeScript, JavaScript, Go, Python, SQL' },
      { category: 'Frameworks', items: 'React, Next.js, Remix, Node.js, Vite' },
      { category: 'Data & APIs', items: 'PostgreSQL, Prisma, tRPC, GraphQL, Redis' },
      { category: 'Tooling', items: 'Turborepo, pnpm, Vitest, Playwright, Storybook' },
      { category: 'Cloud & Ops', items: 'Vercel, AWS, Docker, GitHub Actions, Sentry' },
      { category: 'Craft', items: 'Design systems, A11y, Perf budgets, Animation' },
    ]),

    expSectionLabel: '/03 — Experience',
    expHeading: "Where I've done the work.",
    expJson: JSON.stringify([
      {
        period: 'Mar 2024 – Present', nowLabel: 'Now', duration: '2 yrs',
        role: 'Senior Frontend Engineer', company: 'Northwind Analytics · B2B SaaS',
        employmentType: 'Full-time',
        summary: 'Leading the dashboard surface used by 3,400+ teams across analytics & billing flows.',
        bullets: 'Redesigned the chart layer on a virtualized canvas — first paint −38%\nLed the Radix-based design-system migration across 140+ components\nCut bundle size by −34% via route-level code splitting\nWrote the team a11y checklist; product hit WCAG 2.2 AA\nMentored three engineers through their first production releases',
        stack: 'TypeScript, React, Next.js, tRPC, Postgres, Tailwind, Playwright',
        isCurrent: true,
      },
      {
        period: 'Jul 2022 – Feb 2024', nowLabel: '', duration: '1 yr 8 mos',
        role: 'Founding Frontend Engineer', company: 'Spool Studio · Creative-tools startup',
        employmentType: 'Full-time',
        summary: 'First frontend hire at a creative-tools company; owned the editor surface end-to-end.',
        bullets: 'Built the multiplayer canvas editor (CRDT-backed) from scratch\nShipped 14 major releases, growing DAU from 0 to 11k\nIntegrated Stripe & built the billing UI for 3 pricing tiers\nWrote the engineering interview loop that hired the next 4 hires',
        stack: 'TypeScript, React, Yjs, WebGL, Tailwind, Vitest',
        isCurrent: false,
      },
      {
        period: 'Aug 2020 – Jun 2022', nowLabel: '', duration: '1 yr 10 mos',
        role: 'SDK Engineer', company: 'Loop Finance · Fintech, Series B',
        employmentType: 'Full-time',
        summary: 'Built and maintained the public JS SDK used by 1,800+ integrating teams.',
        bullets: 'Designed v2 SDK with tree-shakable surface and TS-first DX\nCut p95 init time from 320ms to 90ms\nWrote the SDK docs site that became internal a11y reference\nFielded weekly office hours with 30+ integrating teams',
        stack: 'TypeScript, React, Node.js, Webpack, Rollup, Vitest',
        isCurrent: false,
      },
    ]),

    projSectionLabel: '/04 — Selected Work',
    projHeading: 'Things I have built.',
    projSub: 'Client work, side projects, and small experiments — mostly the ones I keep going back to.',
    projJson: JSON.stringify([
      { title: 'Beacon', tag: '2026 · Solo', desc: 'A keyboard-first dashboard tool for indie devs. Save layouts as URLs, share via a single link. Used by ~280 daily.', stack: 'Next.js, TypeScript, Postgres, Tailwind', liveUrl: '', githubUrl: '' },
      { title: 'Quill', tag: '2025 · 2 contributors', desc: 'A markdown notes app with a built-in command palette and AI-powered linking. Designed to feel like a text file.', stack: 'React, IndexedDB, Tauri, OpenAI', liveUrl: '', githubUrl: '' },
      { title: 'Riverbed', tag: '2025 · OSS', desc: 'A tiny status-page-as-a-service for indie devs. One markdown file becomes a hosted status page.', stack: 'Astro, Cloudflare Workers, KV', liveUrl: '', githubUrl: '' },
      { title: 'Carbide', tag: '2024 · Client', desc: 'A friendly community platform for a 12k-member dev meetup. Threaded talks, RSVPs, calendar sync.', stack: 'Next.js, Postgres, Supabase, Resend', liveUrl: '', githubUrl: '' },
      { title: 'Notch', tag: '2024 · Hackathon', desc: 'Won a 48-hour build for indie musicians: a visual map of songs by mood, BPM, and key.', stack: 'Next.js, D3, Spotify API', liveUrl: '', githubUrl: '' },
      { title: 'Inkwell', tag: '2023 · Learning', desc: 'My first deployed project. A minimalist writing app with a typewriter mode and focus timer.', stack: 'React, Vite, Vercel', liveUrl: '', githubUrl: '' },
    ]),

    eduSectionLabel: '/05 — Background',
    eduHeading: 'Where I learned to build.',
    educationJson: JSON.stringify([
      { school: 'TU Delft', degree: 'B.Sc. Computer Science', period: '2014 – 2018', detail: 'GPA 8.3/10 · Thesis on incremental compilers · Two semesters teaching the intro CS lab.' },
      { school: 'Self-taught · Continuous', degree: 'Continuous learning', period: '2017 – Now', detail: 'Frontend Masters, Theo, Kent C. Dodds, Wes Bos. One dev book a month, consistently.' },
    ]),
    certsJson: JSON.stringify([
      { name: 'AWS Solutions Architect — Associate', issuer: 'Amazon Web Services', year: '2024', url: '' },
      { name: 'Frontend Masters · Bootcamp', issuer: 'Frontend Masters', year: '2023', url: '' },
      { name: 'Epic React (Pro)', issuer: 'Kent C. Dodds', year: '2022', url: '' },
    ]),

    contactSectionLabel: '/06 — Contact',
    contactHeadline: 'Have a project in mind?',
    contactSub: 'I am open to senior frontend roles and a small number of consulting engagements each year. Email is the fastest way to reach me.',
    contactEmail: 'hello@samaldrich.dev',
    githubUrl: 'https://github.com/samaldrich',
    linkedinUrl: 'https://linkedin.com/in/samaldrich',
    twitterUrl: 'https://x.com/samaldrich',

    colorBg: '#f8f6f0',
    colorSurface: '#ffffff',
    colorSurfaceAlt: '#f1eee5',
    colorInk: '#1a1a17',
    colorInkMuted: '#5c5c54',
    colorInkFaint: '#a09c8f',
    colorLine: '#e3dfd2',
    colorAccent: '#6e8c64',
    colorAccentSoft: '#dfe7d8',
  },
};

export default quartzConfig;
