import type { TemplateConfig } from '@/types';

const solaceConfig: TemplateConfig = {
  slug: 'solace',
  name: 'Solace Template',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', placeholder: 'Solace Ahmadi', section: 'hero' },
        { key: 'title', label: 'Title / Role', type: 'text', placeholder: 'Brand & Web Designer', section: 'hero' },
        { key: 'tagline', label: 'Tagline', type: 'textarea', placeholder: 'I help small teams launch warm, human websites that actually convert.', section: 'hero' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', placeholder: 'Working with founders, studios and indie makers since 2018. Cozy process, sharp output.', section: 'hero' },
        { key: 'availability', label: 'Availability Badge', type: 'text', placeholder: 'Available for new projects · Booking June onward', section: 'hero' },
      ],
    },
    {
      key: 'services',
      label: 'Services',
      fields: [],
    },
    {
      key: 'process',
      label: 'Process',
      fields: [],
    },
    {
      key: 'projects',
      label: 'Projects',
      fields: [],
    },
    {
      key: 'packages',
      label: 'Packages',
      fields: [],
    },
    {
      key: 'testimonials',
      label: 'Testimonials',
      fields: [],
    },
    {
      key: 'faq',
      label: 'FAQ',
      fields: [],
    },
    {
      key: 'contact',
      label: 'Contact',
      fields: [
        { key: 'contactEmail', label: 'Email Address', type: 'text', placeholder: 'hello@solaceahmadi.co', section: 'contact' },
        { key: 'contactPhone', label: 'Phone Number', type: 'text', placeholder: '+1 (555) 014-2230', section: 'contact' },
        { key: 'contactLocation', label: 'Location', type: 'text', placeholder: 'Portland, OR · Working worldwide', section: 'contact' },
        { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'url', placeholder: 'https://linkedin.com/in/username', section: 'contact' },
        { key: 'twitterUrl', label: 'Twitter URL', type: 'url', placeholder: 'https://twitter.com/username', section: 'contact' },
        { key: 'instagramUrl', label: 'Instagram URL', type: 'url', placeholder: 'https://instagram.com/username', section: 'contact' },
        { key: 'dribbbleUrl', label: 'Dribbble URL', type: 'url', placeholder: 'https://dribbble.com/username', section: 'contact' },
      ],
    },
    {
      key: 'theme',
      label: 'Theme & Colors',
      fields: [
        { key: 'colorBg', label: 'Background (cream)', type: 'color', placeholder: '#fdf6ee', section: 'theme' },
        { key: 'colorFg', label: 'Foreground (text)', type: 'color', placeholder: '#2a1f1a', section: 'theme' },
        { key: 'colorAccent', label: 'Accent (terracotta)', type: 'color', placeholder: '#c95f3f', section: 'theme' },
        { key: 'colorAccent2', label: 'Accent 2 (sage)', type: 'color', placeholder: '#7d9b7d', section: 'theme' },
        { key: 'colorLine', label: 'Border / Line', type: 'color', placeholder: '#ecddc8', section: 'theme' },
        { key: 'colorCard', label: 'Card Background', type: 'color', placeholder: '#fffaf3', section: 'theme' },
      ],
    },
  ],
  defaultContent: {
    name: 'Solace Ahmadi',
    title: 'Brand & Web Designer',
    tagline: 'I help small teams launch warm, human websites that actually convert.',
    subtitle: 'Working with founders, studios and indie makers since 2018. Cozy process, sharp output.',
    availability: 'Available for new projects · Booking June onward',
    contactEmail: 'hello@solaceahmadi.co',
    contactPhone: '+1 (555) 014-2230',
    contactLocation: 'Portland, OR · Working worldwide',
    linkedinUrl: 'https://linkedin.com/in/solace-ahmadi',
    twitterUrl: 'https://twitter.com/solaceahmadi',
    instagramUrl: 'https://instagram.com/solace.studio',
    dribbbleUrl: 'https://dribbble.com/solaceahmadi',
    heroStatsJson: JSON.stringify([
      { label: 'Happy clients', value: '60+' },
      { label: 'Projects shipped', value: '120' },
      { label: 'Years freelancing', value: '6' },
      { label: 'Avg. rating', value: '4.9/5' },
    ]),
    servicesJson: JSON.stringify([
      {
        icon: 'brush',
        title: 'Brand Identity',
        description: 'Logos, type systems and visual languages that feel like you — not a stock template.',
        startingPrice: 'from $2,400',
        features: 'Logo suite\nColor & type system\nBrand guidelines\nSocial templates',
      },
      {
        icon: 'monitor',
        title: 'Website Design',
        description: 'Warm, conversion-minded websites designed in Figma and ready to hand off or build.',
        startingPrice: 'from $3,800',
        features: 'Up to 6 pages\nMobile-first\nFigma source files\nClickable prototype',
      },
      {
        icon: 'code',
        title: 'Web Development',
        description: 'Hand-coded Next.js sites with smooth motion and accessible, semantic markup.',
        startingPrice: 'from $4,500',
        features: 'Next.js + TypeScript\nCMS integration\nSEO ready\nAnalytics setup',
      },
      {
        icon: 'spark',
        title: 'Landing Pages',
        description: 'Single-page sprints for launches, product drops, and campaigns. Fast turnaround.',
        startingPrice: 'from $1,400',
        features: '2-week turnaround\nCopy + visuals\nA/B variants\nLaunch checklist',
      },
      {
        icon: 'compass',
        title: 'Brand Strategy',
        description: 'Positioning, voice and messaging workshops to find the words before we design.',
        startingPrice: 'from $1,800',
        features: 'Discovery workshop\nVoice + tone guide\nMessaging map\nCompetitor audit',
      },
      {
        icon: 'palette',
        title: 'Design Retainers',
        description: 'Ongoing design support for teams that need a steady hand each month.',
        startingPrice: 'from $2,000/mo',
        features: 'Async + sync\nSlack + Figma\nPriority queue\nMonthly review',
      },
    ]),
    processJson: JSON.stringify([
      {
        step: '01',
        title: 'Discovery call',
        description: 'A friendly 30-minute chat to understand your goals, audience and timeline. No pressure, just a real conversation.',
        duration: '30 min',
      },
      {
        step: '02',
        title: 'Proposal & scope',
        description: 'A clear, fixed-price proposal with deliverables, milestones and dates — no surprises down the line.',
        duration: '2 days',
      },
      {
        step: '03',
        title: 'Design sprints',
        description: 'Weekly check-ins, shared Figma boards and async Loom updates so you always know where we are.',
        duration: '2–4 weeks',
      },
      {
        step: '04',
        title: 'Build & polish',
        description: 'I hand-code your site with care, testing across devices, browsers and screen readers before launch day.',
        duration: '1–2 weeks',
      },
      {
        step: '05',
        title: 'Handoff & launch',
        description: 'Polished files, recorded walkthroughs, and 30 days of post-launch support included with every project.',
        duration: '1 week',
      },
    ]),
    projectsJson: JSON.stringify([
      {
        title: 'Foundry & Loom',
        client: 'Foundry & Loom',
        industry: 'E-commerce · Home goods',
        summary: 'Rebuilt the brand and Shopify storefront for a small-batch textile studio in Portland.',
        result: '+38% conversion · 2.4× avg. order value',
        tags: 'Brand, Shopify, Photography',
        liveUrl: 'https://foundryandloom.example.com',
      },
      {
        title: 'Northbound Coffee',
        client: 'Northbound Coffee',
        industry: 'Hospitality · DTC',
        summary: 'A warm subscription site with playful illustrations and a quiz-driven onboarding flow.',
        result: '5,200 new subscribers in 90 days',
        tags: 'Web, Illustration, Copy',
        liveUrl: 'https://northbound.example.com',
      },
      {
        title: 'Maple Health',
        client: 'Maple Health',
        industry: 'SaaS · Wellness',
        summary: 'Marketing site refresh for a Series A wellness platform with a strict accessibility bar.',
        result: 'WCAG AA · 96 Lighthouse',
        tags: 'Next.js, Design system, A11y',
        liveUrl: 'https://maplehealth.example.com',
      },
      {
        title: 'Pebble Studio',
        client: 'Pebble Studio',
        industry: 'Agency · Design',
        summary: 'Identity and website for a two-person creative studio relaunching after a 3-year hiatus.',
        result: 'Booked solid through Q3',
        tags: 'Brand, Web, Print',
        liveUrl: 'https://pebble.example.com',
      },
      {
        title: 'Little Lantern Books',
        client: 'Little Lantern Books',
        industry: 'Publishing · Indie',
        summary: 'A cozy storefront and reading-club platform for an independent children’s publisher.',
        result: '12k readers in the first year',
        tags: 'Brand, Web, Editorial',
        liveUrl: 'https://littlelantern.example.com',
      },
    ]),
    packagesJson: JSON.stringify([
      {
        name: 'Starter',
        price: '$1,400',
        period: 'one-time',
        description: 'Perfect for solo founders who need a beautiful one-pager to launch this month.',
        features: 'One-page website\nMobile responsive\nBasic SEO setup\n2 revision rounds\n2-week delivery',
        cta: 'Get started',
        highlighted: false,
      },
      {
        name: 'Pro',
        price: '$3,800',
        period: 'one-time',
        description: 'Most teams pick this. A complete website, brand polish, and a smooth launch.',
        features: 'Up to 6 pages\nCustom brand polish\nCMS integration\nUnlimited revisions\n4-week delivery\n30-day support',
        cta: 'Book Pro package',
        highlighted: true,
      },
      {
        name: 'Custom',
        price: "Let's talk",
        period: 'project-based',
        description: 'For ambitious projects: design systems, multi-language, complex integrations.',
        features: 'Everything in Pro\nDesign system\nCustom integrations\nDedicated Slack channel\nFlexible timeline\nPriority support',
        cta: 'Start a conversation',
        highlighted: false,
      },
    ]),
    testimonialsJson: JSON.stringify([
      {
        quote: 'Solace felt like a true partner from day one. The kind of designer who actually listens, then quietly makes everything better.',
        name: 'Jules Tanaka',
        role: 'Founder',
        company: 'Foundry & Loom',
        rating: 5,
      },
      {
        quote: 'We went from a rough idea to a launched site in five weeks. The process was calm, organized, and surprisingly fun.',
        name: 'Marcus Bell',
        role: 'CEO',
        company: 'Northbound Coffee',
        rating: 5,
      },
      {
        quote: 'Detail-oriented without being precious. Solace pushed back on the right things and trusted us on the rest.',
        name: 'Priya Reddy',
        role: 'Head of Marketing',
        company: 'Maple Health',
        rating: 5,
      },
      {
        quote: "Hands down the best freelancer we've worked with. We've already booked her for next year.",
        name: 'Sam Okafor',
        role: 'Co-founder',
        company: 'Pebble Studio',
        rating: 5,
      },
    ]),
    faqJson: JSON.stringify([
      {
        question: 'How does the process actually start?',
        answer: "Book a free 30-minute call. If we're a fit, I send a fixed-price proposal within 2 business days. A 30% deposit kicks things off.",
      },
      {
        question: 'How long does a typical project take?',
        answer: 'Landing pages take 1–2 weeks. Full sites and brand projects usually run 4–6 weeks. I only take on 2–3 projects at a time so each one gets real attention.',
      },
      {
        question: 'Do you work with international clients?',
        answer: 'Yes! Roughly half of my clients are outside the US. I keep flexible hours and use async tools (Loom, Notion, Slack) so timezones rarely matter.',
      },
      {
        question: 'What if I need ongoing help after launch?',
        answer: 'Every project includes 30 days of post-launch support. After that, I offer monthly design retainers starting at $2,000/mo.',
      },
      {
        question: 'Do you write the copy too?',
        answer: 'I do light editing and headlines as part of every project. For long-form copy I partner with two trusted writers and can bring them in.',
      },
      {
        question: 'What does payment look like?',
        answer: '30% deposit to kick off, 40% at design approval, 30% at launch. I accept bank transfer, Wise and Stripe — whatever is easiest for you.',
      },
      {
        question: 'Can you work with my existing brand?',
        answer: "Absolutely. If you already have a brand you love, I'll work within it. If it needs a refresh, we can scope a light polish into the project.",
      },
    ]),
    colorBg: '#fdf6ee',
    colorFg: '#2a1f1a',
    colorAccent: '#c95f3f',
    colorAccent2: '#7d9b7d',
    colorLine: '#ecddc8',
    colorCard: '#fffaf3',
  },
};

export default solaceConfig;
